import { ArrowLeft } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { BlogCard } from "../components/blog-card";
import { BlogContent } from "../components/blog-content";
import { BlogDiagnosticCta } from "../components/blog-diagnostic-cta";
import { SeoHead } from "../components/seo-head";
import { blogDataSource } from "../data-source";
import { usePublicPost, usePublicPosts } from "../hooks";
import { readingMinutes } from "../types";
export function BlogPostPage(){const{slug=""}=useParams();const post=usePublicPost(slug);const related=usePublicPosts({category:post.data?.categorySlug,page:1,pageSize:4});if(post.isLoading)return <div className="mx-auto max-w-3xl px-5 py-24 text-center text-muted-foreground">Carregando artigo…</div>;if(!post.data)return <><SeoHead title="Artigo não encontrado | ESADS Beauty" description="Este conteúdo não está disponível." path={`/blog/${slug}`} noIndex/><div className="mx-auto max-w-xl px-5 py-28 text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-champagne-dark">404</p><h1 className="mt-4 text-4xl font-semibold">Artigo não encontrado</h1><p className="mt-4 text-muted-foreground">O conteúdo pode ter sido retirado do ar ou o endereço está incorreto.</p><Link className="mt-8 inline-flex rounded-full bg-primary px-6 py-3 font-semibold text-primary-foreground" to="/blog">Voltar ao blog</Link></div></>;const item=post.data,image=blogDataSource.coverUrl(item.coverImagePath),more=(related.data?.items??[]).filter(value=>value.id!==item.id).slice(0,3);return <><SeoHead title={`${item.seoTitle||item.title} | ESADS Beauty`} description={item.seoDescription||item.excerpt} path={`/blog/${item.slug}`} image={image} type="article"/><article><header className="mx-auto max-w-4xl px-5 pb-10 pt-12 text-center md:px-8 md:pb-14 md:pt-20"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground" to="/blog"><ArrowLeft size={17}/> Voltar ao blog</Link><p className="mt-10 text-xs font-bold uppercase tracking-[.18em] text-champagne-dark">{item.categoryName??"Conteúdo"}</p><h1 className="mt-4 text-[2.6rem] font-semibold leading-[1.07] tracking-[-.055em] md:text-6xl">{item.title}</h1><p className="mx-auto mt-6 max-w-2xl text-[18px] leading-8 text-muted-foreground">{item.excerpt}</p><p className="mt-6 text-sm text-muted-foreground">Por {item.authorName} · {item.publishedAt&&new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(item.publishedAt))} · {readingMinutes(item.content)} min de leitura</p></header>{image&&<div className="mx-auto max-w-5xl px-5 md:px-8"><img src={image} alt="" width="1200" height="675" className="aspect-[16/9] w-full rounded-[1.5rem] object-cover"/></div>}<div className="mx-auto max-w-[46rem] px-5 py-12 md:px-8 md:py-16"><BlogContent content={item.content}/><BlogDiagnosticCta placement="final"/></div></article>{more.length>0&&<section className="mx-auto max-w-6xl px-5 pb-12 md:px-8"><h2 className="text-3xl font-semibold tracking-[-.04em]">Continue lendo</h2><div className="mt-7 grid gap-6 md:grid-cols-3">{more.map(value=><BlogCard key={value.id} post={value}/>)}</div></section>}</>}
