import type{DiagnosticQuestion}from"./types";
const options=(labels:string[])=>labels.map((label,index)=>({key:(['a','b','c','d'] as const)[index],label}));
export const diagnosticQuestions:DiagnosticQuestion[]=[
{key:"acquisition",category:"acquisition",title:"Hoje, como as pessoas descobrem o seu trabalho?",options:options(["Ainda estou começando e quase ninguém conhece meu trabalho","Principalmente através de indicações","Pelo Instagram e outras redes sociais","Já uso algumas formas diferentes para conseguir novos clientes"])},
{key:"service",category:"service",title:"Quando alguém chama você no Instagram ou WhatsApp querendo saber mais sobre um serviço, como costuma ser?",options:options(["Ainda recebo poucas mensagens","Respondo quando consigo","Tento responder rapidamente","Já tenho uma forma organizada de atender essas pessoas"])},
{key:"organization",category:"organization",title:"Onde você guarda os contatos das pessoas que demonstraram interesse nos seus serviços?",options:options(["Ficam somente nas conversas do WhatsApp ou Instagram","Uso agenda, caderno ou bloco de notas","Uso uma planilha","Tenho uma forma organizada de acompanhar esses contatos"])},
{key:"follow_up",category:"follow_up",title:"Quando uma pessoa pergunta o preço, demonstra interesse e depois desaparece, o que você costuma fazer?",options:options(["Normalmente não entro mais em contato","Às vezes lembro e mando outra mensagem","Costumo chamar novamente","Tenho o hábito de acompanhar essas pessoas até ter uma resposta"])},
{key:"metrics",category:"metrics",title:"Hoje você sabe aproximadamente quantas pessoas pedem informações e quantas realmente viram clientes?",options:options(["Não faço ideia","Tenho apenas uma noção","Às vezes acompanho","Sim, costumo acompanhar isso"])},
{key:"demand",category:"demand",title:"Como está sua agenda atualmente?",options:options(["Estou começando e ainda tenho poucos atendimentos","Tenho bastante horário disponível","Tenho alguns dias bons e outros mais parados","Minha agenda já possui uma boa frequência de clientes"])},
{key:"business_stage",category:"business_stage",title:"Qual dessas opções representa melhor o momento do seu negócio?",options:options(["Estou começando agora","Já tenho alguns clientes, mas ainda é muito instável","Já tenho uma clientela e quero crescer","Já tenho bastante movimento e quero organizar melhor o negócio"])},
{key:"marketing",category:"marketing",title:"Como está a divulgação do seu trabalho hoje?",options:options(["Quase não divulgo","Posto de vez em quando","Tento manter meu Instagram ativo","Tenho uma rotina para divulgar meus serviços e atrair clientes"])},
{key:"financial_clarity",category:"financial_clarity",title:"Você sabe quanto precisa faturar por mês para manter o negócio funcionando e ainda ter lucro?",options:options(["Ainda não sei","Tenho uma ideia","Já fiz algumas contas","Sim, tenho uma meta definida"])},
{key:"primary_need",category:"primary_need",title:"Se você pudesse melhorar uma coisa no seu negócio hoje, qual seria?",options:options(["Conseguir mais clientes","Fazer mais pessoas que pedem informação realmente agendarem","Organizar melhor meus clientes, contatos e rotina","Faturar mais e deixar meu negócio mais estável"])},
];
