import type { DreGroup, FinanceData, Payable, Receivable, RecurrenceRule } from "./types";

export const money = (value:number) => Math.round((value + Number.EPSILON) * 100) / 100;
export function netAmount(input:{originalAmount:number;discountAmount?:number;interestAmount?:number;penaltyAmount?:number}) { return money(input.originalAmount-(input.discountAmount??0)+(input.interestAmount??0)+(input.penaltyAmount??0)); }
export function allocatedAmount(entryId:string,type:"receivable"|"payable",data:FinanceData){return money(data.allocations.filter((item)=>type==="receivable"?item.receivableId===entryId:item.payableId===entryId).filter((item)=>!data.transactions.find((tx)=>tx.id===item.transactionId)?.reversedAt).reduce((sum,item)=>sum+item.amount,0));}
export function entryBalance(entry:Receivable|Payable,type:"receivable"|"payable",data:FinanceData){return money(Math.max(0,entry.netAmount-allocatedAmount(entry.id,type,data)));}
export function derivedStatus(entry:Receivable|Payable,type:"receivable"|"payable",data:FinanceData, today=new Date().toISOString().slice(0,10)){if(entry.status==="cancelled"||entry.status==="refunded")return entry.status;const paid=allocatedAmount(entry.id,type,data);if(paid>=entry.netAmount)return "paid";if(paid>0)return "partially_paid";if(entry.dueDate<today)return "overdue";return "pending";}
export function agingBucket(days:number){if(days<=7)return "1–7 dias";if(days<=15)return "8–15 dias";if(days<=30)return "16–30 dias";if(days<=60)return "31–60 dias";if(days<=90)return "61–90 dias";return "90+ dias";}
export function splitInstallments(total:number,count:number){if(count<1||!Number.isInteger(count))throw new Error("Quantidade de parcelas inválida.");const cents=Math.round(total*100);const base=Math.floor(cents/count);return Array.from({length:count},(_,index)=>(index===count-1?cents-base*(count-1):base)/100);}
export function calculateMrr(rules:RecurrenceRule[]){return money(rules.filter((rule)=>rule.isActive&&rule.type==="receivable").reduce((sum,rule)=>sum+rule.amount/(rule.frequency==="monthly"?1:rule.frequency==="quarterly"?3:rule.frequency==="semiannual"?6:12),0));}
export function dashboard(data:FinanceData,from:string,to:string){const validTx=data.transactions.filter((item)=>!item.reversedAt&&item.occurredAt.slice(0,10)>=from&&item.occurredAt.slice(0,10)<=to);const received=money(validTx.filter((item)=>item.type==="income").reduce((s,i)=>s+i.amount,0));const paid=money(validTx.filter((item)=>item.type==="expense").reduce((s,i)=>s+i.amount,0));const receivableBalances=data.receivables.filter((item)=>item.status!=="cancelled").map((item)=>({item,balance:entryBalance(item,"receivable",data)}));const payableBalances=data.payables.filter((item)=>item.status!=="cancelled").map((item)=>entryBalance(item,"payable",data));const accountBalance=money(data.accounts.reduce((s,a)=>s+a.initialBalance,0)+data.transactions.filter((item)=>!item.reversedAt).reduce((s,item)=>s+(item.type==="income"?item.amount:item.type==="expense"?-item.amount:0),0));return {receivable:money(receivableBalances.reduce((s,i)=>s+i.balance,0)),overdue:money(receivableBalances.filter(({item,balance})=>balance>0&&item.dueDate<new Date().toISOString().slice(0,10)).reduce((s,i)=>s+i.balance,0)),payable:money(payableBalances.reduce((s,i)=>s+i,0)),received,paid,result:money(received-paid),accountBalance,mrr:calculateMrr(data.recurrences)};}
export function accountBalance(accountId:string,data:FinanceData){const account=data.accounts.find(item=>item.id===accountId);return money((account?.initialBalance??0)+data.transactions.filter(item=>item.financialAccountId===accountId&&!item.reversedAt).reduce((sum,item)=>sum+(item.type==="income"?item.amount:item.type==="expense"?-item.amount:0),0));}
export function cashFlow(data:FinanceData,mode:"actual"|"forecast",from:string,to:string,accountId?:string){let balance=accountId?accountBalance(accountId,data):dashboard(data,"0000-01-01","9999-12-31").accountBalance;const scoped=data.transactions.filter(item=>!item.reversedAt&&(!accountId||item.financialAccountId===accountId));const actual=scoped.filter(item=>item.occurredAt.slice(0,10)>=from&&item.occurredAt.slice(0,10)<=to).sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt)).map(item=>({id:item.id,date:item.occurredAt.slice(0,10),description:item.description,accountId:item.financialAccountId,income:item.type==="income"?item.amount:0,expense:item.type==="expense"?item.amount:0,actual:true}));if(mode==="actual"){balance=(accountId?(data.accounts.find(x=>x.id===accountId)?.initialBalance??0):data.accounts.reduce((s,x)=>s+x.initialBalance,0))+scoped.filter(item=>item.occurredAt.slice(0,10)<from).reduce((sum,item)=>sum+(item.type==="income"?item.amount:item.type==="expense"?-item.amount:0),0);return actual.map(item=>({...item,balance:balance=money(balance+item.income-item.expense)}));}const forecast=[...data.receivables.filter(item=>item.status!=="cancelled"&&item.dueDate>=from&&item.dueDate<=to&&(!accountId||item.financialAccountId===accountId)).map(item=>({id:item.id,date:item.dueDate,description:item.description,accountId:item.financialAccountId,income:entryBalance(item,"receivable",data),expense:0,actual:false})),...data.payables.filter(item=>item.status!=="cancelled"&&item.dueDate>=from&&item.dueDate<=to&&(!accountId||item.financialAccountId===accountId)).map(item=>({id:item.id,date:item.dueDate,description:item.description,accountId:item.financialAccountId,income:0,expense:entryBalance(item,"payable",data),actual:false}))].filter(item=>item.income+item.expense>0).sort((a,b)=>a.date.localeCompare(b.date));return forecast.map(item=>({...item,balance:balance=money(balance+item.income-item.expense)}));}
export function dre(data:FinanceData,from:string,to:string){const groups:Record<DreGroup,number>={gross_revenue:0,deduction:0,direct_cost:0,operating_expense:0,other_income:0,other_expense:0};for(const entry of [...data.receivables,...data.payables]){if(entry.status==="cancelled"||entry.competenceDate<from||entry.competenceDate>to)continue;const group=data.categories.find((category)=>category.id===entry.categoryId)?.dreGroup;if(group)groups[group]=money(groups[group]+entry.netAmount);}const netRevenue=money(groups.gross_revenue-groups.deduction);const grossMargin=money(netRevenue-groups.direct_cost);const operatingResult=money(grossMargin-groups.operating_expense);return {groups,netRevenue,grossMargin,grossMarginPercent:netRevenue?money(grossMargin/netRevenue*100):0,operatingResult,managerialResult:money(operatingResult+groups.other_income-groups.other_expense)};}
