import { entryBalance, netAmount, splitInstallments } from "./domain";
import type { FinanceRepository } from "./repository-contract";
import type { FinanceData, Payable, Receivable } from "./types";
const STORAGE="esads_finance_data_v1",ORG="esads-beauty",USER="preview-admin";const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString();
const empty=():FinanceData=>({accounts:[],categories:[],costCenters:[],receivables:[],payables:[],transactions:[],allocations:[],recurrences:[]});
const read=()=>{const value=localStorage.getItem(STORAGE);return value?JSON.parse(value) as FinanceData:empty();};const write=(data:FinanceData)=>localStorage.setItem(STORAGE,JSON.stringify(data));
const addMonths=(date:string,months:number)=>{const next=new Date(`${date}T12:00:00Z`);next.setUTCMonth(next.getUTCMonth()+months);return next.toISOString().slice(0,10);};
function entry<T extends "receivable"|"payable">(type:T,input:T extends "receivable"?Parameters<FinanceRepository["createReceivable"]>[0]:Parameters<FinanceRepository["createPayable"]>[0]){const stamp=now();return {id:id(),organizationId:ORG,...input,discountAmount:input.discountAmount??0,interestAmount:input.interestAmount??0,penaltyAmount:input.penaltyAmount??0,netAmount:netAmount(input),status:"pending" as const,createdAt:stamp,updatedAt:stamp};}
export const financeRepository:FinanceRepository={
 async list(){return read();},
 async createAccount(input){const data=read();const item={id:id(),organizationId:ORG,...input,isActive:true,createdAt:now(),updatedAt:now()};data.accounts.push(item);write(data);return item;},
 async createCategory(input){const data=read();const item={id:id(),organizationId:ORG,...input,isActive:true,createdAt:now(),updatedAt:now()};data.categories.push(item);write(data);return item;},
 async createCostCenter(input){const data=read();const item={id:id(),organizationId:ORG,...input,isActive:true,createdAt:now(),updatedAt:now()};data.costCenters.push(item);write(data);return item;},
 async createReceivable(input){const data=read();const item=entry("receivable",input) as Receivable;data.receivables.push(item);write(data);return item;},
 async createPayable(input){const data=read();const item=entry("payable",input) as Payable;data.payables.push(item);write(data);return item;},
 async receivePayment(input){const data=read();const target=data.receivables.find((item)=>item.id===input.entryId);if(!target||target.status==="cancelled")throw new Error("Cobrança não encontrada.");const balance=entryBalance(target,"receivable",data);if(input.amount<=0||input.amount>balance)throw new Error("O valor deve ser positivo e não pode superar o saldo.");const tx={id:id(),organizationId:ORG,financialAccountId:input.financialAccountId,type:"income" as const,amount:input.amount,occurredAt:input.occurredAt,description:`Recebimento: ${target.description}`,paymentMethod:input.paymentMethod,reference:input.reference,createdBy:USER,createdAt:now()};data.transactions.push(tx);data.allocations.push({id:id(),organizationId:ORG,transactionId:tx.id,receivableId:target.id,amount:input.amount,createdAt:now()});target.status=input.amount===balance?"paid":"partially_paid";target.updatedAt=now();write(data);},
 async payExpense(input){const data=read();const target=data.payables.find((item)=>item.id===input.entryId);if(!target||target.status==="cancelled")throw new Error("Despesa não encontrada.");const balance=entryBalance(target,"payable",data);if(input.amount<=0||input.amount>balance)throw new Error("O valor deve ser positivo e não pode superar o saldo.");const tx={id:id(),organizationId:ORG,financialAccountId:input.financialAccountId,type:"expense" as const,amount:input.amount,occurredAt:input.occurredAt,description:`Pagamento: ${target.description}`,paymentMethod:input.paymentMethod,reference:input.reference,createdBy:USER,createdAt:now()};data.transactions.push(tx);data.allocations.push({id:id(),organizationId:ORG,transactionId:tx.id,payableId:target.id,amount:input.amount,createdAt:now()});target.status=input.amount===balance?"paid":"partially_paid";target.updatedAt=now();write(data);},
 async reverseTransaction(transactionId){const data=read();const tx=data.transactions.find((item)=>item.id===transactionId);if(!tx||tx.reversedAt)throw new Error("Movimentação não encontrada ou já estornada.");tx.reversedAt=now();for(const allocation of data.allocations.filter((item)=>item.transactionId===tx.id)){const target=allocation.receivableId?data.receivables.find((item)=>item.id===allocation.receivableId):data.payables.find((item)=>item.id===allocation.payableId);if(target)target.status="pending";}write(data);},
 async createRecurrence(input){const data=read();const item={id:id(),organizationId:ORG,...input,createdAt:now(),updatedAt:now()};data.recurrences.push(item);write(data);return item;},
 async generateRecurringEntries(ruleId,throughDate){const data=read();const rule=data.recurrences.find((item)=>item.id===ruleId&&item.isActive);if(!rule)throw new Error("Recorrência não encontrada.");let date=rule.nextGenerationDate,count=0;const months=(rule.frequency==="monthly"?1:rule.frequency==="quarterly"?3:rule.frequency==="semiannual"?6:12)*rule.intervalCount;while(date<=throughDate&&(!rule.endDate||date<=rule.endDate)){const key=`${rule.id}:${date.slice(0,7)}`;if(rule.type==="receivable"&&!data.receivables.some((item)=>item.recurrenceKey===key)){data.receivables.push({...entry("receivable",{description:rule.description,originalAmount:rule.amount,competenceDate:`${date.slice(0,7)}-01`,dueDate:date,categoryId:rule.categoryId,costCenterId:rule.costCenterId,customerAccountId:rule.customerAccountId,contractId:rule.contractId,customerServiceId:rule.customerServiceId}) as Receivable,recurrenceRuleId:rule.id,recurrenceKey:key});count++;}if(rule.type==="payable"&&!data.payables.some((item)=>item.recurrenceKey===key)){data.payables.push({...entry("payable",{supplierName:rule.supplierName??"Fornecedor",description:rule.description,originalAmount:rule.amount,competenceDate:`${date.slice(0,7)}-01`,dueDate:date,categoryId:rule.categoryId,costCenterId:rule.costCenterId}) as Payable,recurrenceRuleId:rule.id,recurrenceKey:key});count++;}date=addMonths(date,months);}rule.nextGenerationDate=date;rule.updatedAt=now();write(data);return count;},
 async createInstallments(input){const amounts=splitInstallments(input.originalAmount,input.installments);const result:Receivable[]=[];for(let index=0;index<amounts.length;index++)result.push(await this.createReceivable({...input,description:`${input.description} (${index+1}/${amounts.length})`,originalAmount:amounts[index],competenceDate:addMonths(input.competenceDate,index),dueDate:addMonths(input.dueDate,index)}));return result;}
};
