import { supabase } from "@/lib/supabase";
import type { Database } from "@/shared/types/database";
import { netAmount, splitInstallments } from "./domain";
import type { FinanceRepository } from "./repository-contract";
import type { FinanceData, Payable, Receivable } from "./types";
type T=Database["public"]["Tables"];const api=()=>{if(!supabase)throw new Error("Supabase não configurado.");return supabase;};const fail=(error:{message:string}|null)=>{if(error){console.error("[Finance]",error);throw new Error("Não foi possível concluir a operação financeira.");}};const optional=<V extends string|number>(value:V|null)=>value??undefined;
async function org(){const result=await api().rpc("current_organization_id");fail(result.error);if(!result.data)throw new Error("Organização não encontrada.");return result.data;}
const receivable=(r:T["receivables"]["Row"]):Receivable=>({id:r.id,organizationId:r.organization_id,customerAccountId:optional(r.customer_account_id),companyId:optional(r.company_id),contractId:optional(r.contract_id),customerServiceId:optional(r.customer_service_id),sourceOpportunityId:optional(r.source_opportunity_id),description:r.description,categoryId:optional(r.category_id),costCenterId:optional(r.cost_center_id),competenceDate:r.competence_date,dueDate:r.due_date,originalAmount:r.original_amount,discountAmount:r.discount_amount,interestAmount:r.interest_amount,penaltyAmount:r.penalty_amount,netAmount:r.net_amount,status:r.status,paymentMethod:r.payment_method as Receivable["paymentMethod"],notes:optional(r.notes),recurrenceRuleId:optional(r.recurrence_rule_id),recurrenceKey:optional(r.recurrence_key),createdAt:r.created_at,updatedAt:r.updated_at,cancelledAt:optional(r.cancelled_at)});
const payable=(r:T["payables"]["Row"]):Payable=>({id:r.id,organizationId:r.organization_id,supplierName:r.supplier_name,description:r.description,categoryId:optional(r.category_id),costCenterId:optional(r.cost_center_id),competenceDate:r.competence_date,dueDate:r.due_date,originalAmount:r.original_amount,discountAmount:r.discount_amount,interestAmount:r.interest_amount,penaltyAmount:r.penalty_amount,netAmount:r.net_amount,status:r.status,financialAccountId:optional(r.financial_account_id),notes:optional(r.notes),recurrenceRuleId:optional(r.recurrence_rule_id),recurrenceKey:optional(r.recurrence_key),createdAt:r.created_at,updatedAt:r.updated_at,cancelledAt:optional(r.cancelled_at)});
export const supabaseFinanceRepository:FinanceRepository={
 async list(){const c=api();const results=await Promise.all([c.from("financial_accounts").select("*").is("deleted_at",null),c.from("financial_categories").select("*").eq("is_active",true),c.from("cost_centers").select("*").eq("is_active",true),c.from("receivables").select("*").is("deleted_at",null).order("due_date"),c.from("payables").select("*").is("deleted_at",null).order("due_date"),c.from("financial_transactions").select("*").order("occurred_at",{ascending:false}),c.from("payment_allocations").select("*"),c.from("recurrence_rules").select("*")]);results.forEach((r)=>fail(r.error));const [a,categories,centers,r,p,t,alloc,rules]=results;return {accounts:(a.data??[]).map((x)=>({id:x.id,organizationId:x.organization_id,name:x.name,type:x.type,bankName:optional(x.bank_name),initialBalance:x.initial_balance,isActive:x.is_active,createdAt:x.created_at,updatedAt:x.updated_at})),categories:(categories.data??[]).map((x)=>({id:x.id,organizationId:x.organization_id,name:x.name,type:x.type,parentId:optional(x.parent_id),dreGroup:x.dre_group,isActive:x.is_active,createdAt:x.created_at,updatedAt:x.updated_at})),costCenters:(centers.data??[]).map((x)=>({id:x.id,organizationId:x.organization_id,name:x.name,description:optional(x.description),isActive:x.is_active,createdAt:x.created_at,updatedAt:x.updated_at})),receivables:(r.data??[]).map(receivable),payables:(p.data??[]).map(payable),transactions:(t.data??[]).map((x)=>({id:x.id,organizationId:x.organization_id,financialAccountId:x.financial_account_id,type:x.type,transferDirection:x.transfer_direction??undefined,amount:x.amount,occurredAt:x.occurred_at,description:x.description,paymentMethod:x.payment_method as FinanceData["transactions"][number]["paymentMethod"],reference:optional(x.reference),createdBy:x.created_by,reversedAt:optional(x.reversed_at),reversalOfId:optional(x.reversal_of_id),transferId:optional(x.transfer_id),createdAt:x.created_at})),allocations:(alloc.data??[]).map((x)=>({id:x.id,organizationId:x.organization_id,transactionId:x.transaction_id,receivableId:optional(x.receivable_id),payableId:optional(x.payable_id),amount:x.amount,createdAt:x.created_at})),recurrences:(rules.data??[]).map((x)=>({id:x.id,organizationId:x.organization_id,type:x.type,customerAccountId:optional(x.customer_account_id),contractId:optional(x.contract_id),customerServiceId:optional(x.customer_service_id),supplierName:optional(x.supplier_name),description:x.description,amount:x.amount,categoryId:optional(x.category_id),costCenterId:optional(x.cost_center_id),frequency:x.frequency,intervalCount:x.interval_count,startDate:x.start_date,endDate:optional(x.end_date),dueDay:x.due_day,isActive:x.is_active,nextGenerationDate:x.next_generation_date,createdAt:x.created_at,updatedAt:x.updated_at,cancelledAt:optional(x.cancelled_at)}))};},
 async createAccount(input){const result=await api().from("financial_accounts").insert({organization_id:await org(),name:input.name,type:input.type,bank_name:input.bankName,initial_balance:input.initialBalance,is_active:true}).select("*").single();fail(result.error);const x=result.data!;return{id:x.id,organizationId:x.organization_id,name:x.name,type:x.type,bankName:optional(x.bank_name),initialBalance:x.initial_balance,isActive:x.is_active,createdAt:x.created_at,updatedAt:x.updated_at};},
 async createCategory(input){const result=await api().from("financial_categories").insert({organization_id:await org(),name:input.name,type:input.type,parent_id:input.parentId,dre_group:input.dreGroup,is_active:true}).select("*").single();fail(result.error);const x=result.data!;return{id:x.id,organizationId:x.organization_id,name:x.name,type:x.type,parentId:optional(x.parent_id),dreGroup:x.dre_group,isActive:x.is_active,createdAt:x.created_at,updatedAt:x.updated_at};},
 async createCostCenter(input){const result=await api().from("cost_centers").insert({organization_id:await org(),name:input.name,description:input.description,is_active:true}).select("*").single();fail(result.error);const x=result.data!;return{id:x.id,organizationId:x.organization_id,name:x.name,description:optional(x.description),isActive:x.is_active,createdAt:x.created_at,updatedAt:x.updated_at};},
 async createReceivable(input){const result=await api().from("receivables").insert({organization_id:await org(),customer_account_id:input.customerAccountId,company_id:input.companyId,contract_id:input.contractId,customer_service_id:input.customerServiceId,source_opportunity_id:input.sourceOpportunityId,description:input.description,category_id:input.categoryId,cost_center_id:input.costCenterId,competence_date:input.competenceDate,due_date:input.dueDate,original_amount:input.originalAmount,discount_amount:input.discountAmount??0,interest_amount:input.interestAmount??0,penalty_amount:input.penaltyAmount??0,payment_method:input.paymentMethod,notes:input.notes,status:"pending"}).select("*").single();fail(result.error);return receivable(result.data!);},
 async createPayable(input){const result=await api().from("payables").insert({organization_id:await org(),supplier_name:input.supplierName,description:input.description,category_id:input.categoryId,cost_center_id:input.costCenterId,competence_date:input.competenceDate,due_date:input.dueDate,original_amount:input.originalAmount,discount_amount:input.discountAmount??0,interest_amount:input.interestAmount??0,penalty_amount:input.penaltyAmount??0,financial_account_id:input.financialAccountId,notes:input.notes,status:"pending"}).select("*").single();fail(result.error);return payable(result.data!);},
 async receivePayment(input){const result=await api().rpc("register_financial_payment",{entry_kind:"receivable",target_entry_id:input.entryId,target_account_id:input.financialAccountId,payment_amount:input.amount,payment_occurred_at:input.occurredAt,payment_method_value:input.paymentMethod,payment_reference:input.reference,payment_notes:input.notes});fail(result.error);},
 async payExpense(input){const result=await api().rpc("register_financial_payment",{entry_kind:"payable",target_entry_id:input.entryId,target_account_id:input.financialAccountId,payment_amount:input.amount,payment_occurred_at:input.occurredAt,payment_method_value:input.paymentMethod,payment_reference:input.reference,payment_notes:input.notes});fail(result.error);},
 async reverseTransaction(id){const result=await api().rpc("reverse_financial_transaction",{target_transaction_id:id});fail(result.error);},
 async createRecurrence(input){const result=await api().from("recurrence_rules").insert({organization_id:await org(),type:input.type,customer_account_id:input.customerAccountId,contract_id:input.contractId,customer_service_id:input.customerServiceId,supplier_name:input.supplierName,description:input.description,amount:input.amount,category_id:input.categoryId,cost_center_id:input.costCenterId,frequency:input.frequency,interval_count:input.intervalCount,start_date:input.startDate,end_date:input.endDate,due_day:input.dueDay,is_active:input.isActive,next_generation_date:input.nextGenerationDate}).select("*").single();fail(result.error);const data=await this.list();return data.recurrences.find((x)=>x.id===result.data!.id)!;},
 async generateRecurringEntries(ruleId,throughDate){const result=await api().rpc("generate_recurring_entries",{target_rule_id:ruleId,through_date:throughDate});fail(result.error);return result.data??0;},
 async createInstallments(input){const values=splitInstallments(input.originalAmount,input.installments);const output:Receivable[]=[];for(let i=0;i<values.length;i++){const date=new Date(`${input.dueDate}T12:00:00Z`);date.setUTCMonth(date.getUTCMonth()+i);output.push(await this.createReceivable({...input,description:`${input.description} (${i+1}/${values.length})`,originalAmount:values[i],dueDate:date.toISOString().slice(0,10)}));}return output;}
};
