import{describe,expect,test}from"bun:test";import{readFileSync}from"node:fs";
const migration=readFileSync("supabase/migrations/202609030001_provider_neutral_billing_integration.sql","utf8"),provider=readFileSync("supabase/functions/_shared/asaas-provider.ts","utf8"),factory=readFileSync("supabase/functions/_shared/provider-factory.ts","utf8"),create=readFileSync("supabase/functions/create-billing-charge/index.ts","utf8"),webhook=readFileSync("supabase/functions/asaas-webhook/index.ts","utf8");
describe("provider-neutral Asaas Pix integration",()=>{
 test("uses a provider abstraction and configurable sandbox/production URL",()=>{const contract=readFileSync("supabase/functions/_shared/billing-provider.ts","utf8");expect(contract).toContain("interface BillingProvider");for(const method of["createCustomer","createCharge","getCharge","findChargeByExternalReference","getPix","cancelCharge"])expect(contract).toContain(method);expect(factory).toContain('Deno.env.get("ASAAS_BASE_URL")');expect(factory).toContain('Deno.env.get("PAYMENT_PROVIDER")');expect(provider).not.toContain("api.asaas.com");});
 test("uses documented customer, payment and Pix resource paths",()=>{expect(provider).toContain('"/customers"');expect(provider).toContain('"/payments"');expect(provider).toContain('/pixQrCode');expect(provider).toContain('"access_token"');expect(provider).toContain('billingType:"PIX"');});
 test("never exposes Asaas or service credentials to frontend",()=>{for(const file of[factory,provider,create,webhook])expect(file).not.toContain("VITE_ASAAS");for(const path of["src/modules/platform/PlatformPage.tsx","src/modules/platform/repository.ts","src/modules/subscription/SubscriptionContactPage.tsx"])expect(readFileSync(path,"utf8")).not.toContain("ASAAS_API_KEY");});
 test("Legacy and free subscriptions cannot create external customers or charges",()=>{expect(migration).toContain("p.slug='legacy'or s.price_cents=0");expect(migration).toContain("free_plan_not_billable");expect(create).toContain("platform_prepare_billing_charge");});
 test("charge value and due date come from current subscription",()=>{expect(migration).toContain("'amountCents',s.price_cents");expect(migration).toContain("'dueDate',s.next_due_at::date");expect(provider).toContain("value:input.amountCents/100");expect(provider).toContain("dueDate:input.dueDate");});
 test("charge creation is idempotent and provider failures preserve organization",()=>{expect(migration).toContain("unique(provider,idempotency_key)");expect(migration).toContain("unique(provider,external_payment_id)");expect(migration).toContain("request_token uuid");expect(create).toContain("A organização foi preservada");expect(create).toContain("findChargeByExternalReference");expect(create).toContain("platform_record_external_customer");expect(create).not.toMatch(/deleteUser|delete.*organization/i);});
 test("webhook authenticates before parsing and accepts official payment events",()=>{expect(webhook).toContain('request.headers.get("asaas-access-token")');expect(webhook.indexOf("invalid_webhook_token")).toBeLessThan(webhook.indexOf("request.json()"));for(const event of["PAYMENT_CREATED","PAYMENT_RECEIVED","PAYMENT_CONFIRMED","PAYMENT_OVERDUE","PAYMENT_REFUNDED","PAYMENT_DELETED"])expect(webhook).toContain(event);});
 test("duplicate webhooks and payments are idempotent",()=>{expect(migration).toContain("unique(provider,external_event_id)");expect(migration).toContain("subscription_payments_provider_payment_unique");expect(migration).toContain("on conflict(provider,external_payment_id)");expect(migration).toContain("if payment_id is null then");expect(migration).toContain("if e.processing_status='processed'");});
 test("confirmed payment validates amount and activates only non-cancelled subscription",()=>{expect(migration).toContain("confirmed_amount_cents<>s.price_cents");expect(migration).toContain("payment_amount_mismatch");expect(migration).toContain("if s.status<>'cancelled'");expect(migration).toContain("status='active',last_payment_at");expect(migration).toContain("insert into public.subscription_payments");});
 test("past due, refund and deletion map to internal states",()=>{expect(migration).toContain("target_event_type='PAYMENT_OVERDUE'");expect(migration).toContain("status='past_due'");expect(migration).toContain("target_event_type='PAYMENT_REFUNDED'");expect(migration).toContain("target_event_type in('PAYMENT_DELETED')");});
 test("tenant can read only its own charge and cannot mutate billing",()=>{expect(migration).toContain("billing_charges_tenant_read");expect(migration).toContain("organization_id=public.current_organization_id()");expect(migration).not.toMatch(/create policy .*billing_charges.* for (all|insert|update|delete)/i);expect(migration).toContain("current_billing_snapshot");});
 test("Pix is provider-generated and card secrets are never stored",()=>{expect(provider).toContain("getPix");expect(create).toContain("pix.encodedImage");expect(migration).toContain("pix_payload text,pix_qr_code text");expect(migration).not.toMatch(/\b(cvv|card_number|pan)\b/i);});
 test("manual and gateway confirmation share payment domain logic",()=>{expect(migration).toContain("apply_confirmed_subscription_payment");expect(migration.match(/perform public\.apply_confirmed_subscription_payment/g)?.length).toBe(2);expect(migration).toContain("platform_mark_subscription_paid");});
 test("failed provider events remain retryable with sanitized payload",()=>{expect(migration).toContain("processing_status='failed'");expect(migration).toContain("sanitized_payload");expect(webhook).toContain("safe_payload");expect(webhook).not.toContain("provider_payload");});
});
