import {describe,expect,test}from"bun:test";
import{readFileSync}from"node:fs";
const migration=readFileSync("supabase/migrations/202609020001_allow_cancelled_subscription_reactivation.sql","utf8");
describe("cancelled subscription reactivation",()=>{
 test("only Platform Admin can reactivate supported statuses",()=>{expect(migration).toContain("if not public.is_platform_admin()then raise exception 'platform_admin_required'");expect(migration).toContain("status not in('suspended','past_due','pending','cancelled')");expect(migration).toContain("grant execute on function public.platform_reactivate_subscription(uuid)to authenticated");});
 test("prevents two current subscriptions for one organization",()=>{expect(migration).toContain("current.organization_id=subscription.organization_id");expect(migration).toContain("current.id<>subscription.id");expect(migration).toContain("current.status<>'cancelled'");expect(migration).toContain("organization_already_has_current_subscription");});
 test("cancelled opens a new calendar cycle while preserving original start",()=>{expect(migration).toContain("cycle_start timestamptz:=now()");expect(migration).toContain("cycle_end:=cycle_start+make_interval(months=>subscription.billing_interval_months)");expect(migration).toContain("current_period_start=cycle_start,current_period_end=cycle_end,next_due_at=cycle_end");expect(migration).toContain("grace_period_ends_at=cycle_end+make_interval(days=>subscription.grace_period_days)");expect(migration).not.toContain("started_at=");});
 test("clears cancellation and suspension without inventing payment",()=>{expect(migration).toContain("status='active',cancelled_at=null,suspended_at=null");expect(migration).not.toContain("last_payment_at=");expect(migration).not.toContain("insert into public.subscription_payments");});
 test("does not mutate organization, plan, history, CRM or identity",()=>{expect(migration).not.toMatch(/(update|delete from) public\.(organizations|plans|subscription_payments|companies|opportunities|profiles|organization_members)/i);expect(migration).not.toContain("plan_id=");expect(migration).not.toContain("price_cents=");expect(migration).not.toContain("currency=");});
 test("suspended, past due and pending retain the existing reactivation behavior",()=>{expect(migration).toContain("else\n  update public.organization_subscriptions set status='active',suspended_at=null");expect(migration).toContain("greatest(next_due_at,now()+interval'1 day')");});
 test("UI confirms cancelled reactivation and keeps payment disabled",()=>{const page=readFileSync("src/modules/platform/PlatformPage.tsx","utf8");expect(page).toContain('selected.subscription.status==="cancelled"?"Reativar assinatura":"Reativar"');expect(page).toContain('title="Reativar esta assinatura?"');expect(page).toContain("Um novo ciclo será iniciado a partir de hoje. O histórico anterior será preservado.");expect(page).toContain('disabled={Boolean(saving)||selected.subscription.status==="cancelled"}');});
 test("existing snapshot and access guard reflect active immediately",()=>{const billing=readFileSync("supabase/migrations/202608310001_organization_subscriptions_billing.sql","utf8"),access=readFileSync("supabase/migrations/202609010001_subscription_access_control.sql","utf8"),hook=readFileSync("src/modules/subscription/hooks.ts","utf8");expect(billing).toContain("candidate.status<>'cancelled'");expect(access).toContain("public.subscription_effective_status");expect(hook).toContain("refetchInterval:30_000");});
 test("Legacy behavior is untouched",()=>{const access=readFileSync("supabase/migrations/202609010001_subscription_access_control.sql","utf8");expect(access).toContain("plan.slug='legacy'and subscription.price_cents=0 then 'active'");expect(migration).not.toContain("legacy");});
});
