import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { normalizeBrazilianWhatsapp, parseCsv, validateLeadRows } from "../src/modules/crm/lead-spreadsheet";
import type { CompanyContact, Profile } from "../src/modules/crm/types";

const migration=readFileSync("supabase/migrations/202609190001_crm_lead_spreadsheet_import.sql","utf8"),page=readFileSync("src/modules/crm/CrmPage.tsx","utf8"),dialog=readFileSync("src/modules/crm/components/lead-import-dialog.tsx","utf8"),sheet=readFileSync("src/modules/crm/lead-spreadsheet.ts","utf8"),hooks=readFileSync("src/modules/crm/hooks.ts","utf8"),supabaseRepo=readFileSync("src/modules/crm/supabase-repository.ts","utf8");
const profile=(id:string,name:string):Profile=>({id,organizationId:"org-a",name,email:`${id}@example.com`,role:"sales",createdAt:"",updatedAt:""});
const contact=(whatsapp:string):CompanyContact=>({id:whatsapp,organizationId:"org-a",companyId:"company",name:"Lead",whatsapp,isPrimary:true,isFinancial:false,isCommercial:true,status:"ativo",createdAt:"",updatedAt:""});

describe("CRM lead spreadsheet import and export",()=>{
  test("normalizes Brazilian country code and the legacy missing ninth digit",()=>{expect(normalizeBrazilianWhatsapp("+55 75 99999-9999")).toBe("75999999999");expect(normalizeBrazilianWhatsapp("5575999999999")).toBe("75999999999");expect(normalizeBrazilianWhatsapp("75 9999-9999")).toBe("75999999999");expect(normalizeBrazilianWhatsapp("123")).toBeUndefined()});
  test("parses semicolon and comma CSV with the documented columns",()=>{const semicolon=parseCsv("Nome;WhatsApp;Instagram;Observação;Origem;Responsável\nMaria;75999999999;@maria;Nota;Indicação;Elielson");expect(semicolon[0]).toMatchObject({row:2,name:"Maria",whatsapp:"75999999999",instagram:"@maria",note:"Nota",source:"Indicação",ownerName:"Elielson"});expect(parseCsv("Nome,WhatsApp\nAna,75988888888")[0].name).toBe("Ana")});
  test("validates all rows in memory against tenant contacts and profiles",()=>{const rows=parseCsv("Nome;WhatsApp;Responsável\nNovo;75911111111; elielson \nDuplicado;+55 75 99999-9999;\nSem nome;123;\n;75922222222;\nSem dono;75933333333;Inexistente\nRepetido;75911111111;Elielson");const result=validateLeadRows(rows,[contact("75999999999")],[profile("user-a","ELIELSON")]);expect(result.map(row=>row.status)).toEqual(["new","duplicate","invalid_phone","missing_name","owner_not_found","duplicate_file"]);expect(result[0].ownerId).toBe("user-a")});
  test("offers responsive preview, template, status summary and confirmation",()=>{for(const text of["Importar leads","Exportar","LeadImportDialog"])expect(page).toContain(text);for(const text of["Baixar modelo de planilha","Status da linha","Já existe","WhatsApp inválido","Responsável não encontrado","Importação concluída"])expect(dialog).toContain(text);expect(dialog).toContain('accept=".xlsx,.csv');expect(sheet).toContain("downloadLeadTemplate");expect(sheet).toContain("exportLeadsCsv")});
  test("imports once and refreshes CRM only after the batch",()=>{expect(supabaseRepo).toContain('rpc("import_crm_leads"');expect(hooks).toContain("mutationFn: (rows:LeadImportInput[])");expect(hooks).toContain("await refresh()");expect(dialog).not.toContain("createCompany")});
  test("backend derives tenant and actor, validates owners and reuses manual creation",()=>{expect(migration).toContain("tenant uuid:=public.current_organization_id()");expect(migration).toContain("actor uuid:=auth.uid()");expect(migration).toContain("public.has_permission('crm.manage')");expect(migration).toContain("p.organization_id=tenant");expect(migration).toContain("from public.contacts c");expect(migration).toContain("from public.companies c");expect(migration).toContain("pg_advisory_xact_lock");expect(migration).toContain("public.create_company_with_primary_contact");expect(migration).toContain("insert into public.notes");expect(migration).not.toMatch(/service_role/i)});
  test("uses the stable initial-stage lookup in the existing manual RPC",()=>{const manual=readFileSync("supabase/migrations/202608270004_crm_tenant_performance_fix.sql","utf8");expect(manual).toContain("slug='novo_lead'");expect(manual).toContain("is_default=true");expect(manual).toContain("status,created_by")});
});
