import{describe,expect,test}from"bun:test";import{readFileSync}from"node:fs";import{calculateDiagnosticResult}from"../src/modules/diagnostic/scoring";import{diagnosticQuestions}from"../src/modules/diagnostic/questions";import type{AnswerKey,DiagnosticAnswers,DiagnosticSubmission}from"../src/modules/diagnostic/types";import{diagnosticLeadSchema}from"../src/modules/diagnostic/schema";import{createDiagnosticPdf}from"../src/modules/diagnostic/pdf/generate-diagnostic-pdf";
const answer=(value:AnswerKey)=>Object.fromEntries(diagnosticQuestions.map(question=>[question.key,value]))as DiagnosticAnswers;
describe("diagnóstico público do negócio",()=>{
 test("possui dez perguntas em linguagem pública e uma necessidade separada",()=>{expect(diagnosticQuestions).toHaveLength(10);expect(diagnosticQuestions.at(-1)?.category).toBe("primary_need")});
 test("normaliza os extremos sem usar a necessidade como maturidade",()=>{expect(calculateDiagnosticResult(answer("a")).totalScore).toBe(0);expect(calculateDiagnosticResult(answer("d")).totalScore).toBe(100);const values=answer("b");values.primary_need="d";expect(calculateDiagnosticResult(values).totalScore).toBe(33)});
 test("classifica faixas intermediárias e categorias",()=>{const result=calculateDiagnosticResult(answer("c"));expect(result.level).toBe("Negócio em desenvolvimento");expect(Object.keys(result.categoryScores)).toHaveLength(8);expect(result.recommendations).toHaveLength(3)});
 test("desempata pela ordem editorial documentada",()=>{const result=calculateDiagnosticResult(answer("b"));expect(result.primaryBottleneck).toBe("acquisition");expect(result.strongestArea).toBe("financial_clarity")});
 test("recusa respostas ausentes",()=>expect(()=>calculateDiagnosticResult({})).toThrow("Responda todas"));

 test("gera PDF premium de oito páginas a partir do resultado",()=>{const answers=answer("c"),result=calculateDiagnosticResult(answers),submission={token:"test",lead:{name:"Maria Silva",whatsapp:"5511999999999",instagram:"maria.studio"},answers,result,createdAt:new Date().toISOString()}satisfies DiagnosticSubmission;const pdf=createDiagnosticPdf(submission);expect(new TextDecoder().decode(pdf.slice(0,8))).toStartWith("%PDF-1.4");expect(pdf.length).toBeGreaterThan(5000)});
 test("rota é pública e RPC não expõe leitura das tabelas",()=>{const main=readFileSync("src/main.tsx","utf8"),root=readFileSync("src/app/public-app-root.tsx","utf8"),sql=readFileSync("supabase/migrations/202608210001_public_business_diagnostic.sql","utf8");expect(main).toContain("blog|diagnostico");expect(root).toContain('path="/diagnostico"');expect(sql).toContain("enable row level security");expect(sql).toContain("submit_public_diagnostic");expect(sql).toContain("revoke all on function public.submit_public_diagnostic");expect(sql).not.toMatch(/grant\s+(select|update|delete).*diagnostic_/i)});
 test("recalcula score no banco e reutiliza criação atômica do lead",()=>{const sql=readFileSync("supabase/migrations/202608210001_public_business_diagnostic.sql","utf8");expect(sql).toContain("create_company_lead");expect(sql).toContain("category_scores");expect(sql).toContain("idempotency_key");expect(sql).toContain("rate_limited")});
 test("captura exige somente nome, WhatsApp e Instagram normalizados",()=>{const parsed=diagnosticLeadSchema.parse({name:"  Maria Silva ",whatsapp:"(11) 99999-9999",instagram:"@Maria.Studio"});expect(parsed).toEqual({name:"Maria Silva",whatsapp:"+5511999999999",instagram:"maria.studio"});expect(diagnosticLeadSchema.safeParse({name:"",whatsapp:"1",instagram:"@"}).success).toBe(false)});
 test("formulário remove campos legados e exibe loading e erros",()=>{const page=readFileSync("src/modules/diagnostic/pages/DiagnosticPage.tsx","utf8");expect(page).not.toContain("Nome do negócio");expect(page).not.toContain("Ainda não tenho um nome definido");expect(page).not.toContain('label="E-mail"');expect(page).toContain('label="Instagram"');expect(page).toContain('type="submit"');expect(page).toContain("Preparando seu diagnóstico...");expect(page).toContain('role="alert"')});
 test("RPC simplificada deriva empresa do nome e reutiliza vínculo CRM",()=>{const sql=readFileSync("supabase/migrations/202608210004_instagram_diagnostic_capture.sql","utf8"),repository=readFileSync("src/modules/diagnostic/supabase-repository.ts","utf8");expect(repository).not.toContain("business_name:");expect(repository).not.toContain("email:input.lead");expect(repository).toContain("instagram:input.lead.instagram");expect(sql).toContain("existing_crm");expect(sql).toContain("create_company_lead");expect(sql).toContain("trim(submission_data->>'name')");expect(sql).toContain("idempotency_key")});
 test("blog conduz ao diagnóstico e quiz avança sem botão Continuar",()=>{const post=readFileSync("src/modules/blog/pages/BlogPostPage.tsx","utf8"),content=readFileSync("src/modules/blog/components/blog-content.tsx","utf8"),page=readFileSync("src/modules/diagnostic/pages/DiagnosticPage.tsx","utf8"),root=readFileSync("src/app/public-app-root.tsx","utf8");expect(post).toContain("BlogDiagnosticCta");expect(content).toContain("diagnostic-middle");expect(content).toContain('"ul"|"ol"');expect(page).toContain("setTimeout");expect(page).not.toContain(">Continuar<");expect(page).toContain("Analisando suas respostas...");expect(root).toContain("/diagnostico/obrigado/:token")});
 test("landing pública possui funil mobile radical sem alterar o desktop",()=>{const page=readFileSync("src/modules/diagnostic/pages/DiagnosticPage.tsx","utf8"),styles=readFileSync("src/styles/globals.css","utf8"),html=readFileSync("index.html","utf8");for(const component of["MobileDiagnosticHero","MobileProofStrip","MobilePainSection","MobileBenefitsSection","MobileHowItWorks","MobileAuthorityBlock","MobileFinalCta","MobileStickyCta","DesktopLanding"])expect(page).toContain(component);expect(page).toContain("md:hidden");expect(page).toContain("hidden md:block");expect(page).toContain('data-landing-variant="mobile-v2"');expect(page).toContain('data-landing-variant="desktop"');expect(page).toContain("Isso parece com você?");expect(page).toContain("Em poucos minutos, você vai descobrir:");expect(page).toContain("Você já sabe que quer crescer");expect(page).toContain("env(safe-area-inset-bottom)");expect(page).toContain("IntersectionObserver");expect(styles).toContain("prefers-reduced-motion");expect(html).toContain('name="viewport" content="width=device-width, initial-scale=1.0"')});
 test("expõe caixa administrativa autenticada e limitada à organização",()=>{const app=readFileSync("src/app/App.tsx","utf8"),admin=readFileSync("supabase/migrations/202608210002_diagnostic_admin_access.sql","utf8");expect(app).toContain('path="marketing/diagnosticos"');expect(admin).toContain("has_permission('marketing.view')");expect(admin).toContain("organization_id = current_profile.organization_id");expect(admin).toContain("grant execute");expect(admin).not.toMatch(/grant\s+select/i)});
});
