import{describe,expect,test}from"bun:test";import{readFileSync}from"node:fs";import{calculateDiagnosticResult}from"../src/modules/diagnostic/scoring";import{diagnosticQuestions}from"../src/modules/diagnostic/questions";import type{AnswerKey,DiagnosticAnswers,DiagnosticSubmission}from"../src/modules/diagnostic/types";import{createDiagnosticPdf}from"../src/modules/diagnostic/pdf/generate-diagnostic-pdf";
const answer=(value:AnswerKey)=>Object.fromEntries(diagnosticQuestions.map(question=>[question.key,value]))as DiagnosticAnswers;
describe("diagnóstico público do negócio",()=>{
 test("possui dez perguntas em linguagem pública e uma necessidade separada",()=>{expect(diagnosticQuestions).toHaveLength(10);expect(diagnosticQuestions.at(-1)?.category).toBe("primary_need")});
 test("normaliza os extremos sem usar a necessidade como maturidade",()=>{expect(calculateDiagnosticResult(answer("a")).totalScore).toBe(0);expect(calculateDiagnosticResult(answer("d")).totalScore).toBe(100);const values=answer("b");values.primary_need="d";expect(calculateDiagnosticResult(values).totalScore).toBe(33)});
 test("classifica faixas intermediárias e categorias",()=>{const result=calculateDiagnosticResult(answer("c"));expect(result.level).toBe("Negócio em desenvolvimento");expect(Object.keys(result.categoryScores)).toHaveLength(8);expect(result.recommendations).toHaveLength(3)});
 test("desempata pela ordem editorial documentada",()=>{const result=calculateDiagnosticResult(answer("b"));expect(result.primaryBottleneck).toBe("acquisition");expect(result.strongestArea).toBe("financial_clarity")});
 test("recusa respostas ausentes",()=>expect(()=>calculateDiagnosticResult({})).toThrow("Responda todas"));

 test("gera PDF real de sete páginas a partir do resultado",()=>{const answers=answer("c"),result=calculateDiagnosticResult(answers),submission={token:"test",lead:{name:"Maria Silva",businessName:"Studio Bella",whatsapp:"5511999999999",email:"maria@example.com",instagram:"maria"},answers,result,createdAt:new Date().toISOString()}satisfies DiagnosticSubmission;const pdf=createDiagnosticPdf(submission);expect(new TextDecoder().decode(pdf.slice(0,8))).toStartWith("%PDF-1.4");expect(pdf.length).toBeGreaterThan(1000)});
 test("rota é pública e RPC não expõe leitura das tabelas",()=>{const main=readFileSync("src/main.tsx","utf8"),root=readFileSync("src/app/public-app-root.tsx","utf8"),sql=readFileSync("supabase/migrations/202608210001_public_business_diagnostic.sql","utf8");expect(main).toContain("blog|diagnostico");expect(root).toContain('path="/diagnostico"');expect(sql).toContain("enable row level security");expect(sql).toContain("submit_public_diagnostic");expect(sql).toContain("revoke all on function public.submit_public_diagnostic");expect(sql).not.toMatch(/grant\s+(select|update|delete).*diagnostic_/i)});
 test("recalcula score no banco e reutiliza criação atômica do lead",()=>{const sql=readFileSync("supabase/migrations/202608210001_public_business_diagnostic.sql","utf8");expect(sql).toContain("create_company_lead");expect(sql).toContain("category_scores");expect(sql).toContain("idempotency_key");expect(sql).toContain("rate_limited")});
 test("expõe caixa administrativa autenticada e limitada à organização",()=>{const app=readFileSync("src/app/App.tsx","utf8"),admin=readFileSync("supabase/migrations/202608210002_diagnostic_admin_access.sql","utf8");expect(app).toContain('path="marketing/diagnosticos"');expect(admin).toContain("has_permission('marketing.view')");expect(admin).toContain("organization_id = current_profile.organization_id");expect(admin).toContain("grant execute");expect(admin).not.toMatch(/grant\s+select/i)});
});
