import {describe,expect,test} from "bun:test";import{readFileSync}from"node:fs";import{accountBalance,cashFlow,derivedStatus,splitInstallments}from"../src/modules/finance/domain";import type{FinanceData,Payable,Receivable}from"../src/modules/finance/types";
const migration=readFileSync("supabase/migrations/202609170001_finance_v1_tenant_hardening.sql","utf8"),repository=readFileSync("src/modules/finance/supabase-repository.ts","utf8"),hooks=readFileSync("src/modules/finance/hooks.ts","utf8"),page=readFileSync("src/modules/finance/FinancePage.tsx","utf8");
const income:Receivable={id:"r",organizationId:"a",description:"Procedimento",competenceDate:"2026-09-01",dueDate:"2026-09-10",originalAmount:300,discountAmount:0,interestAmount:0,penaltyAmount:0,netAmount:300,status:"pending",financialAccountId:"bank",createdAt:"",updatedAt:""};const expense:Payable={id:"p",organizationId:"a",supplierName:"Fornecedor",description:"Insumos",competenceDate:"2026-09-01",dueDate:"2026-09-12",originalAmount:100,discountAmount:0,interestAmount:0,penaltyAmount:0,netAmount:100,status:"pending",financialAccountId:"bank",createdAt:"",updatedAt:""};const data:FinanceData={accounts:[{id:"bank",organizationId:"a",name:"Banco",type:"checking",initialBalance:1000,isActive:true,createdAt:"",updatedAt:""}],categories:[],costCenters:[],receivables:[income],payables:[expense],transactions:[{id:"in",organizationId:"a",financialAccountId:"bank",type:"income",amount:500,occurredAt:"2026-09-05T12:00:00Z",description:"Recebido",createdBy:"u",createdAt:""},{id:"out",organizationId:"a",financialAccountId:"bank",type:"expense",amount:200,occurredAt:"2026-09-06T12:00:00Z",description:"Pago",createdBy:"u",createdAt:""}],allocations:[],recurrences:[],companies:[],opportunities:[]};
describe("finance 1.0",()=>{
 test("keeps every read and write tenant scoped with existing RLS permissions",()=>{for(const table of ["financial_accounts","financial_categories","receivables","payables","financial_transactions","payment_allocations","recurrence_rules"])expect(repository).toContain(`.from("${table}")`);expect(repository.match(/\.eq\("organization_id",organizationId\)/g)?.length).toBeGreaterThan(10);expect(migration).toContain("new.organization_id<>public.current_organization_id()");for(const guard of ["cross_tenant_account","cross_tenant_category","cross_tenant_company","cross_tenant_opportunity","cross_tenant_transaction","cross_tenant_financial_entry"])expect(migration).toContain(guard);expect(migration).toContain("finance.view','finance.manage','finance.transactions.reverse");expect(migration).not.toMatch(/service_role|disable row level security/i)});
 test("uses tenant-aware cache keys so Platform Admin switches cannot leak data",()=>{expect(hooks).toContain("financeKeys.all(organizationId)");expect(hooks).toContain("enabled:Boolean(organizationId)")});
 test("calculates settled account balance without storing aggregates",()=>expect(accountBalance("bank",data)).toBe(1300));
 test("derives overdue status from due date without cron",()=>expect(derivedStatus(income,"receivable",data,"2026-09-11")).toBe("overdue"));
 test("builds actual and forecast cash flow chronologically",()=>{const actual=cashFlow(data,"actual","2026-09-01","2026-09-30");expect(actual.map(x=>x.balance)).toEqual([1500,1300]);const forecast=cashFlow(data,"forecast","2026-09-01","2026-09-30");expect(forecast.map(x=>x.balance)).toEqual([1600,1500])});
 test("splits cents predictably and persists installment groups for income and expense",()=>{expect(splitInstallments(3000,3)).toEqual([1000,1000,1000]);expect(migration).toContain("installment_group_id");expect(repository).toContain("createPayableInstallments")});
 test("supports edit, cancel, settle, reopen, duplicate and monthly recurrence",()=>{for(const label of ["Editar","Duplicar","Cancelar","Reabrir","Marcar como recebido","Marcar como pago","Repetir mensalmente por 12 meses"])expect(page).toContain(label);expect(migration).toContain("amount_below_settled_total")});
 test("provides the six required areas and lightweight CRM links",()=>{for(const label of ["Visão Geral","Contas a Receber","Contas a Pagar","Fluxo de Caixa","Contas Bancárias","Categorias"])expect(page).toContain(label);expect(repository).toContain('.from("companies")');expect(repository).toContain('.from("opportunities")')});
 test("seeds safe defaults without deleting existing categories",()=>{for(const name of ["Procedimentos","Consultas","Pacotes","Aluguel","Funcionários","Tráfego pago","Impostos","Software","Energia"])expect(migration).toContain(name);expect(migration).toContain("on conflict(organization_id,type,name) do nothing");expect(migration).not.toMatch(/delete from|drop table/i)});
});
