import {describe,expect,test} from "bun:test";import {agingBucket,calculateMrr,dashboard,derivedStatus,dre,entryBalance,netAmount,splitInstallments} from "../src/modules/finance/domain";import type {FinanceData,Receivable} from "../src/modules/finance/types";
const receivable:Receivable={id:"r",organizationId:"o",description:"Mensalidade",competenceDate:"2026-08-01",dueDate:"2026-08-10",originalAmount:2000,discountAmount:0,interestAmount:0,penaltyAmount:0,netAmount:2000,status:"pending",categoryId:"income",createdAt:"2026-08-01T00:00:00Z",updatedAt:"2026-08-01T00:00:00Z"};
const data:FinanceData={accounts:[{id:"bank",organizationId:"o",name:"Banco",type:"bank",initialBalance:100,isActive:true,createdAt:"",updatedAt:""}],categories:[{id:"income",organizationId:"o",name:"Receita",type:"income",dreGroup:"gross_revenue",isActive:true,createdAt:"",updatedAt:""},{id:"cost",organizationId:"o",name:"Custo",type:"expense",dreGroup:"direct_cost",isActive:true,createdAt:"",updatedAt:""}],costCenters:[],receivables:[receivable],payables:[],transactions:[],allocations:[],recurrences:[]};
describe("finance domain",()=>{
 test("centralizes net amount",()=>expect(netAmount({originalAmount:1000,discountAmount:100,interestAmount:20,penaltyAmount:10})).toBe(930));
 test("supports zero and a full discount without negative value",()=>expect(netAmount({originalAmount:1000,discountAmount:1000})).toBe(0));
 test("supports partial and multiple payments",()=>{const partial={...data,transactions:[{id:"t1",organizationId:"o",financialAccountId:"bank",type:"income" as const,amount:1000,occurredAt:"2026-08-11T00:00:00Z",description:"p",createdBy:"u",createdAt:""},{id:"t2",organizationId:"o",financialAccountId:"bank",type:"income" as const,amount:500,occurredAt:"2026-08-12T00:00:00Z",description:"p",createdBy:"u",createdAt:""}],allocations:[{id:"a1",organizationId:"o",transactionId:"t1",receivableId:"r",amount:1000,createdAt:""},{id:"a2",organizationId:"o",transactionId:"t2",receivableId:"r",amount:500,createdAt:""}]};expect(entryBalance(receivable,"receivable",partial)).toBe(500);expect(derivedStatus(receivable,"receivable",partial,"2026-08-15")).toBe("partially_paid");});
 test("reversal restores balance",()=>{const reversed={...data,transactions:[{id:"t",organizationId:"o",financialAccountId:"bank",type:"income" as const,amount:2000,occurredAt:"2026-08-11T00:00:00Z",description:"p",createdBy:"u",createdAt:"",reversedAt:"2026-08-12T00:00:00Z"}],allocations:[{id:"a",organizationId:"o",transactionId:"t",receivableId:"r",amount:2000,createdAt:""}]};expect(entryBalance(receivable,"receivable",reversed)).toBe(2000);});
 test("splits installments without losing cents",()=>expect(splitInstallments(1000,3)).toEqual([333.33,333.33,333.34]));
 test("derives delinquency and aging",()=>{expect(derivedStatus(receivable,"receivable",data,"2026-08-11")).toBe("overdue");expect(agingBucket(95)).toBe("90+ dias");});
 test("cash dashboard uses transactions, not won opportunities",()=>expect(dashboard(data,"2026-08-01","2026-08-31").received).toBe(0));
 test("transfers do not affect managerial result",()=>{const transfer={...data,transactions:[{id:"tr",organizationId:"o",financialAccountId:"bank",type:"transfer" as const,amount:500,occurredAt:"2026-08-10T00:00:00Z",description:"Transferência",createdBy:"u",createdAt:""}]};expect(dashboard(transfer,"2026-08-01","2026-08-31").result).toBe(0);});
 test("DRE uses competence and handles zero margin divisor",()=>{const report=dre({...data,receivables:[],payables:[]},"2026-08-01","2026-08-31");expect(report.grossMarginPercent).toBe(0);});
 test("MRR excludes one-time by relying on real recurrence rules",()=>expect(calculateMrr([{id:"x",organizationId:"o",type:"receivable",description:"Anual",amount:12000,frequency:"yearly",intervalCount:1,startDate:"2026-01-01",dueDay:1,isActive:true,nextGenerationDate:"2026-01-01",createdAt:"",updatedAt:""}])).toBe(1000));
});
