import{describe,expect,test}from"bun:test";import{readFileSync}from"node:fs";import{captureReferralCode}from"../src/modules/sales/tracking";
const sql=readFileSync("supabase/migrations/202609180001_referral_program_v1.sql","utf8"),repo=readFileSync("src/modules/referrals/repository.ts","utf8"),hooks=readFileSync("src/modules/referrals/hooks.ts","utf8"),page=readFileSync("src/modules/referrals/ReferralPage.tsx","utf8"),sales=readFileSync("src/modules/sales/repository.ts","utf8"),main=readFileSync("src/main.tsx","utf8");
describe("Indique e Ganhe 1.0",()=>{
 test("uses unique non-sequential codes without exposing organization UUID",()=>{expect(sql).toContain("unique(code)");expect(sql).toContain("generate_referral_code");expect(sql).toContain("ABCDEFGHJKLMNPQRSTUVWXYZ23456789");expect(sql).toContain("/?ref=")});
 test("captures and persists only the referral code without PII",()=>{const store=new Map<string,string>();Object.assign(globalThis,{location:{search:"?ref=ab7k9x"},sessionStorage:{getItem:(k:string)=>store.get(k)??null,setItem:(k:string,v:string)=>store.set(k,v)}});expect(captureReferralCode()).toBe("AB7K9X");expect(store.get("esads-referral-code")).toBe("AB7K9X");expect(sales).toContain("validate_referral_code")});
 test("associates a submitted public lead idempotently with first valid referral",()=>{expect(sql).toContain("referral_code_id");expect(sql).toContain("referral_first_valid_lead_idx");expect(sql).toContain("on conflict do nothing");expect(sales).toContain("referral_code:referralCode")});
 test("stores structured 99 to 59 campaign and applies it once",()=>{expect(sql).toContain("base_price_cents");expect(sql).toContain("first_payment_cents");expect(sql).toContain("9900,5900,3");expect(sql).toContain("applied_payment_id uuid unique")});
 test("rewards only paid customers and caps three open credits under a lock",()=>{expect(sql).toContain("subscription_payments where organization_id=referred_organization_id and status='paid'");expect(sql).toContain("open_count>=c.max_open_credits");expect(sql).toContain("pg_advisory_xact_lock");expect(sql).toContain("unique(referral_id)");expect(sql).toContain("fill_referral_credit_capacity(s.organization_id)")});
 test("consumes monthly credit idempotently without cash or residual",()=>{expect(sql).toContain("least(coalesce(credit.amount_cents,0)");expect(sql).toContain("greatest(0,s.price_cents-promo-credit_value)");expect(sql).toContain("unique(payment_id)");expect(sql).not.toMatch(/withdraw|payout|cashout/i)});
 test("blocks self referral and duplicate attributed organizations",()=>{expect(sql).toContain("self_referral");expect(sql).toContain("referred_organization_id<>referrer_organization_id");expect(sql).toContain("referral_first_valid_organization_idx")});
 test("RLS is tenant-scoped and platform mutations are backend guarded",()=>{expect(sql.match(/enable row level security/g)?.length).toBe(5);expect(sql).toContain("referrer_organization_id=public.current_organization_id()");expect(sql).toContain("if not public.is_platform_admin()");expect(repo).not.toContain("service_role")});
 test("React Query cache is tenant-aware and platform switching cannot reuse tenant data",()=>{expect(hooks).toContain('["referrals",organizationId,"dashboard"]');expect(hooks).toContain("enabled:Boolean(organizationId)")});
 test("provides public root landing, WhatsApp sharing and discreet valid-ref offer",()=>{expect(main).toContain("isReferralLanding");expect(page).toContain("wa.me/?text=");expect(page).toContain("encodeURIComponent");expect(page).toContain("R$ 59")});
});
