import { describe,expect,test } from "bun:test";
import { readFileSync } from "node:fs";

const migration=readFileSync("supabase/migrations/202609010001_subscription_access_control.sql","utf8");
const guard=readFileSync("src/routes/tenant-subscription-route.tsx","utf8");
const app=readFileSync("src/app/App.tsx","utf8");

describe("controlled subscription access",()=>{
 test("uses backend effective status for the current tenant only",()=>{expect(migration).toContain("tenant uuid:=public.current_organization_id()");expect(migration).toContain("public.subscription_effective_status");expect(migration).not.toContain("target_organization_id");expect(migration).toContain("where s.organization_id=tenant");});
 test("active, pending and past_due remain operational",()=>{expect(migration).toContain("effective_status in('suspended','cancelled')");expect(guard).toContain("access.data?.isBlocked");expect(guard).not.toMatch(/past_due.*Navigate/s);});
 test("suspended and cancelled are centrally blocked without redirect loop",()=>{expect(migration).toContain("'isBlocked',effective_status in('suspended','cancelled')");expect(app).toContain('path="assinatura-suspensa"');expect(app.indexOf('path="assinatura-suspensa"')).toBeLessThan(app.indexOf("<TenantSubscriptionRoute"));expect(guard).toContain('to="/assinatura-suspensa"');});
 test("Platform Admin bypass is based on backend identity",()=>{expect(migration).toContain("if public.is_platform_admin()then");expect(migration).toContain("'isPlatformAdmin',true");expect(guard).toContain("if(isPlatformAdmin)return <Outlet/>");});
 test("Legacy free plan never ages into delinquency",()=>{expect(migration).toContain("plan.slug='legacy'and subscription.price_cents=0 then 'active'");});
 test("past_due banner is global and non-blocking",()=>{const layout=readFileSync("src/layouts/app-layout.tsx","utf8"),banner=readFileSync("src/modules/subscription/SubscriptionPastDueBanner.tsx","utf8");expect(layout).toContain("<SubscriptionPastDueBanner/>");expect(banner).toContain('access.data?.status!=="past_due"');expect(banner).toContain("Regularizar assinatura");});
 test("onboarding and modules are behind subscription guard",()=>{expect(app.indexOf('path="onboarding"')).toBeGreaterThan(app.indexOf("<TenantSubscriptionRoute"));expect(app.indexOf('path="onboarding"')).toBeLessThan(app.indexOf("</Route>\n          <Route path=\"plataforma\""));expect(app).toContain('permission="crm.view"');expect(app).toContain('permission="settings.manage"');});
 test("placeholder operational routes are also guarded",()=>{expect(app.indexOf('{["ia"].map')).toBeGreaterThan(app.indexOf("<TenantSubscriptionRoute"));expect(app.indexOf('{["ia"].map')).toBeLessThan(app.indexOf("</Route>\n          <Route path=\"plataforma\""));});
 test("auth and invitation routes remain outside the guard",()=>{for(const route of ['/login','/register','/aceitar-convite','/finalizar-configuracao'])expect(app.indexOf(route)).toBeLessThan(app.indexOf("<TenantSubscriptionRoute"));});
 test("status is never sourced from browser storage",()=>{for(const file of [migration,guard,readFileSync("src/modules/subscription/repository.ts","utf8")]){expect(file).not.toContain("localStorage");expect(file).not.toContain("sessionStorage");}expect(readFileSync("src/modules/subscription/repository.ts","utf8")).toContain('rpc("current_subscription_access")');});
 test("blocking does not mutate or delete tenant data",()=>{expect(migration).not.toMatch(/(update|delete from) public\.(organizations|profiles|companies|opportunities|organization_members)/i);const billing=readFileSync("supabase/migrations/202608310001_organization_subscriptions_billing.sql","utf8");expect(billing).not.toMatch(/delete from public\.(organizations|profiles|companies|opportunities|organization_members)/i);});
 test("tenant cannot self-reactivate and financial RPCs still require Platform Admin",()=>{expect(migration).not.toContain("update public.organization_subscriptions");const billing=readFileSync("supabase/migrations/202608310001_organization_subscriptions_billing.sql","utf8");expect(billing).toContain("platform_reactivate_subscription");expect(billing).toContain("if not public.is_platform_admin()");});
 test("cancelled remains blocked until the explicit Platform Admin reactivation",()=>{const reactivation=readFileSync("supabase/migrations/202609020001_allow_cancelled_subscription_reactivation.sql","utf8");expect(reactivation).toContain("status not in('suspended','past_due','pending','cancelled')");expect(reactivation).toContain("if not public.is_platform_admin()");});
});
