import{describe,expect,test}from"bun:test";import{readFileSync}from"node:fs";
const edge=readFileSync("supabase/functions/whatsapp-send-message/index.ts","utf8"),config=readFileSync("supabase/config.toml","utf8"),repo=readFileSync("src/modules/whatsapp/repository.ts","utf8"),hooks=readFileSync("src/modules/whatsapp/hooks/use-whatsapp-inbox.ts","utf8"),chat=readFileSync("src/modules/whatsapp/components/chat-panel.tsx","utf8"),page=readFileSync("src/modules/whatsapp/pages/WhatsAppInboxPage.tsx","utf8");
describe("WhatsApp Inbox v2 outbound text",()=>{
 test("requires JWT and authenticates before creating an admin client",()=>{expect(config).toContain('[functions.whatsapp-send-message]\nverify_jwt = true');expect(edge).toContain('request.headers.get("authorization")');expect(edge).toContain("userClient.auth.getUser()");expect(edge.indexOf("auth.getUser()")).toBeLessThan(edge.indexOf("const admin = createClient"))});
 test("derives active tenant authorization rather than trusting payload organization",()=>{expect(edge).toContain('rpc("current_authorization")');expect(edge).toContain('context.organization_id === organizationId');expect(edge).toContain('context?.status === "active"');for(const role of["owner","admin","manager","sales","operations","marketing"])expect(edge).toContain(`"${role}"`);expect(edge).not.toMatch(/allowedRoles[^\n]+financial|allowedRoles[^\n]+reader/)});
 test("validates conversation and active connection in the same tenant",()=>{expect(edge).toContain('from("whatsapp_conversations")');expect(edge).toContain('.eq("organization_id", organizationId)');expect(edge).toContain('from("whatsapp_connections")');expect(edge).toContain('.eq("id", conversation.connection_id)');expect(edge).toContain('.eq("status", "active")')});
 test("rejects missing conversation and empty or oversized text",()=>{expect(edge).toContain("!organizationId || !conversationId || !text");expect(edge).toContain("text.length > maxTextLength");expect(edge).toContain('reply(422, "invalid_message"');expect(edge).toContain('reply(404, "conversation_not_found"')});
 test("calls Cloud API only in Edge Function with the official text payload",()=>{expect(edge).toContain("https://graph.facebook.com/v26.0/");for(const fragment of['messaging_product: "whatsapp"','recipient_type: "individual"','type: "text"','preview_url: false'])expect(edge).toContain(fragment);expect(repo).not.toContain("graph.facebook.com");expect(page).not.toContain("graph.facebook.com")});
 test("keeps all credentials server-side and does not log them",()=>{expect(edge).toContain('Deno.env.get("WHATSAPP_ACCESS_TOKEN")');expect(edge).toContain('Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")');expect(repo).not.toMatch(/WHATSAPP_ACCESS_TOKEN|SERVICE_ROLE|Bearer/);expect(edge).not.toMatch(/console\.(log|error)\([^\n]*(accessToken|serviceRoleKey)/)});
 test("persists confirmed outbound message and updates only matching conversation",()=>{expect(edge).toContain('direction: "outbound"');expect(edge).toContain('external_message_id: externalMessageId');expect(edge).toContain('raw_payload: { messages: [{ id: externalMessageId }] }');expect(edge).toContain('.eq("connection_id", connection.id)');expect(edge).toContain('saved.error.code !== "23505"')});
 test("maps provider and expired 24-hour window errors safely",()=>{expect(edge).toContain("customer_care_window_expired");expect(edge).toContain("janela de atendimento expirou");expect(edge).toContain('reply(502, "provider_rejected"');expect(edge).not.toContain("providerPayload.error?.message")});
 test("frontend invokes only the Edge Function and refreshes tenant-aware queries",()=>{expect(repo).toContain('functions.invoke("whatsapp-send-message"');expect(hooks).toContain("useMutation");expect(hooks).toContain("whatsappKeys.inbox(organizationId)");expect(hooks).toContain("whatsappKeys.messages(organizationId,conversationId)")});
 test("composer supports Enter, Shift+Enter, loading and empty validation",()=>{expect(chat).toContain('event.key==="Enter"');expect(chat).toContain("!event.shiftKey");expect(chat).toContain("event.preventDefault()");expect(chat).toContain("LoaderCircle");expect(chat).toContain("!draft.trim()");expect(chat).toContain("maxLength={4096}")});
 test("clears only after success and preserves draft on error",()=>{expect(chat).toContain('await onSend(text); setDraft("")');expect(chat).toContain("catch (reason) { setError");expect(chat).not.toMatch(/catch \(reason\)[^}]+setDraft/)});
 test("does not optimistic-insert and outbound remains rendered on the right",()=>{expect(hooks).not.toContain("setQueryData");expect(chat).toContain('message.direction==="outbound"?"justify-end"');expect(page).toContain("send.mutateAsync(text)")});
});
