import{describe,expect,test}from"bun:test";import{readFileSync}from"node:fs";
const repo=readFileSync("src/modules/whatsapp/repository.ts","utf8"),hooks=readFileSync("src/modules/whatsapp/hooks/use-whatsapp-inbox.ts","utf8"),page=readFileSync("src/modules/whatsapp/pages/WhatsAppInboxPage.tsx","utf8"),list=readFileSync("src/modules/whatsapp/components/conversation-list.tsx","utf8"),chat=readFileSync("src/modules/whatsapp/components/chat-panel.tsx","utf8"),crm=readFileSync("src/modules/whatsapp/components/crm-panel.tsx","utf8"),app=readFileSync("src/app/App.tsx","utf8"),sidebar=readFileSync("src/shared/components/layout/sidebar.tsx","utf8"),mobile=readFileSync("src/shared/components/layout/mobile-navigation.tsx","utf8");
describe("WhatsApp Inbox v1",()=>{
 test("adds a protected tenant route and desktop/mobile navigation",()=>{expect(app).toContain('path="whatsapp"');expect(app).toContain('permission="crm.view"');expect(sidebar).toContain('to: "/whatsapp", label: "WhatsApp"');expect(mobile).toContain('to: "/whatsapp", label: "WhatsApp"')});
 test("reads only active organization data through authenticated Supabase",()=>{for(const table of["whatsapp_connections","whatsapp_conversations","whatsapp_messages"])expect(repo).toContain(`from("${table}")`);expect(repo.match(/\.eq\("organization_id",organizationId\)/g)?.length).toBeGreaterThanOrEqual(4);expect(repo).not.toMatch(/service_role|access.token|app.secret/i)});
 test("loads latest messages without per-conversation N+1 and sorts conversations",()=>{expect(repo).toContain('.in("conversation_id",ids)');expect(repo).toContain('.order("last_message_at",{ascending:false');expect(repo).toContain("latest.set(message.conversationId,message)")});
 test("loads selected conversation history chronologically with timestamp fallback",()=>{expect(repo).toContain('.eq("conversation_id",conversationId)');expect(repo).toContain("a.messageTimestamp||a.createdAt");expect(repo).toContain("b.messageTimestamp||b.createdAt")});
 test("Realtime is unique per tenant, filtered and cleaned up",()=>{expect(hooks).toContain('whatsapp-inbox:${organizationId}');expect(hooks.match(/filter:`organization_id=eq\.\$\{organizationId\}`/g)?.length).toBe(2);expect(hooks).toContain('table:"whatsapp_messages"');expect(hooks).toContain('table:"whatsapp_conversations"');expect(hooks).toContain("removeChannel(channel)")});
 test("renders search, status filters, selected state and empty state",()=>{expect(list).toContain("Buscar nome ou telefone");expect(list).toContain("Todas");expect(list).toContain("Abertas");expect(list).toContain("Nenhuma conversa recebida ainda.");expect(list).toContain("bg-champagne-soft")});
 test("renders inbound/outbound bubbles and safe unsupported message labels",()=>{expect(chat).toContain('direction==="outbound"');for(const label of["Mensagem de imagem","Mensagem de áudio","Mensagem de documento","Tipo de mensagem não suportado"])expect(chat).toContain(label);expect(chat).not.toContain("raw_payload")});
 test("keeps the existing composer and never calls Meta directly from the browser",()=>{expect(chat).toContain("Responder mensagem");expect(repo).toContain("whatsapp-send-message");expect(repo).not.toContain("graph.facebook.com")});
 test("shows existing CRM links read-only",()=>{for(const value of["contactDisplayName","companyName","opportunityTitle","assignedUserName"])expect(crm).toContain(value);expect(crm).toContain("A edição dos vínculos será ativada")});
 test("uses list-first mobile flow, back action and CRM drawer",()=>{expect(page).toContain('hidden md:flex');expect(chat).toContain("Voltar para conversas");expect(page).toContain("setSelectedId(undefined)");expect(crm).toContain("fixed inset-y-0 right-0");expect(page).toContain("xl:grid-cols")});
 test("handles loading, errors, no connection, no selection and no messages",()=>{for(const value of["Carregando Inbox WhatsApp","Não foi possível carregar a Inbox","WhatsApp ainda não conectado"])expect(page).toContain(value);expect(chat).toContain("Selecione uma conversa");expect(chat).toContain("Nenhuma mensagem nesta conversa")});
 test("does not introduce database migrations or SQL",()=>{expect(repo).not.toMatch(/select\s+\*\s+from|create table|alter table/i)});
});
