import { Navigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { supportWhatsappUrl } from "@/config/contact";
import { useAuth } from "@/providers/auth-context";
import { useAppState } from "@/shared/state/app-state-context";
import { BrandLogo } from "@/shared/components/brand/brand-logo";
import { useSubscriptionAccess } from "./hooks";
const date=(value?:string)=>value?new Intl.DateTimeFormat("pt-BR").format(new Date(value)):"—";
export function SubscriptionBlockedPage(){const{signOut}=useAuth();const{status,isPlatformAdmin}=useAppState();const access=useSubscriptionAccess(status==="active"&&!isPlatformAdmin);if(isPlatformAdmin)return <Navigate to="/plataforma" replace/>;if(access.isLoading)return <div className="grid min-h-[70dvh] place-items-center text-sm text-muted-foreground">Validando assinatura...</div>;if(access.data&&!access.data.isBlocked)return <Navigate to="/" replace/>;const cancelled=access.data?.status==="cancelled";return <main className="grid min-h-[calc(100dvh-4rem)] place-items-center px-4 py-10"><Card className="w-full max-w-xl"><CardContent className="p-7 sm:p-10"><BrandLogo className="w-36"/><span className="mt-8 inline-flex rounded-lg bg-red-50 px-3 py-1 text-sm font-semibold text-red-800">{cancelled?"Cancelada":"Suspensa"}</span><h1 className="mt-4 text-3xl font-semibold tracking-[-.04em]">{cancelled?"Assinatura encerrada":"Seu acesso está temporariamente suspenso"}</h1><p className="mt-3 text-muted-foreground">{cancelled?"A assinatura desta empresa foi cancelada. Seus dados continuam preservados.":"A assinatura desta empresa precisa ser regularizada para continuar utilizando o ESADS Beauty."}</p><div className="mt-6 grid gap-3 rounded-xl bg-muted p-4 text-sm sm:grid-cols-2"><p><span className="text-muted-foreground">Plano</span><b className="block">{access.data?.planName??"—"}</b></p><p><span className="text-muted-foreground">Vencimento</span><b className="block">{date(access.data?.nextDueAt)}</b></p>{Boolean(access.data?.daysOverdue)&&<p><span className="text-muted-foreground">Atraso</span><b className="block">{access.data?.daysOverdue} dias</b></p>}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a className="inline-flex min-h-12 items-center justify-center rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground" href={supportWhatsappUrl(cancelled?"Olá! Quero reativar minha assinatura do ESADS Beauty.":"Olá! Quero regularizar minha assinatura do ESADS Beauty.")} target="_blank" rel="noreferrer">{cancelled?"Reativar minha assinatura":"Regularizar assinatura"}</a><Button variant="ghost" onClick={()=>void signOut()}>Sair da conta</Button></div><button className="mt-5 text-sm font-semibold underline" onClick={()=>void access.refetch()}>Já regularizei, verificar novamente</button></CardContent></Card></main>;}
