import { Area, AreaChart, ResponsiveContainer, Tooltip } from 'recharts';
import { CalendarClock, Handshake, Target, Users } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { MetricCard } from '@/shared/components/data-display/metric-card';
import { PageContainer } from '@/shared/components/layout/page-container';
import { PageHeader } from '@/shared/components/layout/page-header';
import { useCrmData } from '@/modules/crm/hooks';
import { currency, todayISO } from '@/modules/crm/utils/formatters';
const chart = [20, 34, 28, 45, 54, 62, 71].map((value, index) => ({ name: index, value }));
export function DashboardPage() { const { data } = useCrmData(); const companies = data?.companies.filter((company) => !company.deletedAt) ?? []; const today = todayISO(); const followUpsToday = data?.followUps.filter((item) => item.date === today && item.status === 'pendente').length ?? 0; const overdue = data?.followUps.filter((item) => item.date < today && item.status === 'pendente').length ?? 0; const pipelineValue = companies.reduce((sum, company) => sum + company.estimatedValue, 0); return <PageContainer><PageHeader eyebrow="Executive overview" title="Dashboard Executivo" description="Indicadores de operação comercial, follow-ups, agenda do dia e evolução do pipeline."/><section className="grid gap-4 md:grid-cols-4"><MetricCard label="Empresas cadastradas" value={companies.length} icon={Users}/><MetricCard label="Follow-ups hoje" value={followUpsToday} icon={CalendarClock}/><MetricCard label="Follow-ups vencidos" value={overdue} icon={Target}/><MetricCard label="Pipeline estimado" value={currency.format(pipelineValue)} icon={Handshake}/></section><section className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Crescimento do pipeline</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer><AreaChart data={chart}><Tooltip/><Area dataKey="value" stroke="#A98B4D" fill="#F5EBD2"/></AreaChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>Últimas atividades</CardTitle></CardHeader><CardContent className="space-y-4">{(data?.events ?? []).slice(0, 6).map((event) => <div className="rounded-xl bg-muted p-3 text-sm" key={event.id}>{event.description}</div>)}</CardContent></Card></section></PageContainer>; }
