import { useState } from "react";
import { CalendarCheck, Check, FileSignature, PackageCheck, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Modal } from "@/shared/components/overlays/modal";
import { currency, formatDateTime } from "@/modules/crm/utils/formatters";
import { useCustomerActions, useCustomerByCompany } from "../hooks";
import type { BillingInterval, BillingType, CustomerAccount } from "../types";

const serviceStatusLabel: Record<string,string> = {pending:"Pendente",active:"Ativo",paused:"Pausado",completed:"Concluído",cancelled:"Cancelado"};
const contractStatusLabel: Record<string,string> = {draft:"Rascunho",sent:"Enviado",signed:"Assinado",active:"Ativo",expired:"Expirado",cancelled:"Cancelado"};
const statusLabel = { onboarding:"Em onboarding", active:"Ativo", paused:"Pausado", cancelled:"Cancelado", inactive:"Inativo" } as const;
export function CustomerStatusBadge({account}:{account:CustomerAccount}) { return <span className="rounded-full border border-champagne/50 bg-champagne/10 px-3 py-1 text-xs font-bold">{statusLabel[account.status]}</span>; }

export function CustomerWorkspace({ companyId }:{ companyId:string }) {
  const customer=useCustomerByCompany(companyId); const actions=useCustomerActions(); const [modal,setModal]=useState<"catalog"|"service"|"onboarding"|"contract"|"partnership"|"editService"|null>(null); const [editingService,setEditingService]=useState<import("../types").CustomerService|null>(null); const [stepTitle,setStepTitle]=useState("");
  const account=customer.account; const data=customer.data;
  if(customer.isLoading) return <Card><CardContent className="p-6 text-sm text-muted-foreground">Carregando contexto do cliente...</CardContent></Card>;
  if(!account||!data) return <Card><CardContent className="p-6"><p className="font-semibold">Relacionamento de cliente ainda não iniciado.</p><p className="mt-1 text-sm text-muted-foreground">Ao ganhar uma oportunidade, o pós-venda será ativado sem duplicar os dados da empresa.</p></CardContent></Card>;
  const serviceName=(id:string)=>data.services.find((item)=>item.id===id)?.name??"Serviço removido do catálogo";
  const activeServices=customer.services.filter(item=>item.status==="active"||item.status==="pending");
  const currencyValue=(value:number|undefined)=>value===undefined?"Não informado":currency.format(value);
  const dateValue=(value:string|undefined)=>value?new Date(value.slice(0,10)+"T12:00:00").toLocaleDateString("pt-BR"):"Não definido";
  const daysTogether=Math.max(0,Math.floor((Date.now()-new Date(account.clientSince).getTime())/86400000));
  const renewals=activeServices.filter(item=>item.endDate).sort((a,b)=>(a.endDate??"").localeCompare(b.endDate??""));
  return <div className="space-y-5">
    <Card><CardContent className="space-y-4 p-4 md:p-6"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="space-y-2"><h2 className="text-xl font-bold">Gestão da parceria</h2><CustomerStatusBadge account={account}/><p className="text-sm text-muted-foreground">Cliente desde {dateValue(account.clientSince)} · {daysTogether} dias de parceria</p></div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>setModal("partnership")}>Editar parceria</Button><Button size="sm" variant="outline" onClick={()=>setModal("service")}><Plus size={15}/>Adicionar serviço</Button><Button size="sm" variant="outline" onClick={()=>setModal("catalog")}>Catálogo</Button></div></div>{account.driveFolderUrl&&<a className="inline-flex min-h-10 items-center rounded-lg border px-4 text-sm font-medium hover:bg-muted" href={account.driveFolderUrl} target="_blank" rel="noopener noreferrer">Abrir pasta do cliente ↗</a>}</CardContent></Card>
    <div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">Serviços ativos</p><p className="text-3xl font-semibold">{activeServices.length}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">Valor recorrente mensal conhecido</p><p className="text-2xl font-semibold">{currency.format(activeServices.filter(item=>item.billingInterval==="monthly").reduce((sum,item)=>sum+(item.agreedPrice??0),0))}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">Próxima renovação</p><p className="text-xl font-semibold">{renewals.length?dateValue(renewals[0].endDate):"Não definida"}</p></CardContent></Card></div>
    <Card><CardHeader><CardTitle>Serviços contratados</CardTitle></CardHeader><CardContent className="space-y-3">{customer.services.length===0?<p className="text-sm text-muted-foreground">Nenhum serviço cadastrado para este cliente.</p>:customer.services.map(item=>{const remaining=item.endDate?Math.ceil((new Date(item.endDate+"T12:00:00").getTime()-Date.now())/86400000):null;return <div key={item.id} className="flex flex-col gap-3 rounded-xl border p-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0 space-y-1"><p className="font-semibold">{serviceName(item.serviceId)}</p><p className="text-sm text-muted-foreground">{serviceStatusLabel[item.status]} · {currencyValue(item.agreedPrice)} · {item.billingInterval==="monthly"?"Mensal":item.billingInterval==="quarterly"?"Trimestral":item.billingInterval==="yearly"?"Anual":"Personalizado"}</p><p className="text-xs text-muted-foreground">Início: {dateValue(item.startDate)} · Término/renovação: {dateValue(item.endDate)}</p>{remaining!==null&&remaining<=(account.renewalReminderDays??30)&&<p className="text-sm font-medium text-amber-700">{remaining<0?"Renovação vencida há "+Math.abs(remaining)+" dia(s)":"Renovação em "+remaining+" dia(s)"}</p>}{item.notes&&<p className="text-sm">{item.notes}</p>}</div><Button size="sm" variant="outline" onClick={()=>{setEditingService(item);setModal("editService");}}>Editar serviço</Button></div>})}</CardContent></Card>
    <Card><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium">Situação da parceria</p><p className="text-sm text-muted-foreground">Pause, reative ou encerre sem apagar o histórico.</p></div><div className="flex flex-wrap gap-2">{account.status==="paused"||account.status==="cancelled"?<Button variant="outline" size="sm" onClick={()=>actions.setCustomerStatus.mutate({id:account.id,status:"active"})}>Reativar</Button>:<Button variant="outline" size="sm" onClick={()=>window.confirm("Pausar a parceria?")&&actions.setCustomerStatus.mutate({id:account.id,status:"paused"})}>Pausar</Button>}<Button size="sm" variant="ghost" onClick={()=>window.confirm("Encerrar a parceria sem apagar o histórico?")&&actions.setCustomerStatus.mutate({id:account.id,status:"cancelled",reason:"other"})}>Encerrar</Button></div></CardContent></Card>
    <PartnershipEditor open={modal==="partnership"} close={()=>setModal(null)} account={account} actions={actions}/>
    <ServiceEditor open={modal==="editService"} close={()=>{setModal(null);setEditingService(null);}} service={editingService} actions={actions}/>

    <SimpleModal type={modal==="partnership"||modal==="editService"?null:modal} close={()=>setModal(null)} account={account} data={data} actions={actions}/>
  </div>;
}

type Actions=ReturnType<typeof useCustomerActions>; type Data=NonNullable<ReturnType<typeof useCustomerByCompany>["data"]>;
function SimpleModal({type,close,account,data,actions}:{type:"catalog"|"service"|"onboarding"|"contract"|null;close:()=>void;account:CustomerAccount;data:Data;actions:Actions}){
 const [name,setName]=useState("");const [selected,setSelected]=useState("");const [price,setPrice]=useState("");const [title,setTitle]=useState("");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [billing,setBilling]=useState<BillingType>("custom");const [interval,setInterval]=useState<BillingInterval>("custom");
 const submit=async()=>{if(type==="catalog")await actions.createService.mutateAsync({name,billingType:billing});if(type==="service")await actions.addCustomerService.mutateAsync({customerAccountId:account.id,serviceId:selected,agreedPrice:price?Number(price):undefined,billingType:billing,billingInterval:interval,startDate:date});if(type==="onboarding")await actions.startOnboarding.mutateAsync({customerAccountId:account.id,customerServiceId:selected||undefined,title,dueAt:date?new Date(`${date}T23:59:00`).toISOString():undefined});if(type==="contract")await actions.createContract.mutateAsync({customerAccountId:account.id,title,startDate:date,billingType:billing,billingInterval:interval,autoRenew:false,noticeDays:30,customerServiceIds:selected?[selected]:[]});close();};
 return <Modal open={type!==null} title={type==="catalog"?"Novo serviço no catálogo":type==="service"?"Registrar serviço contratado":type==="onboarding"?"Iniciar onboarding":"Registrar contrato"} onClose={close}><div className="space-y-4">{(type==="catalog"||type==="onboarding"||type==="contract")&&<div><Label>{type==="catalog"?"Nome do serviço":"Título"}</Label><Input value={type==="catalog"?name:title} onChange={(e)=>type==="catalog"?setName(e.target.value):setTitle(e.target.value)}/></div>}{type!=="catalog"&&<div><Label>{type==="contract"?"Serviço vinculado (opcional)":"Serviço"}</Label><Select value={selected} onChange={(e)=>setSelected(e.target.value)}><option value="">Selecione</option>{(type==="service"?data.services:data.customerServices).map((item)=><option key={item.id} value={item.id}>{"name" in item?item.name:data.services.find((service)=>service.id===item.serviceId)?.name}</option>)}</Select></div>}{type==="service"&&<div><Label>Data de início</Label><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>}{type==="service"&&<div><Label>Valor negociado</Label><Input type="number" min="0" step="0.01" value={price} onChange={(e)=>setPrice(e.target.value)}/></div>}{(type==="onboarding"||type==="contract")&&<div><Label>{type==="contract"?"Início da vigência":"Prazo"}</Label><Input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></div>}{(type==="catalog"||type==="service"||type==="contract")&&<div><Label>Classificação comercial</Label><Select value={billing} onChange={(e)=>setBilling(e.target.value as BillingType)}><option value="custom">Personalizado</option><option value="recurring">Recorrente</option><option value="one_time">Pontual</option></Select></div>}<Button disabled={(type==="catalog"&&!name)||(type!=="catalog"&&!title&&type!=="service")||(type==="service"&&!selected)} onClick={submit}>Salvar</Button></div></Modal>;
}

function PartnershipEditor({open,close,account,actions}:{open:boolean;close:()=>void;account:CustomerAccount;actions:Actions}){
 const [drive,setDrive]=useState(account.driveFolderUrl??"");const [reminder,setReminder]=useState(String(account.renewalReminderDays??30));const [since,setSince]=useState(account.clientSince.slice(0,10));
 return <Modal open={open} title="Editar parceria" onClose={close}><div className="space-y-4"><div><Label>Início da parceria</Label><Input type="date" value={since} onChange={e=>setSince(e.target.value)}/></div><div><Label>Link da pasta no Google Drive</Label><Input type="url" placeholder="https://drive.google.com/..." value={drive} onChange={e=>setDrive(e.target.value)}/></div><div><Label>Avisar sobre renovação com quantos dias de antecedência?</Label><Input type="number" min="0" max="365" value={reminder} onChange={e=>setReminder(e.target.value)}/><p className="mt-1 text-xs text-muted-foreground">Alertas visuais na ficha do cliente; sem notificação automática nesta etapa.</p></div><Button disabled={actions.updatePartnership.isPending||(!since)||(Boolean(drive)&&!/^https:\/\//i.test(drive))} onClick={async()=>{await actions.updatePartnership.mutateAsync({id:account.id,input:{driveFolderUrl:drive.trim(),renewalReminderDays:Math.min(365,Math.max(0,Number(reminder)||0)),clientSince:since}});close();}}>Salvar parceria</Button></div></Modal>;
}
function ServiceEditor({open,close,service,actions}:{open:boolean;close:()=>void;service:import("../types").CustomerService|null;actions:Actions}){
 const [draft,setDraft]=useState<import("../types").CustomerService|null>(null);
 const item=draft?.id===service?.id?draft:service;
 if(!service||!item)return null;
 const update=(patch:Partial<import("../types").CustomerService>)=>setDraft({...item,...patch});
 return <Modal open={open} title="Editar serviço contratado" onClose={close}><div className="space-y-4"><div><Label>Situação</Label><Select value={item.status} onChange={e=>update({status:e.target.value as import("../types").ServiceStatus})}><option value="pending">Pendente</option><option value="active">Ativo</option><option value="paused">Pausado</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option></Select></div><div><Label>Valor acordado (R$)</Label><Input type="number" min="0" step="0.01" value={item.agreedPrice??""} onChange={e=>update({agreedPrice:e.target.value===""?undefined:Number(e.target.value)})}/></div><div><Label>Cobrança</Label><Select value={item.billingInterval} onChange={e=>update({billingInterval:e.target.value as BillingInterval})}><option value="monthly">Mensal</option><option value="quarterly">Trimestral</option><option value="yearly">Anual</option><option value="one_time">Única</option><option value="custom">Personalizada</option></Select></div><div><Label>Início do serviço</Label><Input type="date" value={item.startDate?.slice(0,10)??""} onChange={e=>update({startDate:e.target.value})}/></div><div><Label>Término ou renovação</Label><Input type="date" value={item.endDate?.slice(0,10)??""} onChange={e=>update({endDate:e.target.value||undefined})}/></div><div><Label>Observações</Label><Input value={item.notes??""} onChange={e=>update({notes:e.target.value})}/></div><Button disabled={actions.updateCustomerService.isPending} onClick={async()=>{await actions.updateCustomerService.mutateAsync({id:service.id,input:{status:item.status,agreedPrice:item.agreedPrice??null,billingInterval:item.billingInterval,startDate:item.startDate,endDate:item.endDate??null,notes:item.notes??null}});setDraft(null);close();}}>Salvar serviço</Button></div></Modal>;
}
