import { useState } from "react";
import { CalendarCheck, Check, FileSignature, PackageCheck, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Modal } from "@/shared/components/overlays/modal";
import { currency, formatDateTime } from "@/modules/crm/utils/formatters";
import { useCustomerActions, useCustomerByCompany } from "../hooks";
import type { BillingInterval, BillingType, CustomerAccount } from "../types";

const serviceStatusLabel: Record<string,string> = {pending:"Pendente",active:"Ativo",paused:"Pausado",completed:"Concluído",cancelled:"Cancelado"};
const contractStatusLabel: Record<string,string> = {draft:"Rascunho",sent:"Enviado",signed:"Assinado",active:"Ativo",expired:"Expirado",cancelled:"Cancelado"};
const statusLabel = { onboarding:"Em onboarding", active:"Ativo", paused:"Pausado", cancelled:"Cancelado", inactive:"Inativo" } as const;
export function CustomerStatusBadge({account}:{account:CustomerAccount}) { return <span className="rounded-full border border-champagne/50 bg-champagne/10 px-3 py-1 text-xs font-bold">{statusLabel[account.status]}</span>; }

export function CustomerWorkspace({ companyId }:{ companyId:string }) {
  const customer=useCustomerByCompany(companyId); const actions=useCustomerActions(); const [modal,setModal]=useState<"catalog"|"service"|"onboarding"|"contract"|null>(null); const [stepTitle,setStepTitle]=useState("");
  const account=customer.account; const data=customer.data;
  if(customer.isLoading) return <Card><CardContent className="p-6 text-sm text-muted-foreground">Carregando contexto do cliente...</CardContent></Card>;
  if(!account||!data) return <Card><CardContent className="p-6"><p className="font-semibold">Relacionamento de cliente ainda não iniciado.</p><p className="mt-1 text-sm text-muted-foreground">Ao ganhar uma oportunidade, o pós-venda será ativado sem duplicar os dados da empresa.</p></CardContent></Card>;
  const serviceName=(id:string)=>data.services.find((item)=>item.id===id)?.name??"Serviço removido do catálogo";
  return <div className="space-y-5">
    <Card><CardContent className="flex flex-col justify-between gap-4 p-6 md:flex-row md:items-center"><div><div className="flex items-center gap-3"><h2 className="text-xl font-bold">Relacionamento pós-venda</h2><CustomerStatusBadge account={account}/></div><p className="mt-2 text-sm text-muted-foreground">Cliente desde {formatDateTime(account.clientSince)} · dados cadastrais permanecem na empresa.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setModal("catalog")}><Plus size={15}/>Catálogo</Button><Button size="sm" onClick={()=>setModal("service")}><Plus size={15}/>Contratar serviço</Button>{account.status==="paused"?<Button size="sm" variant="outline" onClick={()=>actions.setCustomerStatus.mutate({id:account.id,status:"active"})}>Reativar</Button>:<Button size="sm" variant="ghost" onClick={()=>window.confirm("Pausar este relacionamento de cliente?")&&actions.setCustomerStatus.mutate({id:account.id,status:"paused"})}>Pausar</Button>}<Button size="sm" variant="ghost" onClick={()=>window.confirm("Cancelar o relacionamento sem apagar o histórico?")&&actions.setCustomerStatus.mutate({id:account.id,status:"cancelled",reason:"other"})}>Cancelar</Button></div></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-3">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><PackageCheck size={18}/>Serviços</CardTitle></CardHeader><CardContent className="space-y-3">{customer.services.length===0?<p className="text-sm text-muted-foreground">Nenhum serviço contratado.</p>:customer.services.map((item)=><div key={item.id} className="rounded-xl border p-3"><b>{serviceName(item.serviceId)}</b><p className="text-xs text-muted-foreground">{serviceStatusLabel[item.status]} · {item.agreedPrice===undefined?"Valor não informado":currency.format(item.agreedPrice)}</p></div>)}<Button size="sm" variant="ghost" onClick={()=>setModal("service")}><Plus size={14}/>Adicionar</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarCheck size={18}/>Onboarding</CardTitle></CardHeader><CardContent className="space-y-3">{customer.onboardings.length===0?<p className="text-sm text-muted-foreground">Nenhum onboarding ativo.</p>:customer.onboardings.map((item)=>{const steps=data.steps.filter((step)=>step.onboardingId===item.id);const done=steps.filter((step)=>step.status==="completed").length;return <div key={item.id} className="rounded-xl border p-3"><b>{item.title}</b><div className="my-2 h-1.5 overflow-hidden rounded bg-muted"><div className="h-full bg-champagne" style={{width:`${steps.length?done/steps.length*100:0}%`}}/></div><p className="text-xs text-muted-foreground">{done} de {steps.length} etapas</p>{steps.filter((step)=>step.status!=="completed").slice(0,2).map((step)=><button key={step.id} className="mt-2 flex w-full items-center gap-2 text-left text-sm" onClick={()=>actions.completeOnboardingStep.mutate(step.id)}><span className="grid h-5 w-5 place-items-center rounded border"><Check size={12}/></span>{step.title}</button>)}</div>})}<div className="flex gap-2"><Input aria-label="Nova etapa de onboarding" placeholder="Nova etapa" value={stepTitle} onChange={(event)=>setStepTitle(event.target.value)}/><Button size="sm" variant="outline" disabled={!stepTitle.trim()||!customer.onboardings[0]} onClick={async()=>{await actions.addOnboardingStep.mutateAsync({onboardingId:customer.onboardings[0].id,title:stepTitle.trim()});setStepTitle("");}}><Plus size={14}/></Button></div><Button size="sm" variant="ghost" onClick={()=>setModal("onboarding")}><Plus size={14}/>Iniciar</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileSignature size={18}/>Contratos</CardTitle></CardHeader><CardContent className="space-y-3">{customer.contracts.length===0?<p className="text-sm text-muted-foreground">Nenhum contrato registrado.</p>:customer.contracts.map((item)=><div key={item.id} className="rounded-xl border p-3"><b>{item.title}</b><p className="text-xs text-muted-foreground">{item.contractNumber} · {contractStatusLabel[item.status]}</p><p className="text-xs">{formatDateTime(item.startDate)}{item.endDate?` — ${formatDateTime(item.endDate)}`:" · sem término"}</p>{item.status!=="active"&&<Button className="mt-2" size="sm" variant="outline" onClick={()=>actions.activateContract.mutate(item.id)}>Marcar ativo</Button>}</div>)}<Button size="sm" variant="ghost" onClick={()=>setModal("contract")}><Plus size={14}/>Registrar</Button></CardContent></Card>
    </div>
    <SimpleModal type={modal} close={()=>setModal(null)} account={account} data={data} actions={actions}/>
  </div>;
}

type Actions=ReturnType<typeof useCustomerActions>; type Data=NonNullable<ReturnType<typeof useCustomerByCompany>["data"]>;
function SimpleModal({type,close,account,data,actions}:{type:"catalog"|"service"|"onboarding"|"contract"|null;close:()=>void;account:CustomerAccount;data:Data;actions:Actions}){
 const [name,setName]=useState("");const [selected,setSelected]=useState("");const [price,setPrice]=useState("");const [title,setTitle]=useState("");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [billing,setBilling]=useState<BillingType>("custom");const [interval,setInterval]=useState<BillingInterval>("custom");
 const submit=async()=>{if(type==="catalog")await actions.createService.mutateAsync({name,billingType:billing});if(type==="service")await actions.addCustomerService.mutateAsync({customerAccountId:account.id,serviceId:selected,agreedPrice:price?Number(price):undefined,billingType:billing,billingInterval:interval});if(type==="onboarding")await actions.startOnboarding.mutateAsync({customerAccountId:account.id,customerServiceId:selected||undefined,title,dueAt:date?new Date(`${date}T23:59:00`).toISOString():undefined});if(type==="contract")await actions.createContract.mutateAsync({customerAccountId:account.id,title,startDate:date,billingType:billing,billingInterval:interval,autoRenew:false,noticeDays:30,customerServiceIds:selected?[selected]:[]});close();};
 return <Modal open={type!==null} title={type==="catalog"?"Novo serviço no catálogo":type==="service"?"Registrar serviço contratado":type==="onboarding"?"Iniciar onboarding":"Registrar contrato"} onClose={close}><div className="space-y-4">{(type==="catalog"||type==="onboarding"||type==="contract")&&<div><Label>{type==="catalog"?"Nome do serviço":"Título"}</Label><Input value={type==="catalog"?name:title} onChange={(e)=>type==="catalog"?setName(e.target.value):setTitle(e.target.value)}/></div>}{type!=="catalog"&&<div><Label>{type==="contract"?"Serviço vinculado (opcional)":"Serviço"}</Label><Select value={selected} onChange={(e)=>setSelected(e.target.value)}><option value="">Selecione</option>{(type==="service"?data.services:data.customerServices).map((item)=><option key={item.id} value={item.id}>{"name" in item?item.name:data.services.find((service)=>service.id===item.serviceId)?.name}</option>)}</Select></div>}{type==="service"&&<div><Label>Valor negociado</Label><Input type="number" min="0" step="0.01" value={price} onChange={(e)=>setPrice(e.target.value)}/></div>}{(type==="onboarding"||type==="contract")&&<div><Label>{type==="contract"?"Início da vigência":"Prazo"}</Label><Input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></div>}{(type==="catalog"||type==="service"||type==="contract")&&<div><Label>Classificação comercial</Label><Select value={billing} onChange={(e)=>setBilling(e.target.value as BillingType)}><option value="custom">Personalizado</option><option value="recurring">Recorrente</option><option value="one_time">Pontual</option></Select></div>}<Button disabled={(type==="catalog"&&!name)||(type!=="catalog"&&!title&&type!=="service")||(type==="service"&&!selected)} onClick={submit}>Salvar</Button></div></Modal>;
}
