import { Link } from "react-router-dom";
import { generalContactEmail } from "@/config/contact";
import { LegalDocument, type LegalSection } from "../components/legal-document";

const sections: LegalSection[] = [
  { title: "Aceitação dos Termos", content: <p>Ao acessar ou utilizar o ESADS Beauty, o usuário declara que leu e concorda com estes Termos de Uso e com a nossa <Link to="/politica-de-privacidade">Política de Privacidade</Link>. Caso não concorde, não deverá utilizar a plataforma.</p> },
  { title: "Sobre o ESADS Beauty", content: <p>O ESADS Beauty é uma plataforma SaaS/CRM voltada à organização comercial de empresas e profissionais de estética e beleza. Seus recursos podem incluir gestão de leads e clientes, oportunidades, follow-ups, WhatsApp Business, automações, relatórios, marketing e integrações com serviços de terceiros.</p> },
  { title: "Cadastro e conta", content: <><p>O usuário deve fornecer informações verdadeiras, completas e atualizadas. É responsável por proteger suas credenciais, não compartilhar acessos de forma indevida e comunicar suspeitas de uso não autorizado.</p><p>As atividades realizadas com suas credenciais serão atribuídas à sua conta, ressalvadas situações comprovadas de falha de segurança não causada pelo usuário.</p></> },
  { title: "Organizações e usuários", content: <p>A plataforma organiza dados e acessos por organizações. Os administradores de cada organização podem convidar usuários, atribuir funções e permissões e controlar o acesso às informações sob sua responsabilidade. Cada usuário deve atuar apenas dentro das autorizações que recebeu.</p> },
  { title: "Uso permitido", content: <p>O ESADS Beauty deve ser utilizado para finalidades legítimas relacionadas às atividades profissionais e comerciais do cliente, de acordo com estes Termos, com a legislação aplicável e com as regras dos serviços integrados.</p> },
  { title: "Uso proibido", content: <><p>Não é permitido utilizar a plataforma para:</p><ul><li>praticar atos ilegais, fraudulentos, abusivos ou enganosos;</li><li>enviar spam ou conteúdo ilícito, ofensivo ou que viole direitos de terceiros;</li><li>tentar invadir sistemas, explorar vulnerabilidades ou obter acesso não autorizado;</li><li>interferir na segurança, estabilidade ou disponibilidade dos serviços;</li><li>usar o WhatsApp em desacordo com as políticas da Meta e do WhatsApp Business;</li><li>coletar ou tratar dados pessoais sem fundamento legal adequado.</li></ul></> },
  { title: "Responsabilidade pelos dados cadastrados", content: <p>O cliente é responsável pelos dados que inserir na plataforma, pelas informações de leads, pacientes, clientes e contatos e pela existência de base legal para seu tratamento. Também deve utilizar os dados de maneira adequada e cumprir a LGPD e demais normas aplicáveis às suas atividades.</p> },
  { title: "WhatsApp Business", content: <><p>Algumas funcionalidades dependem da Meta e da Plataforma WhatsApp Business. O usuário deve observar as políticas aplicáveis ao canal. Templates, janelas de atendimento, limites, preços e outras condições podem ser definidos ou alterados pela Meta.</p><p>Bloqueios, limitações, suspensões e indisponibilidades impostas pela Meta não são controlados pela ESADS Beauty. Não garantimos a aprovação de números, contas, templates ou mensagens por plataformas externas.</p></> },
  { title: "Serviços de terceiros", content: <p>A plataforma pode depender de serviços externos de infraestrutura, hospedagem, banco de dados, autenticação, integração, Meta e WhatsApp. Falhas, alterações ou indisponibilidades desses fornecedores podem afetar temporariamente determinadas funcionalidades.</p> },
  { title: "Disponibilidade da plataforma", content: <p>Buscamos manter a plataforma segura e disponível, mas não garantimos funcionamento ininterrupto ou livre de falhas. Poderão ocorrer manutenções, atualizações, falhas técnicas, interrupções emergenciais ou indisponibilidades causadas por terceiros.</p> },
  { title: "Planos, cobrança e pagamentos", content: <p>O acesso a determinados recursos pode depender do plano contratado. Preços, limites e condições podem variar conforme a oferta vigente. Serviços de terceiros podem possuir cobranças próprias, e valores cobrados pela Meta ou pelo WhatsApp não estão necessariamente incluídos na assinatura do ESADS Beauty.</p> },
  { title: "Propriedade intelectual", content: <p>O software, a marca, a identidade visual, o código, a interface, a documentação e os materiais do ESADS Beauty pertencem à ESADS Beauty ou aos respectivos licenciadores. O direito de uso da plataforma é limitado aos termos da contratação e não transfere propriedade intelectual ao cliente.</p> },
  { title: "Dados do cliente", content: <p>O cliente permanece titular de seus dados comerciais e dos conteúdos que inserir na plataforma, observadas as responsabilidades legais, os direitos de terceiros e as condições necessárias para operação e suporte do serviço.</p> },
  { title: "Suspensão e encerramento", content: <p>O acesso poderá ser suspenso ou encerrado em caso de violação destes Termos, fraude, abuso, uso ilegal, risco relevante à segurança ou inadimplência, quando aplicável. Sempre que razoável e permitido, serão considerados a gravidade da situação e os meios disponíveis para regularização.</p> },
  { title: "Limitação de responsabilidade", content: <><p>O ESADS Beauty é uma ferramenta de apoio à organização e à gestão. Não prometemos resultados comerciais, vendas ou conversões e não somos responsáveis pelas decisões comerciais, campanhas ou comunicações realizadas pelo cliente.</p><p>Nos limites permitidos pela legislação, a ESADS Beauty não se responsabiliza por prejuízos decorrentes do uso incorreto da plataforma, de dados ou instruções fornecidos pelo usuário, de indisponibilidade de terceiros ou de bloqueios em contas externas. Esta cláusula não afasta responsabilidades que não possam ser excluídas por lei.</p></> },
  { title: "Alterações dos Termos", content: <p>Estes Termos poderão ser atualizados para acompanhar mudanças na plataforma, nas regras aplicáveis ou nos serviços integrados. A versão vigente e sua data de atualização permanecerão disponíveis publicamente nesta página.</p> },
  { title: "Lei aplicável", content: <p>Estes Termos são regidos pelas leis da República Federativa do Brasil, sem definição de foro específico nesta versão.</p> },
  { title: "Contato", content: <p>Para dúvidas sobre estes Termos de Uso, entre em contato com a ESADS Beauty pelo e-mail <a href={`mailto:${generalContactEmail}`}>{generalContactEmail}</a>.</p> },
];

export function TermsOfUsePage() {
  return <LegalDocument title="Termos de Uso" eyebrow="Condições de utilização" description="Conheça as condições para utilizar o ESADS Beauty e suas ferramentas de gestão, comunicação e integração." path="/termos-de-uso" sections={sections} relatedLink={{to:"/politica-de-privacidade",label:"Consulte também nossa Política de Privacidade"}} />;
}
