import { diagnosticWhatsappUrl } from "../../../config/contact";
import { categoryContent } from "../content";
import type { DiagnosticCategory, DiagnosticSubmission } from "../types";
import { pdfLogoBase64 } from "./pdf-logo";
import { qrModules } from "./pdf-qr";
import { pdfTheme } from "./pdf-theme";

const rgb=(hex:string)=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v.toFixed(3)).join(" ");
const C=Object.fromEntries(Object.entries(pdfTheme.colors).map(([k,v])=>[k,rgb(v)])) as Record<keyof typeof pdfTheme.colors,string>;
const esc=(v:string)=>v.replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/[—–]/g,"-").replace(/[^\x20-\xFF]/g,"?");
const text=(v:string,x:number,y:number,s=13,c=C.black,f="F1")=>`BT /${f} ${s} Tf ${c} rg ${x} ${y} Td (${esc(v)}) Tj ET`;
const rect=(x:number,y:number,w:number,h:number,c:string,r=false)=>`${c} ${r?"RG 1 w":"rg"} ${x} ${y} ${w} ${h} re ${r?"S":"f"}`;
const line=(x:number,y:number,w:number,c=C.gold)=>`${c} RG 1 w ${x} ${y} m ${x+w} ${y} l S`;
const fill=(c:string)=>rect(0,0,pdfTheme.page.width,pdfTheme.page.height,c);
const percent=(value:number)=>Math.min(100,Math.max(0,Number.isFinite(value)?value:0));
const wrap=(v:string,n=63)=>{const out:string[]=[],words=v.split(/\s+/);let row="";for(const word of words){if(`${row} ${word}`.trim().length>n){out.push(row);row=word}else row=`${row} ${word}`.trim()}if(row)out.push(row);return out};
const para=(v:string,x:number,y:number,w=63,s=12,c=C.black,lh=19)=>wrap(v,w).map((r,i)=>text(r,x,y-i*lh,s,c)).join("\n");
const eyebrow=(v:string,y=760,c=C.gold)=>[text(v.toUpperCase(),52,y,9,c,"F2"),line(52,y-15,44,c)].join("\n");
const logo=(x:number,y:number,w:number)=>`q ${w} 0 0 ${w} ${x} ${y} cm /Logo Do Q`;
const card=(x:number,y:number,w:number,h:number,dark=false)=>rect(x,y,w,h,dark?C.nearBlack:C.white);
const formatPhone=(raw:string)=>{const d=raw.replace(/\D/g,"").replace(/^55/,"");return d.length===11?`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`:d.length===10?`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`:raw};
const qr=(value:string,x:number,y:number,size=116)=>{const m=qrModules(value),q=size/m.length;return [rect(x-5,y-5,size+10,size+10,C.white),...m.flatMap((row,yy)=>row.map((on,xx)=>on?rect(x+xx*q,y+(m.length-1-yy)*q,q+.15,q+.15,C.black):""))].join("\n")};
const strategic=(category:DiagnosticCategory)=>{const c=categoryContent[category];return{identified:c.discovery,impact:`Sem atenção a ${c.label.toLowerCase()}, oportunidades podem se perder e o crescimento tende a depender de ações pouco previsíveis.`,opportunity:c.recommendation}};

function pngObject(){const bytes=Uint8Array.from(atob(pdfLogoBase64),c=>c.charCodeAt(0));let p=8,w=0,h=0,idat:number[]=[];while(p<bytes.length){const n=(bytes[p]<<24)|(bytes[p+1]<<16)|(bytes[p+2]<<8)|bytes[p+3],type=String.fromCharCode(...bytes.slice(p+4,p+8)),data=bytes.slice(p+8,p+8+n);if(type==="IHDR"){w=(data[0]<<24)|(data[1]<<16)|(data[2]<<8)|data[3];h=(data[4]<<24)|(data[5]<<16)|(data[6]<<8)|data[7]}if(type==="IDAT")idat.push(...data);p+=12+n}const binary=String.fromCharCode(...idat);return`<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /FlateDecode /DecodeParms << /Predictor 15 /Colors 3 /BitsPerComponent 8 /Columns ${w} >> /Length ${binary.length} >>\nstream\n${binary}\nendstream`}

export function createDiagnosticPdf(s:DiagnosticSubmission){const r=s.result,ordered=Object.entries(r.categoryScores).sort((a,b)=>b[1]-a[1]) as [DiagnosticCategory,number][],bottleneck=categoryContent[r.primaryBottleneck],detail=strategic(r.primaryBottleneck),strong=ordered.slice(0,3),date=new Intl.DateTimeFormat("pt-BR").format(new Date(s.createdAt)),whatsapp=diagnosticWhatsappUrl(s.lead.name,r.totalScore),phone=formatPhone(s.lead.whatsapp),pages:string[]=[];
 pages.push([fill(C.black),rect(34,34,527,774,C.gold,true),logo(48,646,150),eyebrow("Diagnóstico estratégico",608),text("DIAGNÓSTICO",52,530,39,C.white,"F2"),text("DO SEU NEGÓCIO",52,484,39,C.goldLight,"F2"),text("Uma análise do momento atual da sua estética",52,446,13,C.gray),line(52,414,490),text("PREPARADO ESPECIALMENTE PARA",52,350,9,C.gray,"F2"),text(s.lead.name.slice(0,36),52,306,s.lead.name.length>25?21:28,C.white,"F2"),text(`@${s.lead.instagram.replace(/^@/,"")}`,52,270,13,C.goldLight),text(phone,52,245,12,C.white),text(date,52,220,11,C.gray),text("ESADS BEAUTY  ·  DIAGNÓSTICO PARA NEGÓCIOS DE ESTÉTICA",52,62,8,C.gray,"F2")].join("\n"));
 const score=percent(r.totalScore),scoreW=Math.max(4,430*score/100);pages.push([fill(C.ivory),eyebrow("Resumo executivo"),text("SEU NEGÓCIO HOJE",52,700,29,C.black,"F2"),card(52,432,491,226),text(String(Math.round(score)),78,522,88,C.gold,"F2"),text("DE 100",83,495,10,C.gray,"F2"),rect(78,466,430,8,C.line),rect(78,466,scoreW,8,C.gold),rect(295,565,215,42,C.nearBlack),text(r.level.toUpperCase().slice(0,28),311,581,10,C.goldLight,"F2"),text("PRINCIPAL OPORTUNIDADE",295,526,9,C.gray,"F2"),text(bottleneck.label,295,494,19,C.black,"F2"),text("RESUMO EXECUTIVO",52,388,9,C.gold,"F2"),para(`Pelas suas respostas, seu negócio está em ${r.level.toLowerCase()}. O próximo passo é transformar ações isoladas em uma rotina mais organizada, consistente e preparada para crescer.`,52,354,68,13,C.black,21)].join("\n"));
 const bars=ordered.map(([key,v],i)=>{const y=616-i*66,label=categoryContent[key].label,tag=i===0?"PONTO FORTE":i===ordered.length-1?"MAIOR OPORTUNIDADE":"";return[card(52,y-22,491,52),text(label.toUpperCase(),68,y+8,10,C.black,"F2"),text(`${Math.round(v)}/100`,467,y+8,10,C.gray,"F2"),rect(68,y-8,410,6,C.line),rect(68,y-8,Math.max(3,410*percent(v)/100),6,C.gold),tag?text(tag,356,y+8,7,C.gold,"F2"):""].join("\n")}).join("\n");pages.push([fill(C.ivory),eyebrow("Visão por área"),text("MAPA DE MATURIDADE",52,700,27,C.black,"F2"),text("DO NEGÓCIO",52,667,27,C.black,"F2"),bars].join("\n"));
 pages.push([fill(C.black),eyebrow("Gargalo principal"),text("O QUE MAIS MERECE",52,690,27,C.white,"F2"),text("SUA ATENÇÃO AGORA",52,655,27,C.white,"F2"),line(52,625,490),text(bottleneck.label.toUpperCase(),52,566,25,C.goldLight,"F2"),...[["01  O QUE IDENTIFICAMOS",detail.identified],["02  POR QUE ISSO IMPORTA",detail.impact],["03  A OPORTUNIDADE",detail.opportunity]].flatMap(([h,v],i)=>{const y=450-i*128;return[card(52,y-72,491,102,true),text(h,70,y,9,C.gold,"F2"),para(v,70,y-27,59,11,C.white,17)]})].join("\n"));
 pages.push([fill(C.ivory),eyebrow("Pontos fortes"),text("O QUE VOCÊ JÁ ESTÁ",52,700,27,C.black,"F2"),text("CONSTRUINDO BEM",52,666,27,C.black,"F2"),...strong.flatMap(([key],i)=>{const y=525-i*150,c=categoryContent[key];return[card(52,y-86,491,126),text(`0${i+1}`,72,y,34,C.gold,"F2"),text(c.label.toUpperCase(),145,y+7,12,C.black,"F2"),para(c.positive,145,y-25,47,12,C.gray,18)]})].join("\n"));
 const analysis=[["01  MOMENTO ATUAL",`Seu negócio está em ${r.businessStage.toLowerCase()}. Isso mostra que existem bases construídas e espaço para avançar com mais clareza.`],["02  DESAFIO PRINCIPAL",`${bottleneck.label} apareceu como o ponto que mais precisa de atenção agora.`],["03  OPORTUNIDADE","Você não precisa mudar tudo ao mesmo tempo. Processos simples e constantes podem gerar evolução significativa."],["04  DIREÇÃO RECOMENDADA",r.primaryNeed]];pages.push([fill(C.ivory),eyebrow("Análise estratégica"),text("O QUE SUAS RESPOSTAS",52,700,25,C.black,"F2"),text("MOSTRAM SOBRE O NEGÓCIO",52,668,25,C.black,"F2"),...analysis.flatMap(([h,v],i)=>{const x=i%2?304:52,y=i<2?442:224;return[card(x,y,239,164),text(h,x+18,y+128,9,C.gold,"F2"),para(v,x+18,y+94,27,11,C.black,18)]})].join("\n"));
 pages.push([fill(C.ivory),eyebrow("Plano de ação"),text("SEUS PRÓXIMOS PASSOS",52,700,28,C.black,"F2"),text("Três ações para começar agora.",52,670,13,C.gray),...r.recommendations.slice(0,3).flatMap((v,i)=>{const y=508-i*155;return[card(52,y-85,491,130),text(`0${i+1}`,70,y,35,C.gold,"F2"),text(["AÇÃO PRIORITÁRIA","ROTINA DE EVOLUÇÃO","PRÓXIMO MARCO"][i],145,y+8,10,C.black,"F2"),para(v,145,y-25,47,12,C.gray,19)]})].join("\n"));
 const qrUrl=whatsapp.split("?")[0];pages.push([fill(C.black),logo(48,648,150),eyebrow("Seu próximo nível",610),text("SEU DIAGNÓSTICO MOSTROU",52,535,24,C.white,"F2"),text("ONDE VOCÊ ESTÁ.",52,503,24,C.goldLight,"F2"),text("Agora podemos ajudar você",52,453,20,C.white,"F2"),text("a construir o próximo nível.",52,425,20,C.white,"F2"),para("A ESADS Beauty ajuda negócios da estética a organizar sua operação, melhorar sua aquisição e construir uma estrutura mais preparada para crescer.",52,365,48,12,C.gray,19),rect(52,226,312,68,C.gold),text("QUERO CONVERSAR",75,265,12,C.black,"F2"),text("SOBRE MEU NEGÓCIO",75,246,12,C.black,"F2"),qr(qrUrl,411,218,112),text("APONTE A CÂMERA",416,194,7,C.gray,"F2"),text("WhatsApp ESADS Beauty",52,177,10,C.white,"F2")].join("\n"));
 const objects:string[]=["<< /Type /Catalog /Pages 2 0 R >>",""],pageIds:number[]=[];const imageId=19,annotationId=20;pages.forEach((commands,index)=>{const pageId=objects.length+1,contentId=pageId+1;pageIds.push(pageId);objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pdfTheme.page.width} ${pdfTheme.page.height}] /Resources << /XObject << /Logo ${imageId} 0 R >> /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >> /F2 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >> >> >> /Contents ${contentId} 0 R${index===7?` /Annots [${annotationId} 0 R]`:""} >>`);objects.push(`<< /Length ${commands.length} >>\nstream\n${commands}\nendstream`)});objects[1]=`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] /Count ${pages.length} >>`;objects.push(pngObject());objects.push(`<< /Type /Annot /Subtype /Link /Rect [52 226 364 294] /Border [0 0 0] /A << /S /URI /URI (${esc(whatsapp)}) >> >>`);let pdf="%PDF-1.4\n",offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(v=>String(v).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Uint8Array.from(pdf,v=>v.charCodeAt(0))}
export function downloadDiagnosticPdf(s:DiagnosticSubmission){const url=URL.createObjectURL(new Blob([createDiagnosticPdf(s)],{type:"application/pdf"})),a=document.createElement("a");a.href=url;a.download=`diagnostico-esads-beauty-${s.lead.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-")}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
