import{categoryContent}from"../content";import type{DiagnosticSubmission}from"../types";
const esc=(value:string)=>value.replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/[—–]/g,"-").replace(/[^\x20-\xFF]/g,"?");
export function createDiagnosticPdf(submission:DiagnosticSubmission){const pages=[
["ESADS BEAUTY","Diagnóstico do seu negócio",submission.lead.name,submission.lead.businessName,new Intl.DateTimeFormat("pt-BR").format(new Date())],
["Resultado geral",`${submission.result.totalScore}/100`,submission.result.level,`Momento: ${submission.result.businessStage}`],
["Análise por área",...Object.entries(submission.result.categoryScores).map(([key,value])=>`${categoryContent[key as keyof typeof categoryContent].label}: ${Math.round(value)}/100`)],
["Principal ponto de atenção",categoryContent[submission.result.primaryBottleneck].label,categoryContent[submission.result.primaryBottleneck].discovery],
["O que você já está fazendo bem",categoryContent[submission.result.strongestArea].positive],
["Por onde começar",...submission.result.recommendations.map((value,index)=>`${index+1}. ${value}`)],
["Seu próximo passo não precisa ser dado sozinho.","Converse com a ESADS Beauty para organizar e desenvolver seu negócio."]];
 const objects:string[]=["<< /Type /Catalog /Pages 2 0 R >>",`<< /Type /Pages /Kids [${pages.map((_,i)=>`${3+i*2} 0 R`).join(" ")}] /Count ${pages.length} >>`];pages.forEach((lines,index)=>{const pageId=3+index*2,contentId=pageId+1;objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >> >> >> /Contents ${contentId} 0 R >>`);const commands=lines.map((line,i)=>`BT /F1 ${i===0?22:14} Tf 56 ${780-i*52} Td (${esc(line)}) Tj ET`).join("\n");objects.push(`<< /Length ${commands.length} >>\nstream\n${commands}\nendstream`)});let pdf="%PDF-1.4\n",offsets=[0];objects.forEach((object,index)=>{offsets.push(pdf.length);pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(value=>String(value).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Uint8Array.from(pdf,value=>value.charCodeAt(0))}
export function downloadDiagnosticPdf(submission:DiagnosticSubmission){const url=URL.createObjectURL(new Blob([createDiagnosticPdf(submission)],{type:"application/pdf"}));const link=document.createElement("a");link.href=url;link.download=`diagnostico-${submission.lead.businessName.toLowerCase().replace(/[^a-z0-9]+/g,"-")}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
