import { designTokens } from "../../../design-system/tokens";
import { diagnosticWhatsappUrl } from "../../../config/contact";
import { categoryContent } from "../content";
import type { DiagnosticSubmission } from "../types";

const esc=(value:string)=>value.replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/[—–]/g,"-").replace(/[^\x20-\xFF]/g,"?");
const rgb=(hex:string)=>[1,3,5].map(index=>parseInt(hex.slice(index,index+2),16)/255).map(value=>value.toFixed(3)).join(" ");
const C={black:rgb(designTokens.colors.brandBlack),gold:rgb(designTokens.colors.brandGold),goldLight:rgb(designTokens.colors.brandGoldLight),ivory:rgb(designTokens.colors.brandIvory),gray:rgb(designTokens.colors.brandGray),white:"1 1 1"};
const text=(value:string,x:number,y:number,size=14,color=C.black,font="F1")=>`BT /${font} ${size} Tf ${color} rg ${x} ${y} Td (${esc(value)}) Tj ET`;
const line=(x:number,y:number,w:number,color=C.gold)=>`${color} RG 1 w ${x} ${y} m ${x+w} ${y} l S`;
const fill=(color:string)=>`${color} rg 0 0 595 842 re f`;
const wrap=(value:string,width=72)=>{const words=value.split(/\s+/),lines:string[]=[];let current="";for(const word of words){if(`${current} ${word}`.trim().length>width){lines.push(current);current=word}else current=`${current} ${word}`.trim()}if(current)lines.push(current);return lines};
const paragraph=(value:string,y:number,color=C.black,size=13)=>wrap(value).map((row,index)=>text(row,58,y-index*22,size,color)).join("\n");
const brand=(dark=false)=>[text("EB",58,760,42,C.gold,"F2"),text("ESADS BEAUTY",58,722,17,dark?C.white:C.black,"F2"),line(58,704,95)].join("\n");

export function createDiagnosticPdf(submission:DiagnosticSubmission){const r=submission.result,bottleneck=categoryContent[r.primaryBottleneck],ordered=Object.entries(r.categoryScores).sort((a,b)=>b[1]-a[1]),strong=ordered.slice(0,3).map(([key])=>categoryContent[key as keyof typeof categoryContent].positive),date=new Intl.DateTimeFormat("pt-BR").format(new Date(submission.createdAt)),whatsapp=diagnosticWhatsappUrl(submission.lead.name,r.totalScore);
 const pages:string[]=[];
 pages.push([fill(C.black),brand(true),text("DIAGNÓSTICO",58,585,34,C.white,"F2"),text("DO SEU NEGÓCIO",58,542,34,C.gold,"F2"),text("Uma análise do momento atual da sua estética",58,500,14,C.gray),line(58,465,478),text("Preparado especialmente para",58,390,12,C.gray),text(submission.lead.name,58,350,27,C.white,"F2"),text(`@${submission.lead.instagram}`,58,315,14,C.goldLight),text(submission.lead.whatsapp,58,290,13,C.gray),text(date,58,82,11,C.gray)].join("\n"));
 pages.push([fill(C.ivory),brand(),text("Seu negócio hoje",58,630,29,C.black,"F2"),text(String(r.totalScore),58,500,94,C.gold,"F2"),text("de 100",190,520,16,C.gray),text(r.level,58,450,20,C.black,"F2"),line(58,420,478),text("Principal oportunidade de melhoria",58,375,12,C.gray),text(bottleneck.label,58,340,22,C.black,"F2"),paragraph(`Pelas suas respostas, seu negócio está em ${r.level.toLowerCase()}. O próximo passo é transformar ações isoladas em uma rotina mais organizada, consistente e preparada para crescer.`,280)].join("\n"));
 const bars=ordered.map(([key,value],index)=>{const y=610-index*62,label=categoryContent[key as keyof typeof categoryContent].label;return [text(label,58,y+22,12,C.black,"F2"),text(`${Math.round(value)}/100`,475,y+22,11,C.gray),`${C.gray} rg 58 ${y} 420 7 re f`,`${C.gold} rg 58 ${y} ${Math.max(3,420*value/100)} 7 re f`].join("\n")}).join("\n");pages.push([fill(C.ivory),brand(),text("Visão por área",58,655,29,C.black,"F2"),bars].join("\n"));
 pages.push([fill(C.black),brand(true),text("O que mais merece",58,620,27,C.white,"F2"),text("sua atenção agora",58,585,27,C.white,"F2"),line(58,550,478),text(bottleneck.label,58,485,25,C.gold,"F2"),paragraph(bottleneck.discovery,425,C.white,14),paragraph("Sem atenção a esse ponto, contatos interessados podem se perder pelo caminho. A oportunidade está em criar uma rotina simples, repetível e fácil de acompanhar.",300,C.gray,13)].join("\n"));
 pages.push([fill(C.ivory),brand(),text("O que você já está",58,640,28,C.black,"F2"),text("construindo bem",58,605,28,C.black,"F2"),...strong.flatMap((value,index)=>[text(`0${index+1}`,58,510-index*125,25,C.gold,"F2"),paragraph(value,510-index*125,C.black,14)])].join("\n"));
 pages.push([fill(C.ivory),brand(),text("O que suas respostas mostram",58,640,27,C.black,"F2"),paragraph(`Seu momento atual é ${r.businessStage.toLowerCase()}. Isso mostra que existem bases construídas e espaço real para avançar com mais clareza.`,575),paragraph(`O principal desafio identificado está em ${bottleneck.label.toLowerCase()}. Esse ponto influencia a forma como novas oportunidades são aproveitadas.`,470),paragraph("A boa notícia é que você não precisa mudar tudo ao mesmo tempo. Pequenas rotinas bem escolhidas podem gerar consistência e liberar energia para crescer.",365),paragraph(`A direção recomendada agora é: ${r.primaryNeed.toLowerCase()}.`,260,C.black,15)].join("\n"));
 pages.push([fill(C.ivory),brand(),text("Seus próximos passos",58,640,29,C.black,"F2"),...r.recommendations.flatMap((value,index)=>[text(`0${index+1}`,58,535-index*145,35,C.gold,"F2"),paragraph(value,535-index*145,C.black,15)])].join("\n"));
 pages.push([fill(C.black),brand(true),text("Seu próximo passo",58,590,31,C.white,"F2"),text("não precisa ser dado sozinho.",58,548,28,C.gold,"F2"),paragraph("A ESADS Beauty pode ajudar você a organizar melhor sua operação e construir uma estrutura mais preparada para crescer.",470,C.white,15),`${C.gold} rg 58 330 350 62 re f`,text("QUERO CONVERSAR SOBRE MEU NEGÓCIO",78,354,11,C.black,"F2"),text("Link clicável para o WhatsApp",58,292,11,C.gray)].join("\n"));
 const objects:string[]=["<< /Type /Catalog /Pages 2 0 R >>",""];const pageIds:number[]=[];pages.forEach((commands,index)=>{const pageId=objects.length+1,contentId=pageId+1;pageIds.push(pageId);const annotation=index===pages.length-1?" /Annots [19 0 R]":"";objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >> /F2 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >> >> >> /Contents ${contentId} 0 R${annotation} >>`);objects.push(`<< /Length ${commands.length} >>\nstream\n${commands}\nendstream`)});objects[1]=`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] /Count ${pages.length} >>`;objects.push(`<< /Type /Annot /Subtype /Link /Rect [58 330 408 392] /Border [0 0 0] /A << /S /URI /URI (${esc(whatsapp)}) >> >>`);
 let pdf="%PDF-1.4\n",offsets=[0];objects.forEach((object,index)=>{offsets.push(pdf.length);pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(value=>String(value).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Uint8Array.from(pdf,value=>value.charCodeAt(0))}
export function downloadDiagnosticPdf(submission:DiagnosticSubmission){const url=URL.createObjectURL(new Blob([createDiagnosticPdf(submission)],{type:"application/pdf"})),link=document.createElement("a");link.href=url;link.download=`diagnostico-esads-beauty-${submission.lead.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-")}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
