import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/providers/auth-provider";

const schema = z.object({ email: z.string().email(), password: z.string() }); type Form = z.infer<typeof schema>;
export function AuthPage() {
  const auth = useAuth(); const [mode, setMode] = useState<"login" | "reset">("login"); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { email: "", password: "" } });
  async function submit(data: Form) { setMessage(""); setError(""); try { if (auth.passwordRecovery && data.password.length < 8) { setError("A nova senha deve possuir pelo menos 8 caracteres."); return; } if (auth.passwordRecovery) { await auth.updatePassword(data.password); setMessage("Senha atualizada com segurança. Você já pode continuar."); return; } if (mode === "reset") { await auth.resetPassword(data.email); setMessage("Enviamos as instruções de recuperação para o seu email."); return; } await auth.signIn(data.email, data.password); } catch { setError("Não foi possível concluir. Verifique os dados e tente novamente."); } }
  const title = auth.passwordRecovery ? "Definir nova senha" : mode === "login" ? "Acessar plataforma" : "Recuperar senha";
  return <main className="min-h-screen bg-sidebar p-4 text-white md:p-6"><div className="mx-auto grid min-h-[calc(100vh-3rem)] max-w-6xl overflow-hidden rounded-[1.75rem] bg-sidebar lg:grid-cols-[1.05fr_.95fr]"><section className="flex flex-col justify-between p-8 md:p-12"><div><div className="mb-12 flex items-center gap-3 text-xs font-semibold tracking-[.22em]"><Sparkles className="text-champagne" size={16}/> ESADS BEAUTY</div><h1 className="max-w-lg text-4xl font-semibold tracking-[-.045em] md:text-5xl">Sua operação, em um só lugar.</h1><p className="mt-5 max-w-md text-sm leading-6 text-white/55">Relacionamento, rotina e resultados organizados para decisões mais claras.</p></div><p className="mt-16 text-xs text-white/30">Hub Interno · Acesso reservado</p></section><form onSubmit={handleSubmit(submit)} className="my-auto w-full bg-background p-8 text-foreground shadow-overlay md:rounded-[1.5rem] md:p-10 lg:max-w-md"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">Use suas credenciais para continuar.</p><div className="mt-8 space-y-4">{!auth.passwordRecovery && <Input placeholder="email@esadsbeauty.com" {...register("email")}/>} {errors.email && !auth.passwordRecovery && <p className="text-sm text-red-600">Informe um email válido.</p>}{mode === "login" || auth.passwordRecovery ? <Input type="password" placeholder={auth.passwordRecovery ? "Nova senha" : "Senha"} {...register("password")}/> : null}<Button className="w-full" variant="default" disabled={isSubmitting}>{isSubmitting ? "Processando..." : "Continuar"}</Button>{message && <p className="text-sm text-emerald-700">{message}</p>}{error && <p className="text-sm text-red-700">{error}</p>}</div>{!auth.passwordRecovery && <div className="mt-6 text-right text-sm"><button type="button" onClick={() => setMode(mode === "login" ? "reset" : "login")}>{mode === "login" ? "Esqueci a senha" : "Voltar ao acesso"}</button></div>}</form></div></main>;
}
