import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/providers/auth-provider";

const schema = z.object({ email: z.string().email(), password: z.string() }); type Form = z.infer<typeof schema>;
export function AuthPage() {
  const auth = useAuth(); const [mode, setMode] = useState<"login" | "reset">("login"); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { email: "", password: "" } });
  async function submit(data: Form) { setMessage(""); setError(""); try { if (auth.passwordRecovery && data.password.length < 8) { setError("A nova senha deve possuir pelo menos 8 caracteres."); return; } if (auth.passwordRecovery) { await auth.updatePassword(data.password); setMessage("Senha atualizada com segurança. Você já pode continuar."); return; } if (mode === "reset") { await auth.resetPassword(data.email); setMessage("Enviamos as instruções de recuperação para o seu email."); return; } await auth.signIn(data.email, data.password); } catch { setError("Não foi possível concluir. Verifique os dados e tente novamente."); } }
  const title = auth.passwordRecovery ? "Definir nova senha" : mode === "login" ? "Acessar plataforma" : "Recuperar senha";
  return <main className="min-h-screen bg-[radial-gradient(circle_at_20%_20%,#F5EBD2,transparent_32%),linear-gradient(135deg,#050507,#17130b)] p-6 text-white"><div className="mx-auto grid min-h-[calc(100vh-3rem)] max-w-6xl items-center gap-10 lg:grid-cols-2"><section><div className="mb-10 inline-flex items-center gap-3 rounded-full border border-white/15 bg-white/10 px-4 py-2"><Sparkles className="text-champagne"/> ESADS BEAUTY</div><h1 className="text-5xl font-extrabold tracking-tight md:text-7xl">Hub Interno premium para crescimento organizado.</h1><p className="mt-6 max-w-xl text-lg text-white/70">Acesso reservado a integrantes convidados da organização.</p></section><form onSubmit={handleSubmit(submit)} className="glass ml-auto w-full max-w-md rounded-[2rem] border-white/15 bg-white/90 p-8 text-black"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-2 text-sm text-black/55">Autenticação e recuperação seguras via Supabase Auth.</p><div className="mt-8 space-y-4">{!auth.passwordRecovery && <Input placeholder="email@esadsbeauty.com" {...register("email")}/>} {errors.email && !auth.passwordRecovery && <p className="text-sm text-red-600">Informe um email válido.</p>}{mode === "login" || auth.passwordRecovery ? <Input type="password" placeholder={auth.passwordRecovery ? "Nova senha" : "Senha"} {...register("password")}/> : null}<Button className="w-full" variant="champagne" disabled={isSubmitting}>{isSubmitting ? "Processando..." : "Continuar"}</Button>{message && <p className="text-sm text-emerald-700">{message}</p>}{error && <p className="text-sm text-red-700">{error}</p>}</div>{!auth.passwordRecovery && <div className="mt-6 text-right text-sm"><button type="button" onClick={() => setMode(mode === "login" ? "reset" : "login")}>{mode === "login" ? "Esqueci a senha" : "Voltar ao acesso"}</button></div>}</form></div></main>;
}
