import { supabase } from "@/lib/supabase";
import type { BlogRepository } from "./repository-contract";
import type { BlogCategory, BlogPost, BlogPostInput, BlogStatus } from "./types";
const api=()=>{if(!supabase)throw new Error("O blog ainda não está configurado.");return supabase};
const fail=(error:{message:string}|null)=>{if(error)throw new Error(error.message.includes("duplicate")?"Este endereço já está em uso.":"Não foi possível concluir a operação do blog.")};
type PublicRow={id:string;title:string;slug:string;excerpt:string;content:string;cover_image_path:string|null;category_id:string|null;category_name:string|null;category_slug:string|null;author_name:string;published_at:string|null;seo_title:string|null;seo_description:string|null};
const fromPublic=(row:PublicRow):BlogPost=>({id:row.id,title:row.title,slug:row.slug,excerpt:row.excerpt,content:row.content,coverImagePath:row.cover_image_path??undefined,categoryId:row.category_id??undefined,categoryName:row.category_name??undefined,categorySlug:row.category_slug??undefined,status:"published",authorName:row.author_name,publishedAt:row.published_at??undefined,seoTitle:row.seo_title??undefined,seoDescription:row.seo_description??undefined});
const category=(row:{id:string;name:string;slug:string;created_at:string;updated_at:string}):BlogCategory=>({id:row.id,name:row.name,slug:row.slug,createdAt:row.created_at,updatedAt:row.updated_at});
export const supabaseBlogRepository:BlogRepository={
 async listPublished({query,category:categorySlug,page,pageSize}){const result=await api().rpc("public_blog_posts",{search_term:query??null,category_slug:categorySlug??null,page_offset:(page-1)*pageSize,page_limit:pageSize});fail(result.error);const value=result.data as unknown as {items:PublicRow[];total:number};return{items:(value?.items??[]).map(fromPublic),total:Number(value?.total??0)}},
 async getPublished(slug){const result=await api().rpc("public_blog_post",{post_slug:slug});fail(result.error);return result.data?fromPublic(result.data as unknown as PublicRow):null},
 async listCategories(){const result=await api().from("blog_categories").select("*").order("name");fail(result.error);return(result.data??[]).map(category)},
 async listManaged(){const client=api();const [posts,categories,profiles]=await Promise.all([client.from("blog_posts").select("*").is("deleted_at",null).order("updated_at",{ascending:false}),client.from("blog_categories").select("*"),client.from("profiles").select("id,name")]);[posts,categories,profiles].forEach(result=>fail(result.error));const categoryMap=new Map((categories.data??[]).map(row=>[row.id,row]));const authorMap=new Map((profiles.data??[]).map(row=>[row.id,row.name]));return(posts.data??[]).map(row=>{const selected=row.category_id?categoryMap.get(row.category_id):undefined;return{id:row.id,title:row.title,slug:row.slug,excerpt:row.excerpt,content:row.content,coverImagePath:row.cover_image_path??undefined,categoryId:row.category_id??undefined,categoryName:selected?.name,categorySlug:selected?.slug,status:row.status,authorId:row.author_id,authorName:authorMap.get(row.author_id)??"Equipe ESADS Beauty",publishedAt:row.published_at??undefined,seoTitle:row.seo_title??undefined,seoDescription:row.seo_description??undefined,createdAt:row.created_at,updatedAt:row.updated_at}})},
 async save(input:BlogPostInput){const values={title:input.title,slug:input.slug,excerpt:input.excerpt,content:input.content,cover_image_path:input.coverImagePath??null,category_id:input.categoryId??null,seo_title:input.seoTitle||null,seo_description:input.seoDescription||null};if(input.id){const result=await api().from("blog_posts").update(values).eq("id",input.id).select("id").single();fail(result.error)}else{const organization=await api().rpc("current_organization_id");fail(organization.error);const user=await api().auth.getUser();if(!user.data.user)throw new Error("Sua sessão expirou.");const result=await api().from("blog_posts").insert({...values,organization_id:organization.data!,author_id:user.data.user.id,status:"draft"}).select("id").single();fail(result.error);input={...input,id:result.data?.id}}const post=(await this.listManaged()).find(item=>item.id===input.id);if(!post)throw new Error("Não foi possível carregar o artigo salvo.");return post},
 async setStatus(id:string,status:BlogStatus){const result=await api().from("blog_posts").update({status,published_at:status==="published"?new Date().toISOString():null}).eq("id",id);fail(result.error)},
 async remove(id){const result=await api().from("blog_posts").update({deleted_at:new Date().toISOString()}).eq("id",id);fail(result.error)},
 async uploadCover(file){if(file.size>5*1024*1024)throw new Error("A imagem deve ter no máximo 5 MB.");if(!["image/jpeg","image/png","image/webp","image/avif"].includes(file.type))throw new Error("Use uma imagem JPG, PNG, WebP ou AVIF.");const extension=file.name.split(".").pop()?.toLowerCase()??"webp",path=`covers/${crypto.randomUUID()}.${extension}`;const result=await api().storage.from("blog").upload(path,file,{contentType:file.type,upsert:false});fail(result.error);return path},
 coverUrl(path){return path?api().storage.from("blog").getPublicUrl(path).data.publicUrl:undefined},
};
