import { supabase } from "@/lib/supabase";
import type { BlogRepository } from "./repository-contract";
import type { BlogCategory, BlogPost, BlogPostInput, BlogStatus } from "./types";
const api=()=>{if(!supabase)throw new Error("O blog ainda não está configurado.");return supabase};
type BlogApiError={code?:string;message:string;details?:string;hint?:string;statusCode?:string|number};
const fail=(error:BlogApiError|null,context="operação")=>{if(!error)return;if(import.meta.env.DEV)console.error(`[Blog ${context}]`,{code:error.code,message:error.message,details:error.details,hint:error.hint});const message=error.message.toLowerCase(),code=error.code??String(error.statusCode??"");if(code==="23505"||message.includes("duplicate"))throw new Error("Este endereço já está em uso.");if(code==="42501"||message.includes("row-level security")||message.includes("permission")||message.includes("denied"))throw new Error("Você não possui permissão para realizar esta ação.");if(code==="42P01"||code==="42883"||code==="PGRST202"||code==="PGRST205"||message.includes("schema cache"))throw new Error("O módulo Blog ainda não foi configurado no banco.");if(context==="upload"&&(code==="404"||message.includes("bucket not found")||message.includes("not found")))throw new Error("O armazenamento de imagens do Blog ainda não foi configurado.");if(code==="23503"||code==="22P02")throw new Error("A categoria selecionada é inválida.");if(code==="23514")throw new Error("Revise os campos obrigatórios do artigo.");throw new Error("Não foi possível concluir a operação do Blog.")};
type PublicRow={id:string;title:string;slug:string;excerpt:string;content:string;cover_image_path:string|null;category_id:string|null;category_name:string|null;category_slug:string|null;author_name:string;published_at:string|null;seo_title:string|null;seo_description:string|null};
const fromPublic=(row:PublicRow):BlogPost=>({id:row.id,title:row.title,slug:row.slug,excerpt:row.excerpt,content:row.content,coverImagePath:row.cover_image_path??undefined,categoryId:row.category_id??undefined,categoryName:row.category_name??undefined,categorySlug:row.category_slug??undefined,status:"published",authorName:row.author_name,publishedAt:row.published_at??undefined,seoTitle:row.seo_title??undefined,seoDescription:row.seo_description??undefined});
const category=(row:{id:string;name:string;slug:string;created_at:string;updated_at:string}):BlogCategory=>({id:row.id,name:row.name,slug:row.slug,createdAt:row.created_at,updatedAt:row.updated_at});
export const supabaseBlogRepository:BlogRepository={
 async listPublished({query,category:categorySlug,page,pageSize}){const result=await api().rpc("public_blog_posts",{search_term:query??null,category_slug:categorySlug??null,page_offset:(page-1)*pageSize,page_limit:pageSize});fail(result.error);const value=result.data as unknown as {items:PublicRow[];total:number};return{items:(value?.items??[]).map(fromPublic),total:Number(value?.total??0)}},
 async getPublished(slug){const result=await api().rpc("public_blog_post",{post_slug:slug});fail(result.error);return result.data?fromPublic(result.data as unknown as PublicRow):null},
 async listCategories(){const result=await api().from("blog_categories").select("*").order("name");fail(result.error);return(result.data??[]).map(category)},
 async listManaged(){const client=api();const [posts,categories,profiles]=await Promise.all([client.from("blog_posts").select("*").is("deleted_at",null).order("updated_at",{ascending:false}),client.from("blog_categories").select("*"),client.from("profiles").select("id,name")]);[posts,categories,profiles].forEach(result=>fail(result.error));const categoryMap=new Map((categories.data??[]).map(row=>[row.id,row]));const authorMap=new Map((profiles.data??[]).map(row=>[row.id,row.name]));return(posts.data??[]).map(row=>{const selected=row.category_id?categoryMap.get(row.category_id):undefined;return{id:row.id,title:row.title,slug:row.slug,excerpt:row.excerpt,content:row.content,coverImagePath:row.cover_image_path??undefined,categoryId:row.category_id??undefined,categoryName:selected?.name,categorySlug:selected?.slug,status:row.status,authorId:row.author_id,authorName:authorMap.get(row.author_id)??"Equipe ESADS Beauty",publishedAt:row.published_at??undefined,seoTitle:row.seo_title??undefined,seoDescription:row.seo_description??undefined,createdAt:row.created_at,updatedAt:row.updated_at}})},
 async save(input:BlogPostInput){const result=await api().rpc("save_blog_post",{post_id:input.id?.trim()||null,post_title:input.title,post_slug:input.slug,post_excerpt:input.excerpt,post_content:input.content,post_cover_image_path:input.coverImagePath?.trim()||null,post_category_id:input.categoryId?.trim()||null,post_seo_title:input.seoTitle?.trim()||null,post_seo_description:input.seoDescription?.trim()||null});fail(result.error,"salvar");const savedId=result.data;const post=(await this.listManaged()).find(item=>item.id===savedId);if(!post)throw new Error("Não foi possível carregar o artigo salvo.");return post},
 async setStatus(id:string,status:BlogStatus){const result=await api().rpc("set_blog_post_status",{post_id:id,next_status:status});fail(result.error,"publicar")},
 async remove(id){const result=await api().from("blog_posts").update({deleted_at:new Date().toISOString()}).eq("id",id);fail(result.error)},
 async uploadCover(file){if(file.size>5*1024*1024)throw new Error("A imagem deve ter no máximo 5 MB.");const extensions:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};const extension=extensions[file.type];if(!extension)throw new Error("Use uma imagem JPG, PNG ou WebP.");const session=await api().auth.getSession();if(!session.data.session)throw new Error("Sua sessão expirou. Entre novamente antes de enviar a imagem.");const organization=await api().rpc("current_organization_id");fail(organization.error,"organização");if(!organization.data)throw new Error("Sua organização não está ativa.");const path=`${organization.data}/covers/${crypto.randomUUID()}.${extension}`;const result=await api().storage.from("blog").upload(path,file,{contentType:file.type,cacheControl:"31536000",upsert:false});fail(result.error,"upload");return path},
 coverUrl(path){return path?api().storage.from("blog").getPublicUrl(path).data.publicUrl:undefined},
};
