export type AttributionModel = "first_touch" | "last_touch";
export type MarketingChannel = "paid_social" | "paid_search" | "organic_social" | "organic_search" | "referral" | "outbound" | "direct" | "partner" | "other";

export type MarketingSource = { id: string; organizationId: string; name: string; slug: string; channel: MarketingChannel; platform: string; type: string; isPaid: boolean; isActive: boolean; createdAt: string; updatedAt: string };
export type MarketingCampaign = { id: string; organizationId: string; sourceId: string; provider: string; externalId?: string; name: string; objective?: string; status: "active" | "paused" | "completed" | "archived"; startDate?: string; endDate?: string; budget?: number; externalAccountId?: string; createdAt: string; updatedAt: string };
export type MarketingAdGroup = { id: string; organizationId: string; campaignId: string; externalId?: string; name: string; status: string; createdAt: string; updatedAt: string };
export type MarketingAd = { id: string; organizationId: string; campaignId: string; adGroupId?: string; externalId?: string; name: string; status: string; creativeName?: string; destinationUrl?: string; createdAt: string; updatedAt: string };
export type LeadAcquisition = { id: string; organizationId: string; companyId: string; contactId?: string; opportunityId?: string; sourceId?: string; campaignId?: string; adGroupId?: string; adId?: string; provider?: string; externalEventId?: string; utmSource?: string; utmMedium?: string; utmCampaign?: string; utmContent?: string; utmTerm?: string; landingPage?: string; referrer?: string; gclid?: string; fbclid?: string; utmId?: string; capturedAt: string; isFirstTouch: boolean; isLastTouch: boolean; metadata: Record<string, string | number | boolean | null>; createdAt: string };
export type MarketingSpend = { id: string; organizationId: string; provider: string; sourceId?: string; campaignId?: string; adGroupId?: string; adId?: string; externalEntityId?: string; date: string; amount: number; currency: string; impressions: number; reach: number; clicks: number; externalConversions: number; createdAt: string; updatedAt: string };
export type MarketingConnection = { id: string; organizationId: string; provider: string; externalAccountId: string; name: string; status: "connected" | "disconnected" | "error" | "syncing"; lastSyncAt?: string; lastSuccessfulSyncAt?: string; syncError?: string; createdAt: string; updatedAt: string };
export type MarketingData = { sources: MarketingSource[]; campaigns: MarketingCampaign[]; adGroups: MarketingAdGroup[]; ads: MarketingAd[]; acquisitions: LeadAcquisition[]; spend: MarketingSpend[]; connections: MarketingConnection[] };
export type SourceInput = Pick<MarketingSource, "name" | "slug" | "channel" | "platform" | "type" | "isPaid">;
export type CampaignInput = Pick<MarketingCampaign, "sourceId" | "provider" | "name" | "status"> & Partial<Pick<MarketingCampaign, "externalId" | "objective" | "startDate" | "endDate" | "budget" | "externalAccountId">>;
export type AcquisitionInput = Omit<LeadAcquisition, "id" | "organizationId" | "isFirstTouch" | "isLastTouch" | "createdAt" | "metadata"> & { metadata?: LeadAcquisition["metadata"] };
export type SpendInput = Omit<MarketingSpend, "id" | "organizationId" | "createdAt" | "updatedAt">;
