import { useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, BriefcaseBusiness, Search, UserRoundCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { EmptyState, Skeleton } from "@/shared/components/feedback/states";
import { PageContainer } from "@/shared/components/layout/page-container";
import { PageHeader } from "@/shared/components/layout/page-header";
import { useCrmData } from "@/modules/crm/hooks";
import { formatDateTime } from "@/modules/crm/utils/formatters";
import { CustomerStatusBadge } from "./components/customer-workspace";
import { useCustomerData } from "./hooks";
import type { CustomerStatus } from "./types";

export function CustomersPage(){ const navigate=useNavigate();const crm=useCrmData();const customer=useCustomerData();const [search,setSearch]=useState("");const [status,setStatus]=useState<CustomerStatus|"all">("all");
 const rows=useMemo(()=>customer.data?.accounts.map((account)=>({account,company:crm.data?.companies.find((item)=>item.id===account.companyId),services:customer.data.customerServices.filter((item)=>item.customerAccountId===account.id&&item.status==="active"),onboarding:customer.data.onboardings.find((item)=>item.customerAccountId===account.id&&!["completed","cancelled"].includes(item.status)),contract:customer.data.contracts.find((item)=>item.customerAccountId===account.id&&["signed","active"].includes(item.status))})).filter((row)=>row.company&&(status==="all"||row.account.status===status)&&`${row.company.fantasyName} ${row.company.email??""} ${row.company.whatsapp??""} ${row.company.instagram??""}`.toLowerCase().includes(search.toLowerCase()))??[],[customer.data,crm.data,search,status]);
 if(customer.isLoading||crm.isLoading)return <PageContainer><Skeleton className="h-32"/><Skeleton className="h-96"/></PageContainer>;
 const active=customer.data?.accounts.filter((item)=>item.status==="active").length??0;const onboarding=customer.data?.accounts.filter((item)=>item.status==="onboarding").length??0;const overdue=customer.data?.onboardings.filter((item)=>item.dueAt&&new Date(item.dueAt)<new Date()&&!['completed','cancelled'].includes(item.status)).length??0;const expiring=customer.data?.contracts.filter((item)=>item.endDate&&new Date(item.endDate).getTime()>=Date.now()&&new Date(item.endDate).getTime()<=Date.now()+90*86400000&&!['expired','cancelled'].includes(item.status)).length??0;
 const metrics=[{label:"Clientes ativos",value:active,Icon:UserRoundCheck},{label:"Em onboarding",value:onboarding,Icon:BriefcaseBusiness},{label:"Onboardings atrasados",value:overdue,Icon:AlertTriangle},{label:"Contratos em 90 dias",value:expiring,Icon:AlertTriangle}];
 return <PageContainer><PageHeader title="Clientes" description="Relacionamentos, serviços e próximos passos."/><div className="grid gap-4 min-[430px]:grid-cols-2 lg:grid-cols-4">{metrics.map(({label,value,Icon})=><Card key={label}><CardContent className="flex items-center justify-between"><div><p className="text-base text-muted-foreground md:text-sm">{label}</p><p className="mt-1 text-4xl font-semibold md:text-2xl">{value}</p></div><Icon className="text-muted-foreground/45" size={26}/></CardContent></Card>)}</div><Card><CardContent className="p-5"><div className="mb-5 grid gap-3 md:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-3 top-3 text-muted-foreground" size={17}/><Input className="pl-10" aria-label="Buscar clientes" placeholder="Empresa, email, WhatsApp ou Instagram" value={search} onChange={(event)=>setSearch(event.target.value)}/></label><Select aria-label="Filtrar por status" value={status} onChange={(event)=>setStatus(event.target.value as CustomerStatus|"all")}><option value="all">Todos os status</option><option value="active">Ativos</option><option value="onboarding">Em onboarding</option><option value="paused">Pausados</option><option value="cancelled">Cancelados</option></Select></div>{rows.length===0?<EmptyState title="Nenhum relacionamento de cliente encontrado" description="Clientes são ativados a partir de empresas e oportunidades ganhas."/>:<div className="divide-y">{rows.map(({account,company,services,onboarding:ob,contract})=><button key={account.id} className="grid min-h-24 w-full gap-3 py-5 text-left text-base hover:bg-muted/40 md:min-h-0 md:grid-cols-[1.5fr_1fr_1fr_1fr_auto] md:items-center md:py-4 md:text-sm" onClick={()=>navigate(`/crm/companies/${account.companyId}?customer=1`)}><div><b>{company!.fantasyName}</b><p className="mt-1 text-sm text-muted-foreground md:text-xs">Cliente desde {formatDateTime(account.clientSince)}</p></div><CustomerStatusBadge account={account}/><span className="text-sm">{services.length} serviço(s) ativo(s)</span><div className="text-sm"><p>{contract?`Contrato ${contract.contractNumber}`:"Sem contrato ativo"}</p><p className="text-xs text-muted-foreground">{ob?ob.title:"Sem onboarding ativo"}</p></div><ArrowRight size={17}/></button>)}</div>}</CardContent></Card></PageContainer>;
}
