import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/shared/components/feedback/toast";
import { customerDataSource } from "./data-source";
import { customerKeys } from "./query-keys";
import { useAppState } from "@/shared/state/app-state-context";

export function useCustomerData() { const{organizationId}=useAppState();return useQuery({ queryKey:[...customerKeys.lists(),organizationId], queryFn:customerDataSource.list, enabled:Boolean(organizationId),staleTime:30_000 }); }
export function useCustomerByCompany(companyId:string) { const query=useCustomerData(); const account=query.data?.accounts.find((item)=>item.companyId===companyId); return { ...query, account, services:query.data?.customerServices.filter((item)=>item.customerAccountId===account?.id)??[], onboardings:query.data?.onboardings.filter((item)=>item.customerAccountId===account?.id)??[], contracts:query.data?.contracts.filter((item)=>item.customerAccountId===account?.id)??[] }; }
export function useCustomerActions(){ const client=useQueryClient(); const {notify}=useToast(); const refresh=()=>client.invalidateQueries({queryKey:customerKeys.all}); const onError=(error:Error)=>notify({title:"Não foi possível concluir",description:error.message}); const success=(title:string)=>()=>{notify({title});void refresh();}; return {
  createService:useMutation({mutationFn:customerDataSource.createService,onSuccess:success("Serviço cadastrado."),onError}), addCustomerService:useMutation({mutationFn:customerDataSource.addCustomerService,onSuccess:success("Serviço contratado registrado."),onError}), startOnboarding:useMutation({mutationFn:customerDataSource.startOnboarding,onSuccess:success("Onboarding iniciado."),onError}), addOnboardingStep:useMutation({mutationFn:customerDataSource.addOnboardingStep,onSuccess:success("Etapa adicionada."),onError}), completeOnboardingStep:useMutation({mutationFn:customerDataSource.completeOnboardingStep,onSuccess:success("Etapa concluída."),onError}), createContract:useMutation({mutationFn:customerDataSource.createContract,onSuccess:success("Contrato registrado."),onError}), activateContract:useMutation({mutationFn:customerDataSource.activateContract,onSuccess:success("Contrato ativado."),onError}), setCustomerStatus:useMutation({mutationFn:({id,status,reason}:{id:string;status:"active"|"paused"|"cancelled";reason?:string})=>customerDataSource.setCustomerStatus(id,status,reason),onSuccess:success("Status do cliente atualizado."),onError}) }; }
