import { supabase } from "@/lib/supabase";
import type { Database } from "@/shared/types/database";
import type { CustomerRepository } from "./repository-contract";
import type { Contract, CustomerAccount, CustomerService, Onboarding, OnboardingStep, Service } from "./types";

type Tables = Database["public"]["Tables"];
const api = () => { if (!supabase) throw new Error("Supabase não configurado."); return supabase; };
const fail = (error: { message: string } | null) => { if (error) { console.error("[Customers]", error); throw new Error("Não foi possível concluir esta ação. Tente novamente."); } };
const optional = <T extends string | number>(value: T | null): T | undefined => value ?? undefined;
const account = (row: Tables["customer_accounts"]["Row"]): CustomerAccount => ({ id: row.id, organizationId: row.organization_id, companyId: row.company_id, status: row.status, clientSince: row.client_since, ownerId: optional(row.owner_id), successOwnerId: optional(row.success_owner_id), sourceOpportunityId: optional(row.source_opportunity_id), cancellationReason: optional(row.cancellation_reason), cancellationNotes: optional(row.cancellation_notes), cancelledAt: optional(row.cancelled_at), createdAt: row.created_at, updatedAt: row.updated_at });
const service = (row: Tables["services"]["Row"]): Service => ({ id: row.id, organizationId: row.organization_id, name: row.name, description: optional(row.description), category: optional(row.category), defaultPrice: optional(row.default_price), billingType: row.billing_type, isActive: row.is_active, createdAt: row.created_at, updatedAt: row.updated_at });
const customerService = (row: Tables["customer_services"]["Row"]): CustomerService => ({ id: row.id, organizationId: row.organization_id, customerAccountId: row.customer_account_id, serviceId: row.service_id, sourceOpportunityId: optional(row.source_opportunity_id), status: row.status, startDate: optional(row.start_date), endDate: optional(row.end_date), agreedPrice: optional(row.agreed_price), billingType: row.billing_type, billingInterval: row.billing_interval, ownerId: optional(row.owner_id), notes: optional(row.notes), createdAt: row.created_at, updatedAt: row.updated_at, cancelledAt: optional(row.cancelled_at) });
const onboarding = (row: Tables["onboardings"]["Row"]): Onboarding => ({ id: row.id, organizationId: row.organization_id, customerAccountId: row.customer_account_id, customerServiceId: optional(row.customer_service_id), sourceOpportunityId: optional(row.source_opportunity_id), title: row.title, status: row.status, ownerId: optional(row.owner_id), startedAt: optional(row.started_at), dueAt: optional(row.due_at), completedAt: optional(row.completed_at), createdAt: row.created_at, updatedAt: row.updated_at });
const step = (row: Tables["onboarding_steps"]["Row"]): OnboardingStep => ({ id: row.id, organizationId: row.organization_id, onboardingId: row.onboarding_id, taskId: optional(row.task_id), title: row.title, description: optional(row.description), position: row.position, status: row.status, assignedTo: optional(row.assigned_to), dueAt: optional(row.due_at), completedAt: optional(row.completed_at), blockedBy: row.blocked_by ?? undefined, blockedReason: optional(row.blocked_reason), createdAt: row.created_at, updatedAt: row.updated_at });
const contract = (row: Tables["contracts"]["Row"], ids: string[] = []): Contract => ({ id: row.id, organizationId: row.organization_id, customerAccountId: row.customer_account_id, sourceOpportunityId: optional(row.source_opportunity_id), title: row.title, status: row.status, contractNumber: row.contract_number, startDate: row.start_date, endDate: optional(row.end_date), signedAt: optional(row.signed_at), value: optional(row.value), billingType: row.billing_type, billingInterval: row.billing_interval, autoRenew: row.auto_renew, noticeDays: row.notice_days, ownerId: optional(row.owner_id), notes: optional(row.notes), customerServiceIds: ids, createdAt: row.created_at, updatedAt: row.updated_at, cancelledAt: optional(row.cancelled_at) });

async function organizationId() { const { data, error } = await api().rpc("current_organization_id"); fail(error); if (!data) throw new Error("Organização não encontrada."); return data; }
export const supabaseCustomerRepository: CustomerRepository = {
  async list() { const client = api(); const [a,s,cs,o,st,c,links] = await Promise.all([client.from("customer_accounts").select("*").order("client_since",{ascending:false}), client.from("services").select("*").eq("is_active",true).order("name"), client.from("customer_services").select("*").is("deleted_at",null), client.from("onboardings").select("*").is("deleted_at",null), client.from("onboarding_steps").select("*").order("position"), client.from("contracts").select("*").is("deleted_at",null).order("created_at",{ascending:false}), client.from("contract_services").select("*")]); [a,s,cs,o,st,c,links].forEach((result) => fail(result.error)); return { accounts:(a.data??[]).map(account), services:(s.data??[]).map(service), customerServices:(cs.data??[]).map(customerService), onboardings:(o.data??[]).map(onboarding), steps:(st.data??[]).map(step), contracts:(c.data??[]).map((row) => contract(row,(links.data??[]).filter((link)=>link.contract_id===row.id).map((link)=>link.customer_service_id))) }; },
  async createService(input) { const result=await api().from("services").insert({ organization_id:await organizationId(), name:input.name, description:input.description, category:input.category, default_price:input.defaultPrice, billing_type:input.billingType, is_active:true }).select("*").single(); fail(result.error); return service(result.data!); },
  async addCustomerService(input) { const result=await api().from("customer_services").insert({ organization_id:await organizationId(), customer_account_id:input.customerAccountId, service_id:input.serviceId, source_opportunity_id:input.sourceOpportunityId, start_date:input.startDate, end_date:input.endDate, agreed_price:input.agreedPrice, billing_type:input.billingType, billing_interval:input.billingInterval, owner_id:input.ownerId, notes:input.notes, status:"pending" }).select("*").single(); fail(result.error); return customerService(result.data!); },
  async startOnboarding(input) { const result=await api().from("onboardings").insert({ organization_id:await organizationId(), customer_account_id:input.customerAccountId, customer_service_id:input.customerServiceId, source_opportunity_id:input.sourceOpportunityId, title:input.title, owner_id:input.ownerId, due_at:input.dueAt, status:"in_progress", started_at:new Date().toISOString() }).select("*").single(); fail(result.error); return onboarding(result.data!); },
  async addOnboardingStep(input) { const data=await this.list(); const position=data.steps.filter((item)=>item.onboardingId===input.onboardingId).length+1; const result=await api().from("onboarding_steps").insert({ organization_id:await organizationId(), onboarding_id:input.onboardingId, title:input.title, description:input.description, position, assigned_to:input.assignedTo, due_at:input.dueAt, blocked_by:input.blockedBy, status:"pending" }).select("*").single(); fail(result.error); return step(result.data!); },
  async completeOnboardingStep(id) { const result=await api().rpc("complete_onboarding_step",{target_step_id:id}); fail(result.error); return step(result.data!); },
  async createContract(input) { const org=await organizationId(); const number=`CTR-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`; const result=await api().from("contracts").insert({ organization_id:org, customer_account_id:input.customerAccountId, source_opportunity_id:input.sourceOpportunityId, title:input.title, contract_number:number, start_date:input.startDate, end_date:input.endDate, value:input.value, billing_type:input.billingType, billing_interval:input.billingInterval, auto_renew:input.autoRenew, notice_days:input.noticeDays, owner_id:input.ownerId, notes:input.notes, status:"draft" }).select("*").single(); fail(result.error); for(const customerServiceId of input.customerServiceIds){ const link=await api().from("contract_services").insert({contract_id:result.data!.id,customer_service_id:customerServiceId}); fail(link.error); } return contract(result.data!,input.customerServiceIds); },
  async activateContract(id) { const result=await api().from("contracts").update({status:"active",signed_at:new Date().toISOString()}).eq("id",id).select("*").single(); fail(result.error); return contract(result.data!); },
  async setCustomerStatus(id,status,reason) { const result=await api().from("customer_accounts").update({status,cancellation_reason:status==="cancelled"?reason:null,cancelled_at:status==="cancelled"?new Date().toISOString():null}).eq("id",id); fail(result.error); },
};
