import { useEffect, useMemo, useState } from "react";
import { Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { PageContainer } from "@/shared/components/layout/page-container";
import { PageHeader } from "@/shared/components/layout/page-header";
import { Modal } from "@/shared/components/overlays/modal";
import { platformRepository } from "./repository";
import type { PlatformOrganization, PlatformSnapshot, ProvisionOrganizationInput, SubscriptionStatus } from "./types";

const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);
const date = (value?: string) => value ? new Intl.DateTimeFormat("pt-BR").format(new Date(value)) : "—";
const emptyForm: ProvisionOrganizationInput = { organizationName: "", ownerName: "", ownerEmail: "", ownerWhatsapp: "", pipelineName: "Pipeline Comercial" };
const statuses: Record<SubscriptionStatus, { label: string; color: string }> = { active:{label:"Ativa",color:"bg-emerald-50 text-emerald-800"},pending:{label:"Pendente",color:"bg-amber-50 text-amber-900"},past_due:{label:"Em atraso",color:"bg-amber-50 text-amber-900"},suspended:{label:"Suspensa",color:"bg-red-50 text-red-800"},cancelled:{label:"Cancelada",color:"bg-red-50 text-red-800"} };

export function PlatformPage() {
  const [data, setData] = useState<PlatformSnapshot>(); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [saving, setSaving] = useState("");
  const [provisionOpen, setProvisionOpen] = useState(false); const [provisioning, setProvisioning] = useState(false); const [form, setForm] = useState<ProvisionOrganizationInput>(emptyForm);
  const [selected, setSelected] = useState<PlatformOrganization>(); const [filter, setFilter] = useState<"all"|SubscriptionStatus>("all"); const [dueDate, setDueDate] = useState("");
  const load = () => platformRepository.snapshot().then((snapshot) => { setData(snapshot); setError(""); }).catch((reason: Error) => setError(reason.message));
  useEffect(() => { void load(); }, []);
  const founders = data?.plans.find((plan) => plan.slug === "fundadores" && plan.isActive);
  const visible = useMemo(() => data?.organizations.filter((organization) => filter === "all" || organization.subscription?.status === filter) ?? [], [data, filter]);
  const openProvisioning = () => { setForm({ ...emptyForm, planId: founders?.id }); setError(""); setSuccess(""); setProvisionOpen(true); };
  const provision = async (event: React.FormEvent) => { event.preventDefault(); setProvisioning(true); setError(""); try { const result = await platformRepository.provision(form); setProvisionOpen(false); setSuccess(result.message); await load(); } catch (reason) { setError((reason as Error).message); } finally { setProvisioning(false); } };
  const act = async (key: string, action: () => Promise<void>, message: string) => { setSaving(key); setError(""); try { await action(); setSuccess(message); setSelected(undefined); await load(); } catch(reason) { setError((reason as Error).message); } finally { setSaving(""); } };

  if (!data) return <PageContainer><p className="text-muted-foreground">{error || "Carregando gestão da plataforma..."}</p></PageContainer>;
  return <PageContainer>
    <PageHeader title="Administração da plataforma" description="Clientes, planos e situação financeira das assinaturas." actions={<Button onClick={openProvisioning}><Plus size={18}/>Nova organização</Button>} />
    {success && <p role="status" className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{success}</p>}{error && !provisionOpen && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-destructive">{error}</p>}
    <section aria-label="Indicadores de assinatura" className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Clientes ativos" value={String(data.metrics.activeCustomers)}/><Metric label="MRR atual" value={money(data.metrics.mrrCents)}/><Metric label="Em atraso" value={String(data.metrics.pastDue)}/><Metric label="Suspensos" value={String(data.metrics.suspended)}/></section>
    <div className="grid gap-5 xl:grid-cols-[.7fr_1.3fr]">
      <section className="space-y-3"><h2 className="text-lg font-semibold">Planos</h2>{data.plans.map((plan) => <Card key={plan.id}><CardHeader><div className="flex items-center justify-between"><CardTitle>{plan.name}</CardTitle><Badge>{plan.isActive ? "Ativo" : "Técnico"}</Badge></div></CardHeader><CardContent><p className="text-2xl font-semibold">{money(plan.priceCents)}<span className="text-sm font-normal text-muted-foreground">/mês</span></p><p className="mt-1 text-sm text-muted-foreground">Cobrança {plan.billingMode === "manual" ? "manual" : "automática"}</p></CardContent></Card>)}</section>
      <section className="space-y-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-lg font-semibold">Organizações</h2><Select className="sm:w-48" value={filter} onChange={(e)=>setFilter(e.target.value as typeof filter)}><option value="all">Todas</option>{Object.entries(statuses).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</Select></div>{visible.map((organization) => { const subscription=organization.subscription;return <Card key={organization.id}><CardContent className="pt-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{organization.name}</p>{subscription&&<span className={`rounded-lg px-2 py-1 text-xs font-semibold ${statuses[subscription.status].color}`}>{statuses[subscription.status].label}</span>}</div><p className="mt-1 text-sm text-muted-foreground">{organization.ownerName || "Responsável não informado"}{organization.ownerEmail ? ` · ${organization.ownerEmail}` : ""}</p><p className="mt-3 font-medium">{organization.planName ?? "Sem plano"} · {money(subscription?.priceCents ?? 0)}/mês</p><div className="mt-2 grid gap-1 text-sm text-muted-foreground sm:grid-cols-2"><span>Próximo vencimento: {date(subscription?.nextDueAt)}</span><span>Último pagamento: {date(subscription?.lastPaymentAt)}</span><span>Pagamento: {subscription?.paymentMethod === "manual" ? "Manual" : subscription?.paymentMethod ?? "—"}</span><span>Criada em: {date(organization.createdAt)}</span>{Boolean(subscription?.daysOverdue)&&<span className="font-medium text-amber-800">{subscription?.daysOverdue} dias em atraso</span>}</div></div><Button variant="outline" onClick={()=>{setSelected(organization);setDueDate(subscription?.nextDueAt?.slice(0,10)??"");}}>Gerenciar</Button></div></CardContent></Card>;})}</section>
    </div>
    <Modal open={Boolean(selected)} title={`Assinatura · ${selected?.name ?? ""}`} onClose={()=>!saving&&setSelected(undefined)}>{selected?.subscription&&<div className="space-y-5"><div className="grid gap-3 rounded-xl bg-muted p-4 text-sm sm:grid-cols-2"><p><span className="text-muted-foreground">Status</span><b className="block">{statuses[selected.subscription.status].label}</b></p><p><span className="text-muted-foreground">Tolerância até</span><b className="block">{date(selected.subscription.gracePeriodEndsAt)}</b></p></div><Field label="Plano atual"><div className="flex gap-2"><Select value={selected.planId ?? ""} onChange={(e) => setSelected({ ...selected, planId: e.target.value })}>{data.plans.filter((plan) => plan.isActive).map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</Select><Button variant="outline" disabled={!selected.planId || Boolean(saving)} onClick={() => act("plan", () => platformRepository.assignPlan(selected.id, selected.planId!), "Plano atualizado.")}>Aplicar</Button></div></Field><Field label="Novo vencimento"><div className="flex gap-2"><Input type="date" value={dueDate} onChange={(e)=>setDueDate(e.target.value)}/><Button variant="outline" disabled={!dueDate||Boolean(saving)} onClick={()=>act("due",()=>platformRepository.changeDueDate(selected.subscription!.id,new Date(`${dueDate}T12:00:00`).toISOString()),"Vencimento atualizado.")}>Alterar</Button></div></Field><div className="flex flex-wrap gap-2"><Button disabled={Boolean(saving)||selected.subscription.status==="cancelled"} onClick={()=>act("paid",()=>platformRepository.markPaid(selected.subscription!.id),"Pagamento registrado.")}>Marcar como pago</Button>{selected.subscription.status==="suspended"||selected.subscription.status==="past_due"||selected.subscription.status==="pending"?<Button variant="outline" disabled={Boolean(saving)} onClick={()=>act("reactivate",()=>platformRepository.reactivate(selected.subscription!.id),"Assinatura reativada.")}>Reativar</Button>:<Button variant="outline" disabled={Boolean(saving)||selected.subscription.status==="cancelled"} onClick={()=>act("suspend",()=>platformRepository.suspend(selected.subscription!.id),"Assinatura suspensa.")}>Suspender</Button>}<Button variant="ghost" disabled={Boolean(saving)||selected.subscription.status==="cancelled"} onClick={()=>{if(confirm("Cancelar esta assinatura? Os dados do cliente serão preservados."))void act("cancel",()=>platformRepository.cancel(selected.subscription!.id),"Assinatura cancelada.");}}>Cancelar assinatura</Button></div><p className="text-xs text-muted-foreground">As ações financeiras não removem dados nem alteram o acesso do tenant nesta fase.</p></div>}</Modal>
    <Modal open={provisionOpen} title="Nova organização" onClose={() => !provisioning && setProvisionOpen(false)}><form className="grid gap-4 md:grid-cols-2" onSubmit={provision}><Field label="Nome da empresa"><Input required value={form.organizationName} onChange={(e) => setForm({ ...form, organizationName: e.target.value })}/></Field><Field label="Nome do responsável"><Input required value={form.ownerName} onChange={(e) => setForm({ ...form, ownerName: e.target.value })}/></Field><Field label="E-mail do responsável"><Input required type="email" value={form.ownerEmail} onChange={(e) => setForm({ ...form, ownerEmail: e.target.value })}/></Field><Field label="WhatsApp do responsável"><Input required type="tel" value={form.ownerWhatsapp} onChange={(e) => setForm({ ...form, ownerWhatsapp: e.target.value })}/></Field><Field label="Plano"><Select required value={form.planId ?? ""} onChange={(e) => setForm({ ...form, planId: e.target.value })}>{data.plans.filter((plan) => plan.isActive).map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</Select></Field><Field label="Nome do pipeline"><Input required value={form.pipelineName} onChange={(e) => setForm({ ...form, pipelineName: e.target.value })}/></Field>{error && <p role="alert" className="text-sm text-destructive md:col-span-2">{error}</p>}<div className="flex justify-end gap-2 md:col-span-2"><Button type="button" variant="outline" disabled={provisioning} onClick={() => setProvisionOpen(false)}>Cancelar</Button><Button type="submit" disabled={provisioning}>{provisioning ? "Preparando organização..." : "Criar e enviar convite"}</Button></div></form></Modal>
  </PageContainer>;
}
function Metric({label,value}:{label:string;value:string}){return <Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></CardContent></Card>;}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
