import type { ActivityFormData, CompanyFormData, ContactFormData, FollowUpFormData } from './schema';
import type { CommercialActivity, Company, CompanyContact, CompanyFile, CompanyNote, CrmData, FollowUp, TimelineEvent } from './types';
import type { LeadStatus } from '@/shared/types/database';

const STORAGE = 'esads_crm_data_v2';
const now = () => new Date().toISOString();
const empty: CrmData = { companies: [], contacts: [], events: [], followUps: [], activities: [], files: [], notes: [] };
function read(): CrmData { const raw = localStorage.getItem(STORAGE); return raw ? { ...empty, ...JSON.parse(raw) } : seed(); }
function write(data: CrmData) { localStorage.setItem(STORAGE, JSON.stringify(data)); }
function event(companyId: string, type: string, description: string): TimelineEvent { return { id: crypto.randomUUID(), companyId, user: 'Administrador', type, description, createdAt: now() }; }
function tags(value?: string) { return value?.split(',').map((tag) => tag.trim()).filter(Boolean) ?? []; }
function seed(): CrmData { const createdAt = now(); const company: Company = { id: crypto.randomUUID(), fantasyName: 'ESADS Beauty Demo', legalName: 'ESADS Beauty LTDA', city: 'São Paulo', state: 'SP', whatsapp: '(11) 99999-0000', email: 'contato@esadsbeauty.com', responsibleName: 'Admin ESADS', responsibleRole: 'Diretoria', businessArea: 'Beleza', leadSource: 'Indicação', owner: 'Administrador', temperature: 'quente', priority: 'alta', status: 'em_conversa', estimatedValue: 25000, notes: 'Empresa demonstrativa para validar a Central 360°.', tags: ['Cliente VIP', 'Indicação'], createdAt, updatedAt: createdAt, lastInteractionAt: createdAt }; const data = { ...empty, companies: [company], events: [event(company.id, 'company.created', 'Empresa criada')], contacts: [{ id: crypto.randomUUID(), companyId: company.id, name: 'Maria Silva', role: 'Compras', whatsapp: '(11) 98888-0000', email: 'maria@demo.com', isPrimary: true, isFinancial: false, isCommercial: true, status: 'ativo', createdAt, updatedAt: createdAt } as CompanyContact] }; write(data); return data; }

export const crmRepository = {
  async list() { return read(); },
  async createCompany(input: CompanyFormData) { const data = read(); const createdAt = now(); const company: Company = { id: crypto.randomUUID(), ...input, employees: input.employees ?? 0, tags: tags(input.tags), createdAt, updatedAt: createdAt, estimatedValue: input.estimatedValue ?? 0 }; data.companies.unshift(company); data.events.unshift(event(company.id, 'company.created', 'Empresa criada')); write(data); return company; },
  async updateCompany(id: string, input: Partial<CompanyFormData>) { const data = read(); const previous = data.companies.find((company) => company.id === id); data.companies = data.companies.map((company) => company.id === id ? { ...company, ...input, tags: input.tags !== undefined ? tags(input.tags) : company.tags, updatedAt: now(), lastInteractionAt: now() } as Company : company); if (previous && input.status && previous.status !== input.status) data.events.unshift(event(id, 'pipeline.changed', `Pipeline alterado de ${previous.status} para ${input.status}`)); else data.events.unshift(event(id, 'company.updated', 'Empresa editada')); write(data); return data.companies.find((company) => company.id === id)!; },
  async moveCompany(id: string, status: LeadStatus) { return this.updateCompany(id, { status }); },
  async deleteCompany(id: string) { const data = read(); data.companies = data.companies.map((company) => company.id === id ? { ...company, deletedAt: now(), updatedAt: now() } : company); data.events.unshift(event(id, 'company.deleted', 'Empresa removida')); write(data); },
  async duplicateCompany(id: string) { const data = read(); const source = data.companies.find((company) => company.id === id); if (!source) throw new Error('Empresa não encontrada'); return this.createCompany({ ...source, fantasyName: `${source.fantasyName} (cópia)`, tags: source.tags.join(', ') }); },
  async createContact(companyId: string, input: ContactFormData) { const data = read(); const contact: CompanyContact = { id: crypto.randomUUID(), companyId, ...input, createdAt: now(), updatedAt: now() }; if (contact.isPrimary) data.contacts = data.contacts.map((item) => item.companyId === companyId ? { ...item, isPrimary: false } : item); data.contacts.unshift(contact); data.events.unshift(event(companyId, 'contact.created', `Contato criado: ${contact.name}`)); write(data); return contact; },
  async updateContact(id: string, input: Partial<ContactFormData>) { const data = read(); const contact = data.contacts.find((item) => item.id === id); if (!contact) throw new Error('Contato não encontrado'); data.contacts = data.contacts.map((item) => item.id === id ? { ...item, ...input, updatedAt: now() } : item); data.events.unshift(event(contact.companyId, 'contact.updated', `Contato editado: ${contact.name}`)); write(data); },
  async deleteContact(id: string) { const data = read(); const contact = data.contacts.find((item) => item.id === id); data.contacts = data.contacts.filter((item) => item.id !== id); if (contact) data.events.unshift(event(contact.companyId, 'contact.deleted', `Contato excluído: ${contact.name}`)); write(data); },
  async createFollowUp(companyId: string, input: FollowUpFormData) { const data = read(); const item: FollowUp = { id: crypto.randomUUID(), companyId, ...input, createdAt: now(), updatedAt: now() }; data.followUps.unshift(item); data.events.unshift(event(companyId, 'followup.created', `Follow-up criado: ${item.title}`)); data.companies = data.companies.map((company) => company.id === companyId ? { ...company, nextFollowUpAt: `${item.date}T${item.time}:00`, updatedAt: now() } : company); write(data); return item; },
  async updateFollowUp(id: string, input: Partial<FollowUpFormData>) { const data = read(); const item = data.followUps.find((followUp) => followUp.id === id); if (!item) throw new Error('Follow-up não encontrado'); data.followUps = data.followUps.map((followUp) => followUp.id === id ? { ...followUp, ...input, updatedAt: now() } : followUp); data.events.unshift(event(item.companyId, 'followup.updated', `Follow-up atualizado: ${item.title}`)); write(data); },
  async createActivity(companyId: string, input: ActivityFormData) { const data = read(); const item: CommercialActivity = { id: crypto.randomUUID(), companyId, ...input, createdAt: now(), updatedAt: now() }; data.activities.unshift(item); data.events.unshift(event(companyId, 'activity.created', `Agenda criada: ${item.title}`)); if (item.type === 'reuniao') data.companies = data.companies.map((company) => company.id === companyId ? { ...company, nextMeetingAt: `${item.date}T${item.time}:00`, updatedAt: now() } : company); write(data); return item; },
  async addNote(companyId: string, text: string) { const data = read(); const note: CompanyNote = { id: crypto.randomUUID(), companyId, text, author: 'Administrador', createdAt: now(), updatedAt: now() }; data.notes.unshift(note); data.events.unshift(event(companyId, 'note.created', 'Observação criada')); write(data); return note; },
  async addFile(companyId: string, file: Omit<CompanyFile, 'id' | 'companyId' | 'user' | 'createdAt'>) { const data = read(); const item: CompanyFile = { id: crypto.randomUUID(), companyId, user: 'Administrador', createdAt: now(), ...file }; data.files.unshift(item); data.events.unshift(event(companyId, 'file.attached', `Arquivo anexado: ${item.name}`)); write(data); return item; },
};
