create type public.lead_status as enum ('novo_lead','pesquisado','primeiro_contato','aguardando_resposta','em_conversa','reuniao_agendada','proposta_enviada','negociacao','cliente_fechado','perdido');
create type public.priority_level as enum ('baixa','media','alta');
create type public.temperature_level as enum ('frio','morno','quente');
create table public.companies (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  fantasy_name text not null, legal_name text, cnpj text, phone text, whatsapp text, instagram text, facebook text, website text, email text,
  zip_code text, address text, number text, complement text, district text, city text, state char(2), responsible_name text, responsible_role text,
  employees integer default 0, business_area text, lead_source text, owner text, temperature public.temperature_level not null default 'morno', priority public.priority_level not null default 'media',
  status public.lead_status not null default 'novo_lead', estimated_value numeric(14,2) not null default 0, notes text, tags text[] not null default '{}',
  last_interaction_at timestamptz, next_follow_up_at timestamptz, next_meeting_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.company_contacts (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, name text not null, role text, phone text, whatsapp text, email text, instagram text, linkedin text, birth_date date, notes text, is_primary boolean not null default false, is_financial boolean not null default false, is_commercial boolean not null default false, status text not null default 'ativo', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.crm_timeline_events (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, type text not null, description text not null, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.crm_follow_ups (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, title text not null, description text, scheduled_at timestamptz not null, owner text, priority public.priority_level not null default 'media', type text not null, status text not null default 'pendente', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.crm_activities (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, contact_id uuid references public.company_contacts(id) on delete set null, user_id uuid not null references auth.users(id) on delete cascade, title text not null, description text, type text not null, scheduled_at timestamptz not null, duration_minutes integer not null default 30, location text, status text not null default 'agendado', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.company_files (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, name text not null, category text not null, mime_type text, size_bytes bigint, storage_path text, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.company_notes (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, text text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create index companies_user_status_idx on public.companies(user_id,status) where deleted_at is null; create index companies_tags_idx on public.companies using gin(tags); create index companies_search_idx on public.companies using gin (to_tsvector('portuguese', coalesce(fantasy_name,'') || ' ' || coalesce(legal_name,'') || ' ' || coalesce(cnpj,'') || ' ' || coalesce(email,'') || ' ' || coalesce(city,''))) where deleted_at is null;
create index contacts_company_idx on public.company_contacts(company_id) where deleted_at is null; create index timeline_company_idx on public.crm_timeline_events(company_id,created_at desc); create index followups_company_schedule_idx on public.crm_follow_ups(company_id,scheduled_at) where deleted_at is null; create index activities_company_schedule_idx on public.crm_activities(company_id,scheduled_at) where deleted_at is null;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create trigger companies_updated_at before update on public.companies for each row execute function public.set_updated_at(); create trigger contacts_updated_at before update on public.company_contacts for each row execute function public.set_updated_at(); create trigger followups_updated_at before update on public.crm_follow_ups for each row execute function public.set_updated_at(); create trigger activities_updated_at before update on public.crm_activities for each row execute function public.set_updated_at(); create trigger notes_updated_at before update on public.company_notes for each row execute function public.set_updated_at();
alter table public.companies enable row level security; alter table public.company_contacts enable row level security; alter table public.crm_timeline_events enable row level security; alter table public.crm_follow_ups enable row level security; alter table public.crm_activities enable row level security; alter table public.company_files enable row level security; alter table public.company_notes enable row level security;
create policy "companies_own" on public.companies for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "contacts_own" on public.company_contacts for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "timeline_own" on public.crm_timeline_events for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "followups_own" on public.crm_follow_ups for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "activities_own" on public.crm_activities for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "files_own" on public.company_files for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "notes_own" on public.company_notes for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
