-- Capture only name, WhatsApp and Instagram without fabricating e-mail values.
alter table public.diagnostic_submissions alter column email drop not null;
create or replace function public.submit_public_diagnostic(submission_data jsonb)returns jsonb language plpgsql security definer set search_path=public as $$
declare org uuid;actor uuid;submission uuid;token uuid;answers jsonb;answer text;score_sum integer:=0;total integer;level text;stage text;need text;bottleneck text;strongest text;category_scores jsonb:='{}';crm jsonb;category text;question text;idem uuid;existing_crm jsonb;
begin
 if coalesce(submission_data->>'website','')<>'' then raise exception 'invalid_submission' using errcode='22023';end if;
 if length(trim(coalesce(submission_data->>'name','')))<2 or length(regexp_replace(coalesce(submission_data->>'whatsapp',''),'\D','','g'))<10 or length(regexp_replace(coalesce(submission_data->>'instagram',''),'[^a-zA-Z0-9._]','','g'))<2 then raise exception 'invalid_contact' using errcode='22023';end if;
 idem:=(submission_data->>'idempotency_key')::uuid;perform pg_advisory_xact_lock(hashtextextended(idem::text,0));answers:=submission_data->'answers';
 select id into org from public.organizations where slug='esads-beauty' limit 1;select p.id into actor from public.profiles p join public.organization_members m on m.user_id=p.id and m.organization_id=org and m.status='active' join public.roles r on r.id=m.role_id where p.organization_id=org and r.slug in('owner','admin')order by case r.slug when'owner'then 0 else 1 end,m.created_at limit 1;
 if org is null or actor is null then raise exception 'diagnostic_destination_not_configured' using errcode='P0002';end if;
 select public_token into token from public.diagnostic_submissions where organization_id=org and idempotency_key=idem;if token is not null then return jsonb_build_object('token',token);end if;
 if exists(select 1 from public.diagnostic_submissions where organization_id=org and(whatsapp=regexp_replace(submission_data->>'whatsapp','\D','','g'))and created_at>now()-interval'60 seconds')then raise exception 'rate_limited' using errcode='42900';end if;
 foreach question in array array['acquisition','service','organization','follow_up','metrics','demand','business_stage','marketing','financial_clarity','primary_need']loop answer:=answers->>question;if answer not in('a','b','c','d')then raise exception 'incomplete_answers' using errcode='22023';end if;end loop;
 foreach category in array array['acquisition','service','organization','follow_up','metrics','demand','marketing','financial_clarity']loop answer:=answers->>category;total:=case answer when'a'then 0 when'b'then 33 when'c'then 67 else 100 end;category_scores:=category_scores||jsonb_build_object(category,total);score_sum:=score_sum+total;end loop;
 total:=round(score_sum/8.0);level:=case when total<=30 then'Começando a construir a base'when total<=50 then'Fase de estruturação'when total<=70 then'Negócio em desenvolvimento'when total<=85 then'Negócio em crescimento'else'Base bem estruturada'end;
 stage:=case answers->>'business_stage'when'a'then'Começando'when'b'then'Em desenvolvimento'when'c'then'Em crescimento'else'Em estruturação'end;need:=case answers->>'primary_need'when'a'then'Conseguir mais clientes'when'b'then'Transformar mais conversas em agendamentos'when'c'then'Organizar contatos e rotina'else'Ganhar estabilidade e faturar mais'end;
 select key into bottleneck from jsonb_each_text(category_scores)order by value::integer,case key when'acquisition'then 1 when'service'then 2 when'organization'then 3 when'follow_up'then 4 when'metrics'then 5 when'demand'then 6 when'marketing'then 7 else 8 end limit 1;select key into strongest from jsonb_each_text(category_scores)order by value::integer desc,case key when'financial_clarity'then 1 when'marketing'then 2 when'demand'then 3 when'metrics'then 4 when'follow_up'then 5 when'organization'then 6 when'service'then 7 else 8 end limit 1;
 select jsonb_build_object('company_id',company_id,'contact_id',contact_id,'opportunity_id',opportunity_id) into existing_crm from public.diagnostic_submissions where organization_id=org and(whatsapp=regexp_replace(submission_data->>'whatsapp','\D','','g'))and company_id is not null order by created_at desc limit 1;
 if existing_crm is not null then crm:=existing_crm;else crm:=public.create_company_lead(org,actor,jsonb_build_object('name',trim(submission_data->>'name'),'whatsapp',regexp_replace(submission_data->>'whatsapp','\D','','g'),'instagram',regexp_replace(lower(submission_data->>'instagram'),'[^a-z0-9._]','','g'),'responsible_name',trim(submission_data->>'name'),'source','Quiz — Diagnóstico do Negócio','notes',format('Diagnóstico concluído · Score %s/100 · %s · Necessidade: %s · Gargalo: %s',total,level,need,bottleneck)),jsonb_build_object('name',trim(submission_data->>'name'),'whatsapp',regexp_replace(submission_data->>'whatsapp','\D','','g'),'instagram',regexp_replace(lower(submission_data->>'instagram'),'[^a-z0-9._]','','g')));end if;
 insert into public.diagnostic_submissions(organization_id,company_id,contact_id,opportunity_id,idempotency_key,name,business_name,whatsapp,email,instagram,total_score,result_level,business_stage,primary_need,primary_bottleneck,strongest_area,category_scores,utm_source,utm_medium,utm_campaign,utm_content,utm_term,referrer,landing_url,started_at)
 values(org,(crm->>'company_id')::uuid,(crm->>'contact_id')::uuid,(crm->>'opportunity_id')::uuid,idem,trim(submission_data->>'name'),trim(submission_data->>'name'),regexp_replace(submission_data->>'whatsapp','\D','','g'),null,regexp_replace(lower(submission_data->>'instagram'),'[^a-z0-9._]','','g'),total,level,stage,need,bottleneck,strongest,category_scores,submission_data#>>'{attribution,utmSource}',submission_data#>>'{attribution,utmMedium}',submission_data#>>'{attribution,utmCampaign}',submission_data#>>'{attribution,utmContent}',submission_data#>>'{attribution,utmTerm}',submission_data#>>'{attribution,referrer}',submission_data#>>'{attribution,landingUrl}',coalesce((submission_data->>'started_at')::timestamptz,now()))returning id,public_token into submission,token;
 foreach question in array array['acquisition','service','organization','follow_up','metrics','demand','business_stage','marketing','financial_clarity','primary_need']loop answer:=answers->>question;insert into public.diagnostic_answers(submission_id,question_key,answer_key,score,category)values(submission,question,answer,case when question in('business_stage','primary_need')then 0 else ascii(answer)-96 end,question);end loop;
 insert into public.lead_acquisitions(organization_id,company_id,contact_id,opportunity_id,source_id,provider,utm_source,utm_medium,utm_campaign,utm_content,utm_term,landing_page,referrer,captured_at,is_first_touch,is_last_touch,metadata,created_by)
 values(org,(crm->>'company_id')::uuid,(crm->>'contact_id')::uuid,(crm->>'opportunity_id')::uuid,(select id from public.marketing_sources where organization_id=org and slug in('quiz-diagnostico-do-negocio','diagnostico')order by created_at limit 1),'diagnostic',submission_data#>>'{attribution,utmSource}',submission_data#>>'{attribution,utmMedium}',submission_data#>>'{attribution,utmCampaign}',submission_data#>>'{attribution,utmContent}',submission_data#>>'{attribution,utmTerm}',submission_data#>>'{attribution,landingUrl}',submission_data#>>'{attribution,referrer}',now(),true,true,jsonb_build_object('diagnostic_submission_id',submission,'score',total,'level',level),actor);
 insert into public.activities(organization_id,company_id,opportunity_id,user_id,type,title,description,metadata)values(org,(crm->>'company_id')::uuid,(crm->>'opportunity_id')::uuid,actor,'diagnostic_completed','Diagnóstico do negócio concluído',format('Score %s/100 · %s',total,level),jsonb_build_object('submission_id',submission,'score',total,'level',level,'primary_need',need,'bottleneck',bottleneck));
 return jsonb_build_object('token',token);
end$$;
revoke all on function public.submit_public_diagnostic(jsonb)from public;grant execute on function public.submit_public_diagnostic(jsonb)to anon,authenticated;

