create extension if not exists pgcrypto;
create type public.profile_role as enum ('admin','manager','sales','financial','member');
create type public.temperature_level as enum ('frio','morno','quente');
create type public.priority_level as enum ('baixa','media','alta');
create type public.lifecycle_stage as enum ('lead','customer','inactive');
create type public.opportunity_status as enum ('open','won','lost','archived');
create type public.task_type as enum ('follow_up','call','whatsapp','email','meeting','task');
create type public.task_status as enum ('pending','completed','cancelled');

create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, organization_id uuid not null references public.organizations(id), name text not null, email text not null, avatar_url text, role public.profile_role not null default 'member', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.companies (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, legal_name text, cnpj text, instagram text, email text, phone text, whatsapp text, city text, state char(2), source text, temperature public.temperature_level not null default 'morno', priority public.priority_level not null default 'media', notes text, lifecycle_stage public.lifecycle_stage not null default 'lead', owner_id uuid references public.profiles(id) on delete set null, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.contacts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid not null references public.companies(id), name text not null, role text, email text, phone text, whatsapp text, instagram text, is_primary boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.pipelines (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, description text, is_default boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index pipelines_one_default_per_org on public.pipelines(organization_id) where is_default;
create table public.pipeline_stages (id uuid primary key default gen_random_uuid(), pipeline_id uuid not null references public.pipelines(id) on delete cascade, name text not null, slug text not null, position integer not null check (position >= 0), probability numeric(5,2) not null default 0 check (probability between 0 and 100), is_won boolean not null default false, is_lost boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(pipeline_id, slug), unique(pipeline_id, position), check (not (is_won and is_lost)));
create table public.opportunities (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid not null references public.companies(id), pipeline_id uuid not null references public.pipelines(id), stage_id uuid not null references public.pipeline_stages(id), title text not null, description text, value numeric(14,2) not null default 0 check (value >= 0), probability numeric(5,2) not null default 0 check (probability between 0 and 100), expected_close_date date, owner_id uuid references public.profiles(id) on delete set null, source text, status public.opportunity_status not null default 'open', lost_reason text, won_at timestamptz, lost_at timestamptz, stage_entered_at timestamptz not null default now(), created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.activities (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid references public.companies(id), opportunity_id uuid references public.opportunities(id), user_id uuid references public.profiles(id) on delete set null, type text not null, title text not null, description text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid references public.companies(id), opportunity_id uuid references public.opportunities(id), assigned_to uuid references public.profiles(id) on delete set null, created_by uuid not null references public.profiles(id), title text not null, description text, type public.task_type not null default 'task', status public.task_status not null default 'pending', priority public.priority_level not null default 'media', due_date timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.notes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid not null references public.companies(id), opportunity_id uuid references public.opportunities(id), created_by uuid not null references public.profiles(id), body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);

create index profiles_organization_idx on public.profiles(organization_id); create index companies_org_created_idx on public.companies(organization_id,created_at desc) where deleted_at is null; create index companies_owner_idx on public.companies(owner_id) where deleted_at is null; create index contacts_org_company_idx on public.contacts(organization_id,company_id) where deleted_at is null; create index pipelines_org_idx on public.pipelines(organization_id); create index stages_pipeline_idx on public.pipeline_stages(pipeline_id,position); create index opportunities_org_status_idx on public.opportunities(organization_id,status,created_at desc) where deleted_at is null; create index opportunities_company_idx on public.opportunities(company_id) where deleted_at is null; create index opportunities_pipeline_stage_idx on public.opportunities(pipeline_id,stage_id) where deleted_at is null; create index opportunities_owner_idx on public.opportunities(owner_id) where deleted_at is null; create index activities_org_created_idx on public.activities(organization_id,created_at desc); create index activities_company_idx on public.activities(company_id,created_at desc); create index activities_opportunity_idx on public.activities(opportunity_id,created_at desc); create index tasks_org_status_due_idx on public.tasks(organization_id,status,due_date) where deleted_at is null; create index tasks_company_idx on public.tasks(company_id) where deleted_at is null; create index notes_company_idx on public.notes(company_id,created_at desc) where deleted_at is null;

create function public.current_organization_id() returns uuid language sql stable security definer set search_path = public as $$ select organization_id from public.profiles where id = auth.uid() $$;
create function public.set_updated_at() returns trigger language plpgsql set search_path = public as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare table_name text; begin foreach table_name in array array['organizations','profiles','companies','contacts','pipelines','pipeline_stages','opportunities','tasks','notes'] loop execute format('create trigger %I_updated_at before update on public.%I for each row execute function public.set_updated_at()',table_name,table_name); end loop; end $$;

alter table public.organizations enable row level security; alter table public.profiles enable row level security; alter table public.companies enable row level security; alter table public.contacts enable row level security; alter table public.pipelines enable row level security; alter table public.pipeline_stages enable row level security; alter table public.opportunities enable row level security; alter table public.activities enable row level security; alter table public.tasks enable row level security; alter table public.notes enable row level security;
create policy organizations_member on public.organizations for select using (id=public.current_organization_id()); create policy profiles_member on public.profiles for select using (organization_id=public.current_organization_id());
create policy companies_member on public.companies for all using (organization_id=public.current_organization_id()) with check (organization_id=public.current_organization_id()); create policy contacts_member on public.contacts for all using (organization_id=public.current_organization_id()) with check (organization_id=public.current_organization_id()); create policy pipelines_member on public.pipelines for all using (organization_id=public.current_organization_id()) with check (organization_id=public.current_organization_id()); create policy stages_member on public.pipeline_stages for all using (exists(select 1 from public.pipelines p where p.id=pipeline_id and p.organization_id=public.current_organization_id())) with check (exists(select 1 from public.pipelines p where p.id=pipeline_id and p.organization_id=public.current_organization_id())); create policy opportunities_member on public.opportunities for all using (organization_id=public.current_organization_id()) with check (organization_id=public.current_organization_id()); create policy activities_member on public.activities for all using (organization_id=public.current_organization_id()) with check (organization_id=public.current_organization_id()); create policy tasks_member on public.tasks for all using (organization_id=public.current_organization_id()) with check (organization_id=public.current_organization_id()); create policy notes_member on public.notes for all using (organization_id=public.current_organization_id()) with check (organization_id=public.current_organization_id());

create function public.create_default_pipeline(target_organization_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare new_pipeline_id uuid; begin insert into public.pipelines(organization_id,name,description,is_default) values(target_organization_id,'Pipeline Comercial','Pipeline padrão da ESADS Beauty',true) returning id into new_pipeline_id; insert into public.pipeline_stages(pipeline_id,name,slug,position,probability,is_won,is_lost) values (new_pipeline_id,'Novo Lead','novo_lead',0,10,false,false),(new_pipeline_id,'Pesquisado','pesquisado',1,15,false,false),(new_pipeline_id,'Primeiro Contato','primeiro_contato',2,20,false,false),(new_pipeline_id,'Aguardando Resposta','aguardando_resposta',3,25,false,false),(new_pipeline_id,'Em Conversa','em_conversa',4,35,false,false),(new_pipeline_id,'Reunião Agendada','reuniao_agendada',5,50,false,false),(new_pipeline_id,'Proposta Enviada','proposta_enviada',6,65,false,false),(new_pipeline_id,'Negociação','negociacao',7,80,false,false),(new_pipeline_id,'Cliente Fechado','cliente_fechado',8,100,true,false),(new_pipeline_id,'Perdido','perdido',9,0,false,true); return new_pipeline_id; end $$;

create function public.bootstrap_default_pipeline() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.create_default_pipeline(new.id); return new; end $$;
create trigger organizations_default_pipeline after insert on public.organizations for each row execute function public.bootstrap_default_pipeline();

insert into public.organizations(name,slug) values ('ESADS Beauty','esads-beauty') on conflict(slug) do nothing;

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare esads_organization_id uuid; begin select id into esads_organization_id from public.organizations where slug='esads-beauty'; insert into public.profiles(id,organization_id,name,email,role) values(new.id,esads_organization_id,coalesce(new.raw_user_meta_data->>'name',split_part(coalesce(new.email,''),'@',1)),coalesce(new.email,''),'admin'); return new; end $$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.handle_new_user();

create function public.track_opportunity_stage_change() returns trigger language plpgsql security definer set search_path=public as $$ declare old_stage_name text; new_stage_name text; begin if new.stage_id is distinct from old.stage_id then select name into old_stage_name from public.pipeline_stages where id=old.stage_id; select name into new_stage_name from public.pipeline_stages where id=new.stage_id and pipeline_id=new.pipeline_id; if new_stage_name is null then raise exception 'A etapa não pertence ao pipeline da oportunidade'; end if; new.stage_entered_at=now(); insert into public.activities(organization_id,company_id,opportunity_id,user_id,type,title,description,metadata) values(new.organization_id,new.company_id,new.id,auth.uid(),'stage_changed','Etapa atualizada',old_stage_name||' → '||new_stage_name,jsonb_build_object('from_stage',old_stage_name,'to_stage',new_stage_name)); end if; return new; end $$;
create trigger opportunities_stage_activity before update of stage_id on public.opportunities for each row execute function public.track_opportunity_stage_change();
