-- Gerencial financeiro: venda/contrato não geram caixa automaticamente.
create table if not exists public.financial_accounts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,type text not null check(type in('bank','cash','digital_wallet','other')),bank_name text,initial_balance numeric(14,2) not null default 0,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,unique(organization_id,name));
create table if not exists public.financial_categories(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,type text not null check(type in('income','expense')),parent_id uuid references public.financial_categories(id),dre_group text not null check(dre_group in('gross_revenue','deduction','direct_cost','operating_expense','other_income','other_expense')),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,type,name));
create table if not exists public.cost_centers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,description text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,name));
create table if not exists public.recurrence_rules(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),type text not null check(type in('receivable','payable')),customer_account_id uuid references public.customer_accounts(id),contract_id uuid references public.contracts(id),customer_service_id uuid references public.customer_services(id),supplier_name text,description text not null,amount numeric(14,2) not null check(amount>0),category_id uuid references public.financial_categories(id),cost_center_id uuid references public.cost_centers(id),frequency text not null check(frequency in('monthly','quarterly','semiannual','yearly')),interval_count integer not null default 1 check(interval_count>0),start_date date not null,end_date date,due_day integer not null check(due_day between 1 and 31),is_active boolean not null default true,next_generation_date date not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),cancelled_at timestamptz,check(end_date is null or end_date>=start_date));
create table if not exists public.receivables(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),customer_account_id uuid references public.customer_accounts(id),company_id uuid references public.companies(id),contract_id uuid references public.contracts(id),customer_service_id uuid references public.customer_services(id),source_opportunity_id uuid references public.opportunities(id),description text not null,category_id uuid references public.financial_categories(id),cost_center_id uuid references public.cost_centers(id),competence_date date not null,due_date date not null,original_amount numeric(14,2) not null check(original_amount>=0),discount_amount numeric(14,2) not null default 0 check(discount_amount>=0),interest_amount numeric(14,2) not null default 0 check(interest_amount>=0),penalty_amount numeric(14,2) not null default 0 check(penalty_amount>=0),net_amount numeric(14,2) generated always as (original_amount-discount_amount+interest_amount+penalty_amount) stored,status text not null default 'pending' check(status in('pending','partially_paid','paid','cancelled','refunded')),payment_method text check(payment_method is null or payment_method in('pix','bank_transfer','boleto','credit_card','debit_card','cash','other')),notes text,recurrence_rule_id uuid references public.recurrence_rules(id),recurrence_key text,created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),cancelled_at timestamptz,deleted_at timestamptz,check(discount_amount<=original_amount+interest_amount+penalty_amount),unique(organization_id,recurrence_key));
create table if not exists public.payables(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),supplier_name text not null,description text not null,category_id uuid references public.financial_categories(id),cost_center_id uuid references public.cost_centers(id),competence_date date not null,due_date date not null,original_amount numeric(14,2) not null check(original_amount>=0),discount_amount numeric(14,2) not null default 0 check(discount_amount>=0),interest_amount numeric(14,2) not null default 0 check(interest_amount>=0),penalty_amount numeric(14,2) not null default 0 check(penalty_amount>=0),net_amount numeric(14,2) generated always as (original_amount-discount_amount+interest_amount+penalty_amount) stored,status text not null default 'pending' check(status in('pending','partially_paid','paid','cancelled','refunded')),financial_account_id uuid references public.financial_accounts(id),notes text,recurrence_rule_id uuid references public.recurrence_rules(id),recurrence_key text,created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),cancelled_at timestamptz,deleted_at timestamptz,check(discount_amount<=original_amount+interest_amount+penalty_amount),unique(organization_id,recurrence_key));
create table if not exists public.financial_transactions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),financial_account_id uuid not null references public.financial_accounts(id),type text not null check(type in('income','expense','transfer','adjustment')),transfer_direction text check(transfer_direction is null or transfer_direction in('in','out')),amount numeric(14,2) not null check(amount>0),occurred_at timestamptz not null,description text not null,payment_method text check(payment_method is null or payment_method in('pix','bank_transfer','boleto','credit_card','debit_card','cash','other')),reference text,created_by uuid not null default auth.uid() references public.profiles(id),reversed_at timestamptz,reversed_by uuid references public.profiles(id),reversal_of_id uuid references public.financial_transactions(id),transfer_id uuid,created_at timestamptz not null default now(),unique(organization_id,reference),check((type='transfer')=(transfer_direction is not null)));
create table if not exists public.payment_allocations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),transaction_id uuid not null references public.financial_transactions(id),receivable_id uuid references public.receivables(id),payable_id uuid references public.payables(id),amount numeric(14,2) not null check(amount>0),created_at timestamptz not null default now(),check((receivable_id is not null)::integer+(payable_id is not null)::integer=1));

create index if not exists receivables_due_idx on public.receivables(organization_id,due_date,status) where deleted_at is null;
create index if not exists receivables_competence_idx on public.receivables(organization_id,competence_date,category_id);
create index if not exists receivables_customer_idx on public.receivables(customer_account_id,due_date);
create index if not exists payables_due_idx on public.payables(organization_id,due_date,status) where deleted_at is null;
create index if not exists payables_competence_idx on public.payables(organization_id,competence_date,category_id,cost_center_id);
create index if not exists financial_transactions_cash_idx on public.financial_transactions(organization_id,occurred_at,type) where reversed_at is null;
create index if not exists allocations_receivable_idx on public.payment_allocations(receivable_id);
create index if not exists allocations_payable_idx on public.payment_allocations(payable_id);
create index if not exists recurrence_next_idx on public.recurrence_rules(organization_id,next_generation_date) where is_active;

do $$ declare n text; begin foreach n in array array['financial_accounts','financial_categories','cost_centers','recurrence_rules','receivables','payables'] loop execute format('create trigger %I_updated_at before update on public.%I for each row execute function public.set_updated_at()',n,n); end loop; end $$;
do $$ declare n text; begin foreach n in array array['financial_accounts','financial_categories','cost_centers','recurrence_rules','receivables','payables','financial_transactions','payment_allocations'] loop execute format('alter table public.%I enable row level security',n);execute format('create policy organization_isolation on public.%I for all using (organization_id=public.current_organization_id()) with check (organization_id=public.current_organization_id())',n);end loop;end $$;

create or replace function public.register_financial_payment(entry_kind text,target_entry_id uuid,target_account_id uuid,payment_amount numeric,payment_occurred_at timestamptz,payment_method_value text,payment_reference text,payment_notes text default null) returns uuid language plpgsql security invoker set search_path=public as $$
declare org uuid:=public.current_organization_id(); total numeric; paid numeric; tx_id uuid; company uuid; label text;
begin
 if payment_amount<=0 then raise exception 'invalid_payment_amount';end if;
 if entry_kind='receivable' then
  select net_amount,company_id into total,company from public.receivables where id=target_entry_id and organization_id=org and status not in('cancelled','refunded') for update;
  select coalesce(sum(pa.amount),0) into paid from public.payment_allocations pa join public.financial_transactions ft on ft.id=pa.transaction_id where pa.receivable_id=target_entry_id and ft.reversed_at is null; label:='Recebimento';
 else
  select net_amount into total from public.payables where id=target_entry_id and organization_id=org and status not in('cancelled','refunded') for update;
  select coalesce(sum(pa.amount),0) into paid from public.payment_allocations pa join public.financial_transactions ft on ft.id=pa.transaction_id where pa.payable_id=target_entry_id and ft.reversed_at is null; label:='Pagamento';
 end if;
 if total is null then raise exception 'entry_not_found';end if;if payment_amount>total-paid then raise exception 'overpayment_not_allowed';end if;
 insert into public.financial_transactions(organization_id,financial_account_id,type,amount,occurred_at,description,payment_method,reference,created_by) values(org,target_account_id,case when entry_kind='receivable' then 'income' else 'expense' end,payment_amount,payment_occurred_at,label,payment_method_value,payment_reference,auth.uid()) returning id into tx_id;
 insert into public.payment_allocations(organization_id,transaction_id,receivable_id,payable_id,amount) values(org,tx_id,case when entry_kind='receivable' then target_entry_id end,case when entry_kind='payable' then target_entry_id end,payment_amount);
 if entry_kind='receivable' then update public.receivables set status=case when paid+payment_amount=total then 'paid' else 'partially_paid' end where id=target_entry_id;else update public.payables set status=case when paid+payment_amount=total then 'paid' else 'partially_paid' end where id=target_entry_id;end if;
 if company is not null then insert into public.activities(organization_id,company_id,user_id,type,title,description,metadata) values(org,company,auth.uid(),case when paid+payment_amount=total then 'receivable_paid' else 'receivable_partially_paid' end,case when paid+payment_amount=total then 'Pagamento recebido' else 'Pagamento parcial recebido' end,format('Pagamento de R$ %s recebido.',payment_amount),jsonb_build_object('transaction_id',tx_id,'receivable_id',target_entry_id,'amount',payment_amount));end if;
 return tx_id;
exception when unique_violation then raise exception 'duplicate_payment_reference';end $$;

create or replace function public.reverse_financial_transaction(target_transaction_id uuid) returns void language plpgsql security invoker set search_path=public as $$
declare tx public.financial_transactions; alloc public.payment_allocations;
begin select * into tx from public.financial_transactions where id=target_transaction_id and organization_id=public.current_organization_id() for update;if tx.id is null or tx.reversed_at is not null then raise exception 'transaction_not_reversible';end if;update public.financial_transactions set reversed_at=now(),reversed_by=auth.uid() where id=tx.id;for alloc in select * from public.payment_allocations where transaction_id=tx.id loop if alloc.receivable_id is not null then update public.receivables set status=case when exists(select 1 from public.payment_allocations pa join public.financial_transactions ft on ft.id=pa.transaction_id where pa.receivable_id=alloc.receivable_id and ft.id<>tx.id and ft.reversed_at is null) then 'partially_paid' else 'pending' end where id=alloc.receivable_id;else update public.payables set status=case when exists(select 1 from public.payment_allocations pa join public.financial_transactions ft on ft.id=pa.transaction_id where pa.payable_id=alloc.payable_id and ft.id<>tx.id and ft.reversed_at is null) then 'partially_paid' else 'pending' end where id=alloc.payable_id;end if;end loop;end $$;
grant execute on function public.register_financial_payment(text,uuid,uuid,numeric,timestamptz,text,text,text) to authenticated;
grant execute on function public.reverse_financial_transaction(uuid) to authenticated;

create or replace function public.generate_recurring_entries(target_rule_id uuid,through_date date) returns integer language plpgsql security invoker set search_path=public as $$
declare rule public.recurrence_rules; generation date; months integer; generated integer:=0; key text;
begin select * into rule from public.recurrence_rules where id=target_rule_id and organization_id=public.current_organization_id() and is_active for update;if rule.id is null then raise exception 'recurrence_not_found';end if;generation:=rule.next_generation_date;months:=(case rule.frequency when 'monthly' then 1 when 'quarterly' then 3 when 'semiannual' then 6 else 12 end)*rule.interval_count;
 while generation<=through_date and (rule.end_date is null or generation<=rule.end_date) loop key:=rule.id::text||':'||to_char(generation,'YYYY-MM');if rule.type='receivable' then insert into public.receivables(organization_id,customer_account_id,contract_id,customer_service_id,description,category_id,cost_center_id,competence_date,due_date,original_amount,recurrence_rule_id,recurrence_key) values(rule.organization_id,rule.customer_account_id,rule.contract_id,rule.customer_service_id,rule.description,rule.category_id,rule.cost_center_id,date_trunc('month',generation)::date,generation,rule.amount,rule.id,key) on conflict(organization_id,recurrence_key) do nothing;if found then generated:=generated+1;end if;else insert into public.payables(organization_id,supplier_name,description,category_id,cost_center_id,competence_date,due_date,original_amount,recurrence_rule_id,recurrence_key) values(rule.organization_id,coalesce(rule.supplier_name,'Fornecedor'),rule.description,rule.category_id,rule.cost_center_id,date_trunc('month',generation)::date,generation,rule.amount,rule.id,key) on conflict(organization_id,recurrence_key) do nothing;if found then generated:=generated+1;end if;end if;generation:=(generation+make_interval(months=>months))::date;end loop;update public.recurrence_rules set next_generation_date=generation where id=rule.id;return generated;end $$;
grant execute on function public.generate_recurring_entries(uuid,date) to authenticated;

create or replace function public.register_financial_entry_activity() returns trigger language plpgsql security definer set search_path=public as $$
begin
 if tg_table_name='receivables' and new.company_id is not null then insert into public.activities(organization_id,company_id,user_id,type,title,description,metadata) values(new.organization_id,new.company_id,new.created_by,'receivable_created','Cobrança criada',new.description,jsonb_build_object('receivable_id',new.id,'amount',new.net_amount,'competence_date',new.competence_date,'due_date',new.due_date));end if;
 return new;
end $$;
create trigger receivables_activity after insert on public.receivables for each row execute function public.register_financial_entry_activity();
