-- Public acquisition diagnostic: write-only RPC, deterministic server score and atomic CRM conversion.
create table if not exists public.diagnostic_submissions(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid references public.companies(id), contact_id uuid references public.contacts(id), opportunity_id uuid references public.opportunities(id),
 public_token uuid not null default gen_random_uuid(), idempotency_key uuid not null, name text not null, business_name text not null, whatsapp text not null, email text not null, instagram text not null,
 total_score integer not null check(total_score between 0 and 100), result_level text not null, business_stage text not null, primary_need text not null, primary_bottleneck text not null, strongest_area text not null,
 category_scores jsonb not null default '{}', utm_source text, utm_medium text, utm_campaign text, utm_content text, utm_term text, referrer text, landing_url text,
 started_at timestamptz not null, completed_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(organization_id,idempotency_key), unique(public_token)
);
create table if not exists public.diagnostic_answers(id uuid primary key default gen_random_uuid(),submission_id uuid not null references public.diagnostic_submissions(id) on delete cascade,question_key text not null,answer_key text not null check(answer_key in('a','b','c','d')),score integer not null check(score between 0 and 4),category text not null,created_at timestamptz not null default now(),unique(submission_id,question_key));
create index if not exists diagnostic_submissions_contact_idx on public.diagnostic_submissions(organization_id,whatsapp,email,created_at desc);
create index if not exists diagnostic_answers_submission_idx on public.diagnostic_answers(submission_id);
alter table public.diagnostic_submissions enable row level security;alter table public.diagnostic_answers enable row level security;

create or replace function public.create_company_lead(target_organization uuid,target_actor uuid,company_data jsonb,contact_data jsonb default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare new_company public.companies;new_contact public.contacts;new_opportunity public.opportunities;default_pipeline public.pipelines;initial_stage public.pipeline_stages;
begin
 if not exists(select 1 from public.profiles where id=target_actor and organization_id=target_organization) then raise exception 'actor_not_found' using errcode='42501';end if;
 select * into default_pipeline from public.pipelines where organization_id=target_organization and is_default=true order by created_at,id limit 1;
 if default_pipeline.id is null then raise exception 'default_pipeline_not_found' using errcode='P0002';end if;
 select * into initial_stage from public.pipeline_stages where pipeline_id=default_pipeline.id and(slug='novo_lead' or lower(name)='novo lead')order by position,id limit 1;
 if initial_stage.id is null then raise exception 'initial_stage_not_found' using errcode='P0002';end if;
 insert into public.companies(organization_id,name,legal_name,cnpj,phone,whatsapp,instagram,facebook,website,email,zip_code,address,address_number,complement,district,city,state,responsible_name,responsible_role,employees,business_area,source,temperature,priority,notes,tags,owner_id,created_by)
 values(target_organization,company_data->>'name',nullif(company_data->>'legal_name',''),nullif(company_data->>'cnpj',''),nullif(company_data->>'phone',''),nullif(company_data->>'whatsapp',''),nullif(company_data->>'instagram',''),nullif(company_data->>'facebook',''),nullif(company_data->>'website',''),nullif(company_data->>'email',''),nullif(company_data->>'zip_code',''),nullif(company_data->>'address',''),nullif(company_data->>'address_number',''),nullif(company_data->>'complement',''),nullif(company_data->>'district',''),nullif(company_data->>'city',''),nullif(company_data->>'state',''),nullif(company_data->>'responsible_name',''),nullif(company_data->>'responsible_role',''),nullif(company_data->>'employees','')::integer,nullif(company_data->>'business_area',''),nullif(company_data->>'source',''),coalesce((company_data->>'temperature')::public.temperature_level,'morno'),coalesce((company_data->>'priority')::public.priority_level,'media'),nullif(company_data->>'notes',''),coalesce(array(select jsonb_array_elements_text(company_data->'tags')),'{}'),target_actor,target_actor)returning*into new_company;
 if contact_data is not null then insert into public.contacts(organization_id,company_id,name,whatsapp,email,instagram,is_primary,is_commercial)values(target_organization,new_company.id,contact_data->>'name',nullif(contact_data->>'whatsapp',''),nullif(contact_data->>'email',''),nullif(contact_data->>'instagram',''),true,true)returning*into new_contact;end if;
 insert into public.opportunities(organization_id,company_id,pipeline_id,stage_id,title,value,probability,owner_id,status,source,created_by)values(target_organization,new_company.id,default_pipeline.id,initial_stage.id,new_company.name,0,initial_stage.probability,target_actor,'open',company_data->>'source',target_actor)returning*into new_opportunity;
 return jsonb_build_object('company_id',new_company.id,'contact_id',new_contact.id,'opportunity_id',new_opportunity.id);
end$$;
revoke all on function public.create_company_lead(uuid,uuid,jsonb,jsonb)from public,anon,authenticated;

-- The authenticated CRM and public diagnostic share the same atomic company/contact/opportunity use case.
create or replace function public.create_company_with_primary_contact(company_data jsonb,contact_data jsonb default null)returns public.companies language plpgsql security invoker set search_path=public as $$
declare profile public.profiles;ids jsonb;created public.companies;begin select*into profile from public.profiles where id=auth.uid();if profile.id is null then raise exception'authenticated_profile_not_found'using errcode='42501';end if;ids:=public.create_company_lead(profile.organization_id,profile.id,company_data,contact_data);select*into created from public.companies where id=(ids->>'company_id')::uuid;return created;end$$;
revoke all on function public.create_company_with_primary_contact(jsonb,jsonb)from public,anon;grant execute on function public.create_company_with_primary_contact(jsonb,jsonb)to authenticated;

create or replace function public.submit_public_diagnostic(submission_data jsonb)returns jsonb language plpgsql security definer set search_path=public as $$
declare org uuid;actor uuid;submission uuid;token uuid;answers jsonb;answer text;score_sum integer:=0;total integer;level text;stage text;need text;bottleneck text;strongest text;category_scores jsonb:='{}';crm jsonb;category text;question text;idem uuid;
begin
 if coalesce(submission_data->>'website','')<>'' then raise exception 'invalid_submission' using errcode='22023';end if;
 if length(trim(coalesce(submission_data->>'name','')))<2 or length(regexp_replace(coalesce(submission_data->>'whatsapp',''),'\D','','g'))<10 or position('@'in coalesce(submission_data->>'email',''))<2 then raise exception 'invalid_contact' using errcode='22023';end if;
 idem:=(submission_data->>'idempotency_key')::uuid;perform pg_advisory_xact_lock(hashtextextended(idem::text,0));answers:=submission_data->'answers';
 select id into org from public.organizations where slug='esads-beauty' limit 1;select p.id into actor from public.profiles p join public.organization_members m on m.user_id=p.id and m.organization_id=org and m.status='active' join public.roles r on r.id=m.role_id where p.organization_id=org and r.slug in('owner','admin')order by case r.slug when'owner'then 0 else 1 end,m.created_at limit 1;
 if org is null or actor is null then raise exception 'diagnostic_destination_not_configured' using errcode='P0002';end if;
 select public_token into token from public.diagnostic_submissions where organization_id=org and idempotency_key=idem;if token is not null then return jsonb_build_object('token',token);end if;
 if exists(select 1 from public.diagnostic_submissions where organization_id=org and(whatsapp=regexp_replace(submission_data->>'whatsapp','\D','','g')or email=lower(submission_data->>'email'))and created_at>now()-interval'60 seconds')then raise exception 'rate_limited' using errcode='42900';end if;
 foreach question in array array['acquisition','service','organization','follow_up','metrics','demand','business_stage','marketing','financial_clarity','primary_need']loop answer:=answers->>question;if answer not in('a','b','c','d')then raise exception 'incomplete_answers' using errcode='22023';end if;end loop;
 foreach category in array array['acquisition','service','organization','follow_up','metrics','demand','marketing','financial_clarity']loop answer:=answers->>category;total:=case answer when'a'then 0 when'b'then 33 when'c'then 67 else 100 end;category_scores:=category_scores||jsonb_build_object(category,total);score_sum:=score_sum+total;end loop;
 total:=round(score_sum/8.0);level:=case when total<=30 then'Começando a construir a base'when total<=50 then'Fase de estruturação'when total<=70 then'Negócio em desenvolvimento'when total<=85 then'Negócio em crescimento'else'Base bem estruturada'end;
 stage:=case answers->>'business_stage'when'a'then'Começando'when'b'then'Em desenvolvimento'when'c'then'Em crescimento'else'Em estruturação'end;need:=case answers->>'primary_need'when'a'then'Conseguir mais clientes'when'b'then'Transformar mais conversas em agendamentos'when'c'then'Organizar contatos e rotina'else'Ganhar estabilidade e faturar mais'end;
 select key into bottleneck from jsonb_each_text(category_scores)order by value::integer,case key when'acquisition'then 1 when'service'then 2 when'organization'then 3 when'follow_up'then 4 when'metrics'then 5 when'demand'then 6 when'marketing'then 7 else 8 end limit 1;select key into strongest from jsonb_each_text(category_scores)order by value::integer desc,case key when'financial_clarity'then 1 when'marketing'then 2 when'demand'then 3 when'metrics'then 4 when'follow_up'then 5 when'organization'then 6 when'service'then 7 else 8 end limit 1;
 crm:=public.create_company_lead(org,actor,jsonb_build_object('name',submission_data->>'business_name','whatsapp',regexp_replace(submission_data->>'whatsapp','\D','','g'),'instagram',submission_data->>'instagram','email',lower(submission_data->>'email'),'responsible_name',submission_data->>'name','source','Quiz — Diagnóstico do Negócio','notes',format('Diagnóstico concluído · Score %s/100 · %s · Necessidade: %s · Gargalo: %s',total,level,need,bottleneck)),jsonb_build_object('name',submission_data->>'name','whatsapp',regexp_replace(submission_data->>'whatsapp','\D','','g'),'email',lower(submission_data->>'email'),'instagram',submission_data->>'instagram'));
 insert into public.diagnostic_submissions(organization_id,company_id,contact_id,opportunity_id,idempotency_key,name,business_name,whatsapp,email,instagram,total_score,result_level,business_stage,primary_need,primary_bottleneck,strongest_area,category_scores,utm_source,utm_medium,utm_campaign,utm_content,utm_term,referrer,landing_url,started_at)
 values(org,(crm->>'company_id')::uuid,(crm->>'contact_id')::uuid,(crm->>'opportunity_id')::uuid,idem,trim(submission_data->>'name'),trim(submission_data->>'business_name'),regexp_replace(submission_data->>'whatsapp','\D','','g'),lower(submission_data->>'email'),submission_data->>'instagram',total,level,stage,need,bottleneck,strongest,category_scores,submission_data#>>'{attribution,utmSource}',submission_data#>>'{attribution,utmMedium}',submission_data#>>'{attribution,utmCampaign}',submission_data#>>'{attribution,utmContent}',submission_data#>>'{attribution,utmTerm}',submission_data#>>'{attribution,referrer}',submission_data#>>'{attribution,landingUrl}',coalesce((submission_data->>'started_at')::timestamptz,now()))returning id,public_token into submission,token;
 foreach question in array array['acquisition','service','organization','follow_up','metrics','demand','business_stage','marketing','financial_clarity','primary_need']loop answer:=answers->>question;insert into public.diagnostic_answers(submission_id,question_key,answer_key,score,category)values(submission,question,answer,case when question in('business_stage','primary_need')then 0 else ascii(answer)-96 end,question);end loop;
 insert into public.lead_acquisitions(organization_id,company_id,contact_id,opportunity_id,source_id,provider,utm_source,utm_medium,utm_campaign,utm_content,utm_term,landing_page,referrer,captured_at,is_first_touch,is_last_touch,metadata,created_by)
 values(org,(crm->>'company_id')::uuid,(crm->>'contact_id')::uuid,(crm->>'opportunity_id')::uuid,(select id from public.marketing_sources where organization_id=org and slug in('quiz-diagnostico-do-negocio','diagnostico')order by created_at limit 1),'diagnostic',submission_data#>>'{attribution,utmSource}',submission_data#>>'{attribution,utmMedium}',submission_data#>>'{attribution,utmCampaign}',submission_data#>>'{attribution,utmContent}',submission_data#>>'{attribution,utmTerm}',submission_data#>>'{attribution,landingUrl}',submission_data#>>'{attribution,referrer}',now(),true,true,jsonb_build_object('diagnostic_submission_id',submission,'score',total,'level',level),actor);
 insert into public.activities(organization_id,company_id,opportunity_id,user_id,type,title,description,metadata)values(org,(crm->>'company_id')::uuid,(crm->>'opportunity_id')::uuid,actor,'diagnostic_completed','Diagnóstico do negócio concluído',format('Score %s/100 · %s',total,level),jsonb_build_object('submission_id',submission,'score',total,'level',level,'primary_need',need,'bottleneck',bottleneck));
 return jsonb_build_object('token',token);
end$$;
revoke all on function public.submit_public_diagnostic(jsonb)from public;grant execute on function public.submit_public_diagnostic(jsonb)to anon,authenticated;

create or replace function public.public_diagnostic_result(result_token uuid)returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('token',s.public_token,'lead',jsonb_build_object('name',s.name,'businessName',s.business_name,'whatsapp',s.whatsapp,'email',s.email,'instagram',s.instagram),'answers',(select jsonb_object_agg(a.question_key,a.answer_key)from public.diagnostic_answers a where a.submission_id=s.id),'createdAt',s.created_at)from public.diagnostic_submissions s where s.public_token=result_token$$;
revoke all on function public.public_diagnostic_result(uuid)from public;grant execute on function public.public_diagnostic_result(uuid)to anon,authenticated;
