-- Marketing analytics. No leads, companies or CRM source text are removed or duplicated.
create table if not exists public.marketing_sources(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,slug text not null,channel text not null check(channel in('paid_social','paid_search','organic_social','organic_search','referral','outbound','direct','partner','other')),platform text not null,type text not null,is_paid boolean not null default false,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,slug));
create table if not exists public.marketing_campaigns(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),source_id uuid not null references public.marketing_sources(id),provider text not null,external_id text,name text not null,objective text,status text not null check(status in('active','paused','completed','archived')),start_date date,end_date date,budget numeric(14,2) check(budget is null or budget>=0),external_account_id text,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date is null or start_date is null or end_date>=start_date));
create unique index if not exists marketing_campaign_external_unique on public.marketing_campaigns(organization_id,provider,external_id) where external_id is not null;
create table if not exists public.marketing_ad_groups(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),campaign_id uuid not null references public.marketing_campaigns(id),external_id text,name text not null,status text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists marketing_ad_group_external_unique on public.marketing_ad_groups(organization_id,campaign_id,external_id) where external_id is not null;
create table if not exists public.marketing_ads(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),campaign_id uuid not null references public.marketing_campaigns(id),ad_group_id uuid references public.marketing_ad_groups(id),external_id text,name text not null,status text not null,creative_name text,destination_url text,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists marketing_ad_external_unique on public.marketing_ads(organization_id,campaign_id,external_id) where external_id is not null;
create table if not exists public.lead_acquisitions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),company_id uuid not null references public.companies(id),contact_id uuid references public.contacts(id),opportunity_id uuid references public.opportunities(id),source_id uuid references public.marketing_sources(id),campaign_id uuid references public.marketing_campaigns(id),ad_group_id uuid references public.marketing_ad_groups(id),ad_id uuid references public.marketing_ads(id),utm_source text,utm_medium text,utm_campaign text,utm_content text,utm_term text,landing_page text,referrer text,gclid text,fbclid text,utm_id text,captured_at timestamptz not null,is_first_touch boolean not null default false,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create unique index if not exists lead_acquisitions_one_first_touch on public.lead_acquisitions(company_id) where is_first_touch;
create table if not exists public.marketing_spend(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),provider text not null,source_id uuid references public.marketing_sources(id),campaign_id uuid references public.marketing_campaigns(id),ad_group_id uuid references public.marketing_ad_groups(id),ad_id uuid references public.marketing_ads(id),external_entity_id text,date date not null,amount numeric(14,2) not null check(amount>=0),currency char(3) not null default 'BRL',impressions bigint not null default 0 check(impressions>=0),reach bigint not null default 0 check(reach>=0),clicks bigint not null default 0 check(clicks>=0),external_conversions numeric(14,2) not null default 0 check(external_conversions>=0),external_data jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists marketing_spend_sync_unique on public.marketing_spend(organization_id,provider,external_entity_id,date) where external_entity_id is not null;
create table if not exists public.marketing_connections(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),provider text not null,external_account_id text not null,name text not null,status text not null check(status in('connected','disconnected','error','syncing')),last_sync_at timestamptz,last_successful_sync_at timestamptz,sync_error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,provider,external_account_id));
comment on table public.marketing_connections is 'Operational metadata only. API credentials belong in server-side secrets or Vault.';
create index if not exists acquisitions_company_time_idx on public.lead_acquisitions(company_id,captured_at);
create index if not exists acquisitions_opportunity_idx on public.lead_acquisitions(opportunity_id,captured_at);
create index if not exists acquisitions_campaign_time_idx on public.lead_acquisitions(campaign_id,captured_at);
create index if not exists marketing_spend_campaign_date_idx on public.marketing_spend(organization_id,campaign_id,date);
do $$ declare n text;begin foreach n in array array['marketing_sources','marketing_campaigns','marketing_ad_groups','marketing_ads','marketing_spend','marketing_connections'] loop execute format('create trigger %I_updated_at before update on public.%I for each row execute function public.set_updated_at()',n,n);end loop;end $$;
do $$ declare n text;begin foreach n in array array['marketing_sources','marketing_campaigns','marketing_ad_groups','marketing_ads','lead_acquisitions','marketing_spend','marketing_connections'] loop execute format('alter table public.%I enable row level security',n);execute format('create policy organization_isolation on public.%I for all using(organization_id=public.current_organization_id()) with check(organization_id=public.current_organization_id())',n);end loop;end $$;
create or replace function public.preserve_marketing_first_touch() returns trigger language plpgsql set search_path=public as $$ begin new.is_first_touch:=not exists(select 1 from public.lead_acquisitions where company_id=new.company_id and is_first_touch);return new;end $$;
create trigger lead_acquisitions_first_touch before insert on public.lead_acquisitions for each row execute function public.preserve_marketing_first_touch();
-- Preserve legacy CRM sources as structured manual sources and historical touchpoints.
insert into public.marketing_sources(organization_id,name,slug,channel,platform,type,is_paid)
select distinct organization_id,source,lower(regexp_replace(source,'[^a-zA-Z0-9]+','-','g')),'other','manual','legacy',false from public.companies where source is not null and btrim(source)<>'' on conflict(organization_id,slug) do nothing;
insert into public.marketing_sources(organization_id,name,slug,channel,platform,type,is_paid)
select distinct organization_id,source,lower(regexp_replace(source,'[^a-zA-Z0-9]+','-','g')),'other','manual','legacy',false from public.opportunities where source is not null and btrim(source)<>'' on conflict(organization_id,slug) do nothing;
insert into public.lead_acquisitions(organization_id,company_id,source_id,captured_at,is_first_touch,metadata)
select c.organization_id,c.id,s.id,c.created_at,true,jsonb_build_object('legacy_source',c.source) from public.companies c join public.marketing_sources s on s.organization_id=c.organization_id and s.slug=lower(regexp_replace(c.source,'[^a-zA-Z0-9]+','-','g')) where c.source is not null and btrim(c.source)<>'' and not exists(select 1 from public.lead_acquisitions a where a.company_id=c.id);
insert into public.lead_acquisitions(organization_id,company_id,opportunity_id,source_id,captured_at,metadata)
select o.organization_id,o.company_id,o.id,s.id,o.created_at,jsonb_build_object('legacy_source',o.source) from public.opportunities o join public.marketing_sources s on s.organization_id=o.organization_id and s.slug=lower(regexp_replace(o.source,'[^a-zA-Z0-9]+','-','g')) where o.source is not null and btrim(o.source)<>'' and not exists(select 1 from public.lead_acquisitions a where a.opportunity_id=o.id);
create or replace function public.upsert_marketing_spend(spend_data jsonb) returns public.marketing_spend language plpgsql security invoker set search_path=public as $$ declare result public.marketing_spend;begin insert into public.marketing_spend(organization_id,provider,source_id,campaign_id,ad_group_id,ad_id,external_entity_id,date,amount,currency,impressions,reach,clicks,external_conversions,external_data) values(public.current_organization_id(),spend_data->>'provider',(spend_data->>'source_id')::uuid,(spend_data->>'campaign_id')::uuid,(spend_data->>'ad_group_id')::uuid,(spend_data->>'ad_id')::uuid,spend_data->>'external_entity_id',(spend_data->>'date')::date,(spend_data->>'amount')::numeric,coalesce(spend_data->>'currency','BRL'),coalesce((spend_data->>'impressions')::bigint,0),coalesce((spend_data->>'reach')::bigint,0),coalesce((spend_data->>'clicks')::bigint,0),coalesce((spend_data->>'external_conversions')::numeric,0),coalesce(spend_data->'external_data','{}'::jsonb)) on conflict(organization_id,provider,external_entity_id,date) where external_entity_id is not null do update set amount=excluded.amount,currency=excluded.currency,impressions=excluded.impressions,reach=excluded.reach,clicks=excluded.clicks,external_conversions=excluded.external_conversions,external_data=excluded.external_data,updated_at=now() returning * into result;return result;end $$;
grant execute on function public.upsert_marketing_spend(jsonb) to authenticated;
