-- Indique e Ganhe 1.0: non-cash monthly credits and first-invoice promotions.
create table public.referral_campaigns(
 id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,is_active boolean not null default true,
 base_price_cents integer not null check(base_price_cents>=0),first_payment_cents integer not null check(first_payment_cents>=0),max_open_credits smallint not null default 3 check(max_open_credits between 1 and 12),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
insert into public.referral_campaigns(slug,name,base_price_cents,first_payment_cents,max_open_credits)values('indique-ganhe-2026','Indique e Ganhe',9900,5900,3);

create table public.referral_codes(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete cascade,code text not null,is_active boolean not null default true,campaign_id uuid not null references public.referral_campaigns(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,campaign_id),unique(code),check(code~'^[A-Z0-9]{8}$')
);
create table public.referrals(
 id uuid primary key default gen_random_uuid(),referrer_organization_id uuid not null references public.organizations(id)on delete cascade,referred_organization_id uuid references public.organizations(id)on delete set null,referred_lead_id uuid references public.public_sales_leads(id)on delete set null,referral_code_id uuid not null references public.referral_codes(id)on delete cascade,campaign_id uuid not null references public.referral_campaigns(id),status text not null default'lead'check(status in('lead','qualified','customer','rewarded','invalid','cancelled')),qualified_at timestamptz,converted_at timestamptz,rewarded_at timestamptz,invalidated_at timestamptz,invalid_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(referred_organization_id is null or referred_organization_id<>referrer_organization_id)
);
create unique index referral_first_valid_lead_idx on public.referrals(referred_lead_id)where referred_lead_id is not null and status not in('invalid','cancelled');
create unique index referral_first_valid_organization_idx on public.referrals(referred_organization_id)where referred_organization_id is not null and status not in('invalid','cancelled');
create index referrals_referrer_created_idx on public.referrals(referrer_organization_id,created_at desc);
create table public.referral_credits(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete cascade,referral_id uuid not null references public.referrals(id)on delete cascade,amount_cents integer not null check(amount_cents>0),currency char(3)not null default'BRL',status text not null default'available'check(status in('pending','available','applied','cancelled')),earned_at timestamptz not null default now(),applied_at timestamptz,subscription_id uuid references public.organization_subscriptions(id)on delete set null,payment_id uuid references public.subscription_payments(id)on delete set null,created_at timestamptz not null default now(),unique(referral_id),unique(payment_id)
);
create index referral_credits_open_idx on public.referral_credits(organization_id,earned_at)where status in('pending','available');
create table public.referral_subscription_benefits(
 id uuid primary key default gen_random_uuid(),referral_id uuid not null unique references public.referrals(id)on delete cascade,organization_id uuid not null unique references public.organizations(id)on delete cascade,subscription_id uuid unique references public.organization_subscriptions(id)on delete set null,campaign_id uuid not null references public.referral_campaigns(id),base_price_cents integer not null,promotional_price_cents integer not null,status text not null default'eligible'check(status in('eligible','applied','cancelled')),applied_payment_id uuid unique references public.subscription_payments(id)on delete set null,applied_at timestamptz,created_at timestamptz not null default now()
);
alter table public.public_sales_leads add column referral_code_id uuid references public.referral_codes(id);

alter table public.referral_campaigns enable row level security;alter table public.referral_codes enable row level security;alter table public.referrals enable row level security;alter table public.referral_credits enable row level security;alter table public.referral_subscription_benefits enable row level security;
create policy referral_codes_tenant_read on public.referral_codes for select to authenticated using(organization_id=public.current_organization_id());
create policy referrals_tenant_read on public.referrals for select to authenticated using(referrer_organization_id=public.current_organization_id());
create policy referral_credits_tenant_read on public.referral_credits for select to authenticated using(organization_id=public.current_organization_id());
-- No client write policies. Mutations remain security-definer workflows.

create or replace function public.generate_referral_code()returns text language plpgsql volatile set search_path=public as $$declare result text;alphabet constant text:='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';begin loop result:='';for i in 1..8 loop result:=result||substr(alphabet,1+floor(random()*length(alphabet))::int,1);end loop;exit when not exists(select 1 from public.referral_codes where code=result);end loop;return result;end$$;
create or replace function public.ensure_referral_code(target_organization_id uuid)returns public.referral_codes language plpgsql security definer set search_path=public as $$declare result public.referral_codes;campaign uuid;begin if target_organization_id<>public.current_organization_id()and not public.is_platform_admin()then raise exception'access_denied'using errcode='42501';end if;select id into campaign from public.referral_campaigns where slug='indique-ganhe-2026'and is_active;insert into public.referral_codes(organization_id,code,campaign_id)values(target_organization_id,public.generate_referral_code(),campaign)on conflict(organization_id,campaign_id)do update set updated_at=referral_codes.updated_at returning*into result;return result;end$$;
create or replace function public.initialize_referral_code()returns trigger language plpgsql security definer set search_path=public as $$declare campaign uuid;begin select id into campaign from public.referral_campaigns where slug='indique-ganhe-2026'and is_active;insert into public.referral_codes(organization_id,code,campaign_id)values(new.id,public.generate_referral_code(),campaign)on conflict(organization_id,campaign_id)do nothing;return new;end$$;
insert into public.referral_codes(organization_id,code,campaign_id)select o.id,public.generate_referral_code(),c.id from public.organizations o cross join public.referral_campaigns c where c.slug='indique-ganhe-2026'on conflict(organization_id,campaign_id)do nothing;
create trigger initialize_referral_code_on_organization after insert on public.organizations for each row execute function public.initialize_referral_code();

create or replace function public.validate_referral_code(candidate text)returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.referral_codes rc join public.referral_campaigns c on c.id=rc.campaign_id where rc.code=upper(trim(candidate))and rc.is_active and c.is_active)$$;
revoke all on function public.validate_referral_code(text)from public;grant execute on function public.validate_referral_code(text)to anon,authenticated;

-- Public acquisition remains first-valid-referral-wins and idempotent on the existing lead key.
create or replace function public.submit_public_sales_lead(lead_data jsonb)returns jsonb language plpgsql security definer set search_path=public as $$
declare destination uuid;lead_id uuid;idem uuid;digits text;normalized_email text;refcode public.referral_codes;
begin
 if coalesce(lead_data->>'website','')<>''then raise exception'invalid_submission'using errcode='22023';end if;digits:=regexp_replace(coalesce(lead_data->>'whatsapp',''),'\D','','g');normalized_email:=lower(trim(coalesce(lead_data->>'email','')));
 if length(trim(coalesce(lead_data->>'name','')))<2 or length(trim(coalesce(lead_data->>'businessName','')))<2 or length(digits)<10 or normalized_email!~'^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception'invalid_contact'using errcode='22023';end if;
 idem:=(lead_data->>'idempotency_key')::uuid;perform pg_advisory_xact_lock(hashtextextended(idem::text,0));select id into destination from public.organizations where slug='esads-beauty'limit 1;if destination is null then raise exception'sales_destination_not_configured'using errcode='P0002';end if;
 select id into lead_id from public.public_sales_leads where organization_id=destination and idempotency_key=idem;if lead_id is not null then return jsonb_build_object('id',lead_id);end if;
 if exists(select 1 from public.public_sales_leads where organization_id=destination and(whatsapp=digits or email=normalized_email)and created_at>now()-interval'60 seconds')then raise exception'rate_limited'using errcode='42900';end if;
 select rc.*into refcode from public.referral_codes rc join public.referral_campaigns c on c.id=rc.campaign_id where rc.code=upper(trim(lead_data->>'referral_code'))and rc.is_active and c.is_active;
 insert into public.public_sales_leads(organization_id,idempotency_key,name,whatsapp,email,business_name,utm_source,utm_medium,utm_campaign,utm_content,utm_term,fbclid,landing_url,referrer,referral_code_id)values(destination,idem,trim(lead_data->>'name'),digits,normalized_email,trim(lead_data->>'businessName'),lead_data#>>'{attribution,utm_source}',lead_data#>>'{attribution,utm_medium}',lead_data#>>'{attribution,utm_campaign}',lead_data#>>'{attribution,utm_content}',lead_data#>>'{attribution,utm_term}',lead_data#>>'{attribution,fbclid}',nullif(lead_data->>'landing_url',''),nullif(lead_data->>'referrer',''),refcode.id)returning id into lead_id;
 if refcode.id is not null then insert into public.referrals(referrer_organization_id,referred_lead_id,referral_code_id,campaign_id)values(refcode.organization_id,lead_id,refcode.id,refcode.campaign_id)on conflict do nothing;end if;return jsonb_build_object('id',lead_id,'referralAccepted',refcode.id is not null);
end$$;

create or replace function public.current_referral_dashboard()returns jsonb language plpgsql security definer set search_path=public as $$declare org uuid:=public.current_organization_id();rc public.referral_codes;begin if org is null then raise exception'access_denied'using errcode='42501';end if;select*into rc from public.ensure_referral_code(org);return jsonb_build_object('code',rc.code,'link','https://beauty.esads.com.br/?ref='||rc.code,'total',(select count(*)from public.referrals where referrer_organization_id=org),'converted',(select count(*)from public.referrals where referrer_organization_id=org and status in('customer','rewarded')),'availableCredits',(select count(*)from public.referral_credits where organization_id=org and status in('pending','available')),'appliedCredits',(select count(*)from public.referral_credits where organization_id=org and status='applied'),'items',(select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'referredName',l.business_name,'code',rc.code,'status',r.status,'createdAt',r.created_at,'rewardCents',cr.amount_cents)order by r.created_at desc),'[]')from public.referrals r left join public.public_sales_leads l on l.id=r.referred_lead_id left join public.referral_credits cr on cr.referral_id=r.id where r.referrer_organization_id=org));end$$;
revoke all on function public.current_referral_dashboard()from public,anon;grant execute on function public.current_referral_dashboard()to authenticated;

create or replace function public.platform_manage_referral(target_referral_id uuid,target_action text,referred_organization_id uuid default null)returns void language plpgsql security definer set search_path=public as $$declare r public.referrals;c public.referral_campaigns;s public.organization_subscriptions;open_count integer;credit_amount integer;begin
 if not public.is_platform_admin()then raise exception'platform_admin_required'using errcode='42501';end if;select*into r from public.referrals where id=target_referral_id for update;if r.id is null then raise exception'referral_not_found';end if;
 if target_action='invalidate'then if r.status='rewarded'then raise exception'rewarded_referral_immutable';end if;update public.referrals set status='invalid',invalidated_at=now(),invalid_reason='platform_admin',updated_at=now()where id=r.id;update public.referral_credits set status='cancelled'where referral_id=r.id and status in('pending','available');update public.referral_subscription_benefits set status='cancelled'where referral_id=r.id and status='eligible';
 elsif target_action='cancel_credit'then update public.referral_credits set status='cancelled'where referral_id=r.id and status in('pending','available');if not found then raise exception'credit_not_cancellable';end if;
 elsif target_action='convert'then if referred_organization_id is null or referred_organization_id=r.referrer_organization_id then update public.referrals set status='invalid',invalidated_at=now(),invalid_reason='self_referral',updated_at=now()where id=r.id;raise exception'self_referral'using errcode='22023';end if;if exists(select 1 from public.referrals x where x.referred_organization_id=referred_organization_id and x.id<>r.id and x.status not in('invalid','cancelled'))then raise exception'referred_organization_already_attributed'using errcode='23505';end if;select*into c from public.referral_campaigns where id=r.campaign_id;select*into s from public.organization_subscriptions where organization_id=referred_organization_id and status<>'cancelled'order by created_at desc limit 1;update public.referrals set referred_organization_id=platform_manage_referral.referred_organization_id,status='customer',qualified_at=coalesce(qualified_at,now()),converted_at=now(),updated_at=now()where id=r.id;insert into public.referral_subscription_benefits(referral_id,organization_id,subscription_id,campaign_id,base_price_cents,promotional_price_cents)values(r.id,referred_organization_id,s.id,c.id,c.base_price_cents,c.first_payment_cents)on conflict(referral_id)do nothing;
 -- A reward is only available after an actual paid subscription payment exists.
 if exists(select 1 from public.subscription_payments where organization_id=referred_organization_id and status='paid')then perform pg_advisory_xact_lock(hashtextextended(r.referrer_organization_id::text,0));select count(*)into open_count from public.referral_credits where organization_id=r.referrer_organization_id and status in('pending','available');if open_count<c.max_open_credits then select price_cents into credit_amount from public.organization_subscriptions where organization_id=r.referrer_organization_id and status<>'cancelled'order by created_at desc limit 1;credit_amount:=coalesce(credit_amount,c.base_price_cents);insert into public.referral_credits(organization_id,referral_id,amount_cents)values(r.referrer_organization_id,r.id,credit_amount)on conflict(referral_id)do nothing;update public.referrals set status='rewarded',rewarded_at=now()where id=r.id;end if;end if;
 else raise exception'invalid_referral_action'using errcode='22023';end if;
 insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,module,new_values)values(r.referrer_organization_id,auth.uid(),'referral_'||target_action,'referral',r.id,'referrals',jsonb_build_object('referredOrganizationId',referred_organization_id));
end$$;

create or replace function public.reward_paid_referral(target_organization_id uuid)returns void language plpgsql security definer set search_path=public as $$declare r public.referrals;c public.referral_campaigns;open_count integer;credit_amount integer;begin select*into r from public.referrals where referred_organization_id=target_organization_id and status='customer'for update;if r.id is null then return;end if;select*into c from public.referral_campaigns where id=r.campaign_id;perform pg_advisory_xact_lock(hashtextextended(r.referrer_organization_id::text,0));select count(*)into open_count from public.referral_credits where organization_id=r.referrer_organization_id and status in('pending','available');if open_count>=c.max_open_credits then return;end if;select price_cents into credit_amount from public.organization_subscriptions where organization_id=r.referrer_organization_id and status<>'cancelled'order by created_at desc limit 1;insert into public.referral_credits(organization_id,referral_id,amount_cents)values(r.referrer_organization_id,r.id,coalesce(credit_amount,c.base_price_cents))on conflict(referral_id)do nothing;update public.referrals set status='rewarded',rewarded_at=now(),updated_at=now()where id=r.id;end$$;

create or replace function public.referral_billing_quote(target_subscription_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare s public.organization_subscriptions;benefit public.referral_subscription_benefits;credit public.referral_credits;promo integer:=0;credit_value integer:=0;begin select*into s from public.organization_subscriptions where id=target_subscription_id;if s.id is null then raise exception'subscription_not_found';end if;if s.organization_id<>public.current_organization_id()and not public.is_platform_admin()then raise exception'access_denied'using errcode='42501';end if;select*into benefit from public.referral_subscription_benefits where organization_id=s.organization_id and status='eligible';if benefit.id is not null and benefit.subscription_id is null then update public.referral_subscription_benefits set subscription_id=s.id where id=benefit.id;end if;if benefit.id is not null then promo:=greatest(0,s.price_cents-benefit.promotional_price_cents);end if;select*into credit from public.referral_credits where organization_id=s.organization_id and status='available'order by earned_at,id limit 1;credit_value:=least(coalesce(credit.amount_cents,0),greatest(0,s.price_cents-promo));return jsonb_build_object('basePriceCents',s.price_cents,'promotionCents',promo,'creditCents',credit_value,'finalPriceCents',greatest(0,s.price_cents-promo-credit_value),'promotionBenefitId',benefit.id,'creditId',credit.id);end$$;

create or replace function public.consume_referral_benefits(target_subscription_id uuid,target_payment_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare quote jsonb;s public.organization_subscriptions;begin if not public.is_platform_admin()then raise exception'platform_admin_required'using errcode='42501';end if;select*into s from public.organization_subscriptions where id=target_subscription_id for update;perform pg_advisory_xact_lock(hashtextextended(s.organization_id::text,0));quote:=public.referral_billing_quote(target_subscription_id);update public.referral_subscription_benefits set status='applied',applied_payment_id=target_payment_id,applied_at=now()where id=(quote->>'promotionBenefitId')::uuid and status='eligible';update public.referral_credits set status='applied',subscription_id=s.id,payment_id=target_payment_id,applied_at=now()where id=(quote->>'creditId')::uuid and status='available';perform public.reward_paid_referral(s.organization_id);return quote;end$$;

create or replace function public.platform_referral_snapshot()returns jsonb language plpgsql security definer stable set search_path=public as $$begin if not public.is_platform_admin()then raise exception'platform_admin_required'using errcode='42501';end if;return jsonb_build_object('items',(select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'referrerOrganization',ro.name,'referredOrganization',doo.name,'referredOrganizationId',r.referred_organization_id,'referredName',l.business_name,'code',rc.code,'status',r.status,'createdAt',r.created_at,'rewardCents',cr.amount_cents,'creditStatus',cr.status)order by r.created_at desc),'[]')from public.referrals r join public.organizations ro on ro.id=r.referrer_organization_id join public.referral_codes rc on rc.id=r.referral_code_id left join public.organizations doo on doo.id=r.referred_organization_id left join public.public_sales_leads l on l.id=r.referred_lead_id left join public.referral_credits cr on cr.referral_id=r.id));end$$;

do $$declare signature text;begin foreach signature in array array['ensure_referral_code(uuid)','current_referral_dashboard()','platform_manage_referral(uuid,text,uuid)','referral_billing_quote(uuid)','consume_referral_benefits(uuid,uuid)','platform_referral_snapshot()']loop execute format('revoke all on function public.%s from public,anon',signature);execute format('grant execute on function public.%s to authenticated',signature);end loop;end$$;
revoke all on function public.generate_referral_code()from public,anon,authenticated;revoke all on function public.reward_paid_referral(uuid)from public,anon,authenticated;revoke all on function public.initialize_referral_code()from public,anon,authenticated;
notify pgrst,'reload schema';

-- Manual billing consumes the promotion/oldest credit atomically and records the net paid amount.
create or replace function public.platform_mark_subscription_paid(target_subscription_id uuid,payment_notes text default null)returns void language plpgsql security definer set search_path=public as $$
declare subscription public.organization_subscriptions;paid_time timestamptz:=now();period_start timestamptz;period_end timestamptz;payment_id uuid;quote jsonb;
begin if not public.is_platform_admin()then raise exception'platform_admin_required'using errcode='42501';end if;select*into subscription from public.organization_subscriptions where id=target_subscription_id for update;if subscription.id is null then raise exception'subscription_not_found';end if;if subscription.status='cancelled'then raise exception'cancelled_subscription';end if;quote:=public.referral_billing_quote(subscription.id);period_start:=greatest(subscription.current_period_end,paid_time);period_end:=period_start+make_interval(months=>subscription.billing_interval_months);insert into public.subscription_payments(organization_id,subscription_id,amount_cents,currency,status,payment_method,paid_at,due_at,notes,created_by)values(subscription.organization_id,subscription.id,(quote->>'finalPriceCents')::integer,subscription.currency,'paid','manual',paid_time,subscription.next_due_at,nullif(trim(payment_notes),''),auth.uid())returning id into payment_id;perform public.consume_referral_benefits(subscription.id,payment_id);update public.organization_subscriptions set status='active',last_payment_at=paid_time,current_period_start=period_start,current_period_end=period_end,next_due_at=period_end,grace_period_ends_at=period_end+make_interval(days=>grace_period_days),suspended_at=null,updated_at=now()where id=subscription.id;end$$;
revoke all on function public.platform_mark_subscription_paid(uuid,text)from public,anon;grant execute on function public.platform_mark_subscription_paid(uuid,text)to authenticated;

-- Refill a freed slot from the oldest already-paying conversion; open credits never exceed the campaign cap.
create or replace function public.fill_referral_credit_capacity(target_referrer uuid)returns void language plpgsql security definer set search_path=public as $$declare candidate public.referrals;c public.referral_campaigns;open_count integer;credit_amount integer;begin perform pg_advisory_xact_lock(hashtextextended(target_referrer::text,0));loop select count(*)into open_count from public.referral_credits where organization_id=target_referrer and status in('pending','available');select r.*into candidate from public.referrals r where r.referrer_organization_id=target_referrer and r.status='customer'and exists(select 1 from public.subscription_payments sp where sp.organization_id=r.referred_organization_id and sp.status='paid')order by r.converted_at,r.id limit 1 for update;exit when candidate.id is null;select*into c from public.referral_campaigns where id=candidate.campaign_id;exit when open_count>=c.max_open_credits;select price_cents into credit_amount from public.organization_subscriptions where organization_id=target_referrer and status<>'cancelled'order by created_at desc limit 1;insert into public.referral_credits(organization_id,referral_id,amount_cents)values(target_referrer,candidate.id,coalesce(credit_amount,c.base_price_cents))on conflict(referral_id)do nothing;update public.referrals set status='rewarded',rewarded_at=now(),updated_at=now()where id=candidate.id;end loop;end$$;
create or replace function public.reward_paid_referral(target_organization_id uuid)returns void language plpgsql security definer set search_path=public as $$declare referrer uuid;begin select referrer_organization_id into referrer from public.referrals where referred_organization_id=target_organization_id and status='customer'limit 1;if referrer is not null then perform public.fill_referral_credit_capacity(referrer);end if;end$$;
create or replace function public.consume_referral_benefits(target_subscription_id uuid,target_payment_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare quote jsonb;s public.organization_subscriptions;begin if not public.is_platform_admin()then raise exception'platform_admin_required'using errcode='42501';end if;select*into s from public.organization_subscriptions where id=target_subscription_id for update;perform pg_advisory_xact_lock(hashtextextended(s.organization_id::text,0));quote:=public.referral_billing_quote(target_subscription_id);update public.referral_subscription_benefits set status='applied',applied_payment_id=target_payment_id,applied_at=now()where id=(quote->>'promotionBenefitId')::uuid and status='eligible';update public.referral_credits set status='applied',subscription_id=s.id,payment_id=target_payment_id,applied_at=now()where id=(quote->>'creditId')::uuid and status='available';perform public.fill_referral_credit_capacity(s.organization_id);perform public.reward_paid_referral(s.organization_id);return quote;end$$;
revoke all on function public.fill_referral_credit_capacity(uuid)from public,anon,authenticated;revoke all on function public.reward_paid_referral(uuid)from public,anon,authenticated;
