import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

export function ContactQuickForm({ onSubmit }: { onSubmit: (data: any) => void }) { const [data, setData] = useState<any>({ name: '', status: 'ativo', isPrimary: false, isFinancial: false, isCommercial: true }); const set = (key: string, value: any) => setData((current: any) => ({ ...current, [key]: value })); return <div className="grid gap-3 md:grid-cols-2"><Input placeholder="Nome" onChange={(e) => set('name', e.target.value)}/><Input placeholder="Cargo" onChange={(e) => set('role', e.target.value)}/><Input placeholder="WhatsApp" onChange={(e) => set('whatsapp', e.target.value)}/><Input placeholder="Email" onChange={(e) => set('email', e.target.value)}/><Input placeholder="Instagram" onChange={(e) => set('instagram', e.target.value)}/><Input placeholder="LinkedIn" onChange={(e) => set('linkedin', e.target.value)}/><label className="flex items-center gap-2 text-sm"><Checkbox checked={data.isPrimary} onChange={(e) => set('isPrimary', e.currentTarget.checked)}/> Principal</label><label className="flex items-center gap-2 text-sm"><Checkbox checked={data.isFinancial} onChange={(e) => set('isFinancial', e.currentTarget.checked)}/> Financeiro</label><Textarea className="md:col-span-2" placeholder="Observações" onChange={(e) => set('notes', e.target.value)}/><Button className="md:col-span-2" onClick={() => onSubmit(data)}>Adicionar contato</Button></div>; }
export function FollowUpQuickForm({ onSubmit }: { onSubmit: (data: any) => void }) { const [data, setData] = useState<any>({ title: '', date: new Date().toISOString().slice(0,10), time: '09:00', owner: 'Administrador', priority: 'media', type: 'ligacao', status: 'pendente' }); const set = (key: string, value: any) => setData((current: any) => ({ ...current, [key]: value })); return <div className="grid gap-3 md:grid-cols-2"><Input placeholder="Título" onChange={(e) => set('title', e.target.value)}/><Input type="date" value={data.date} onChange={(e) => set('date', e.target.value)}/><Input type="time" value={data.time} onChange={(e) => set('time', e.target.value)}/><Select value={data.priority} onChange={(e) => set('priority', e.target.value)}><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option></Select><Select value={data.type} onChange={(e) => set('type', e.target.value)}><option value="ligacao">Ligação</option><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="reuniao">Reunião</option><option value="proposta">Proposta</option></Select><Textarea className="md:col-span-2" placeholder="Descrição" onChange={(e) => set('description', e.target.value)}/><Button className="md:col-span-2" onClick={() => onSubmit(data)}>Criar follow-up</Button></div>; }
export function ActivityQuickForm({ onSubmit }: { onSubmit: (data: any) => void }) { const [data, setData] = useState<any>({ title: '', type: 'reuniao', date: new Date().toISOString().slice(0,10), time: '10:00', durationMinutes: 60, owner: 'Administrador', status: 'agendado' }); const set = (key: string, value: any) => setData((current: any) => ({ ...current, [key]: value })); return <div className="grid gap-3 md:grid-cols-2"><Input placeholder="Título" onChange={(e) => set('title', e.target.value)}/><Select value={data.type} onChange={(e) => set('type', e.target.value)}><option value="ligacao">Ligação</option><option value="whatsapp">WhatsApp</option><option value="reuniao">Reunião</option><option value="visita">Visita</option><option value="videochamada">Videochamada</option><option value="apresentacao">Apresentação</option><option value="retorno">Retorno</option></Select><Input type="date" value={data.date} onChange={(e) => set('date', e.target.value)}/><Input type="time" value={data.time} onChange={(e) => set('time', e.target.value)}/><Input placeholder="Local" onChange={(e) => set('location', e.target.value)}/><Input type="number" value={data.durationMinutes} onChange={(e) => set('durationMinutes', Number(e.target.value))}/><Button className="md:col-span-2" onClick={() => onSubmit(data)}>Agendar</Button></div>; }
